project:
  type: website

website:
  title: "NYX Geospatial App"
  navbar:
    left: 
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex1/Hands-on_Ex1.qmd"

    right:
      - href: index.qmd
        text: Home
      - about.qmd
      
  sidebar:
    style: 'docked'
    background: light
    contents:
      - section: "Hands-on Exercise"
        contents:
          - Hands-on_Ex1/Hands-on_Ex1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

