project:
  type: website

website:
  title: "NYX Geospatial App"
  navbar:
    left: 
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1.1"
            href: "Hands-on_Ex1/Hands-on_Ex1_1.qmd"
          - text: "Hands-on Exercise 1.2"
            href: "Hands-on_Ex1/Hands-on_Ex1_2.qmd"
          - text: "Hands-on Exercise 2.1"
            href: "Hands-on_Ex2/Hands-on_Ex2_1.qmd"
          - text: "Hands-on Exercise 2.2"
            href: "Hands-on_Ex2/Hands-on_Ex2_2.qmd"
          - text: "Hands-on Exercise 2.3"
            href: "Hands-on_Ex2/Hands-on_Ex2_3.qmd"
          - text: "Hands-on Exercise 3.1"
            href: "Hands-on_Ex3/Hands-on_Ex3_1.qmd"
            
      - text: "Take-home Exercises"
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex1/Take-home_Ex1.qmd"
          - text: "Take-home Exercise 2"
 
            
      - text: "In-class Exercises"      
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex1/In-class_Ex1.qmd"
          - text: "In-class Exercise 2"
            href: "In-class_Ex2/In-class_Ex2.qmd"
          - text: "In-class Exercise 3"
            href: "In-class_Ex3/In-class_Ex3_2.qmd"
          #- text: "In-class Exercise 4"
          #- text: "In-class Exercise 5"

    right:
      - href: index.qmd
        text: Home
      - about.qmd
      
  sidebar:
    style: 'docked'
    background: light
    contents:
      - section: "Hands-on Exercise"
        contents:
          - Hands-on_Ex1/Hands-on_Ex1_1.qmd
          - Hands-on_Ex1/Hands-on_Ex1_2.qmd
          - Hands-on_Ex2/Hands-on_Ex2_1.qmd
          - Hands-on_Ex2/Hands-on_Ex2_2.qmd
          - Hands-on_Ex2/Hands-on_Ex2_3.qmd
          - Hands-on_Ex3/Hands-on_Ex3_1.qmd
          #- Hands-on_Ex4/Hands-on_Ex4_1.qmd
          #- Hands-on_Ex5/Hands-on_Ex5_1.qmd
          
      - section: "Take-home Exercise"
        contents:
          - Take-home_Ex1/Take-home_Ex1.qmd
          #- Take-home_Ex2/Take-home_Ex2.qmd
          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

