<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="NeoYX">
<meta name="dcterms.date" content="2023-11-25">

<title>NYX Geospatial App - In-class Exercise 2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="../site_libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<script src="../site_libs/plotly-binding-4.10.3/plotly.js"></script>
<script src="../site_libs/typedarray-0.1/typedarray.min.js"></script>
<script src="../site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="../site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet">
<script src="../site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="../site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>
<link href="../site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="../site_libs/datatables-binding-0.30/datatables.js"></script>
<link href="../site_libs/dt-core-1.13.4/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="../site_libs/dt-core-1.13.4/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="../site_libs/dt-core-1.13.4/js/jquery.dataTables.min.js"></script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">NYX Geospatial App</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercises">    
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex1/Hands-on_Ex1_1.html">
 <span class="dropdown-text">Hands-on Exercise 1.1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex1/Hands-on_Ex1_2.html">
 <span class="dropdown-text">Hands-on Exercise 1.2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex2/Hands-on_Ex2_1.html">
 <span class="dropdown-text">Hands-on Exercise 2.1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex2/Hands-on_Ex2_2.html">
 <span class="dropdown-text">Hands-on Exercise 2.2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex2/Hands-on_Ex2_3.html">
 <span class="dropdown-text">Hands-on Exercise 2.3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex3/Hands-on_Ex3_1.html">
 <span class="dropdown-text">Hands-on Exercise 3.1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Hands-on_Ex4/Hands-on_Ex4_1.html">
 <span class="dropdown-text">Hands-on Exercise 4.1</span></a>
  </li>  
        <li class="dropdown-header">Hands-on Exercise 5.1</li>
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercises">    
        <li>
    <a class="dropdown-item" href="../Take-home_Ex1/Take-home_Ex1.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../Take-home_Ex2/Take-home_Ex2.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercises" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercises</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercises">    
        <li>
    <a class="dropdown-item" href="../In-class_Ex1/In-class_Ex1.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../In-class_Ex2/In-class_Ex2.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../In-class_Ex3/In-class_Ex3_2.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../In-class_Ex4/In-class_Ex4.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li class="dropdown-header">In-class Exercise 5</li>
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">In-class Exercise 2</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">Hands-on Exercise</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Hands-on_Ex1/Hands-on_Ex1_1.html" class="sidebar-item-text sidebar-link">Hands-on Exercise 1.1: Geospatial Data Wrangling with R</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Hands-on_Ex1/Hands-on_Ex1_2.html" class="sidebar-item-text sidebar-link">Hands-on Exercise 1.2: Choropleth Mapping with R</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Hands-on_Ex2/Hands-on_Ex2_1.html" class="sidebar-item-text sidebar-link">Hands-on Exercise 2.1: Spatial Weights and Applications</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Hands-on_Ex2/Hands-on_Ex2_2.html" class="sidebar-item-text sidebar-link">Hands-on Exercise 2.2 and 2.3: Global and Local Measures of Spatial Autocorrelation</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Hands-on_Ex2/Hands-on_Ex2_3.html" class="sidebar-item-text sidebar-link">Hands-on Exercise 2.3:Local Measures of Spatial Autocorrelation</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Hands-on_Ex3/Hands-on_Ex3_1.html" class="sidebar-item-text sidebar-link">Hands-on Exercise 3.1: Processing and Visualising Flow Data</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Hands-on_Ex4/Hands-on_Ex4_1.html" class="sidebar-item-text sidebar-link">Hands-on Exercise 4.1: Geopraphically Weighted Regression</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Take-home Exercise</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Take-home_Ex1/Take-home_Ex1.html" class="sidebar-item-text sidebar-link">Take-home_Ex1: Geospatial Analytics for Public Good</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Take-home_Ex2/Take-home_Ex2.html" class="sidebar-item-text sidebar-link">Take-home_Ex2: Applied Spatial Interaction Models: A case study of Singapore public bus commuter flows</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started">Getting started</a>
  <ul class="collapse">
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The data</a>
  <ul class="collapse">
  <li><a href="#part-1-spatial-weights---sfdep-methods" id="toc-part-1-spatial-weights---sfdep-methods" class="nav-link" data-scroll-target="#part-1-spatial-weights---sfdep-methods">Part 1: Spatial weights - sfdep methods</a></li>
  <li><a href="#part-2-performing-global-and-local-autocorrelation-of-spatial-association-using-sfdep-methods" id="toc-part-2-performing-global-and-local-autocorrelation-of-spatial-association-using-sfdep-methods" class="nav-link" data-scroll-target="#part-2-performing-global-and-local-autocorrelation-of-spatial-association-using-sfdep-methods">Part 2 : Performing Global and Local autocorrelation of spatial association using sfdep methods</a></li>
  <li><a href="#part-3-hot-spot-and-cold-spot-area-analysis-hcsa" id="toc-part-3-hot-spot-and-cold-spot-area-analysis-hcsa" class="nav-link" data-scroll-target="#part-3-hot-spot-and-cold-spot-area-analysis-hcsa">Part 3: Hot Spot and Cold Spot Area Analysis (HCSA)</a></li>
  <li><a href="#part-4-emerging-hotspots-analysis" id="toc-part-4-emerging-hotspots-analysis" class="nav-link" data-scroll-target="#part-4-emerging-hotspots-analysis">Part 4: Emerging hotspots analysis</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">In-class Exercise 2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>NeoYX </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 25, 2023</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">November 27, 2023</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="getting-started" class="level1">
<h1>Getting started</h1>
<p>Installing and loading the required R packages.</p>
<p><code>dplyr</code>: reshape data, joins, pivot for instance..</p>
<p><code>tidyr</code>: transform data</p>
<p><code>knitr</code>: generate html table</p>
<p>Today, <code>sfdep</code> library will replace the <code>spdep</code> library because it is more recent (&lt;2 years ago). Allows to <u>mutate</u> using <u>spatial function</u>s. <code>spdep</code> does not allow for mutate for instance.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tmap, sfdep, tidyverse, knitr, plotly,Kendall, DT)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The data</h2>
<ul>
<li><p>Hunan, geospatial dataset in shapefile format</p></li>
<li><p>Hunan_2012, an attribute dataset in csv format</p></li>
</ul>
<section id="part-1-spatial-weights---sfdep-methods" class="level3">
<h3 class="anchored" data-anchor-id="part-1-spatial-weights---sfdep-methods">Part 1: Spatial weights - sfdep methods</h3>
<section id="import-geospatial-and-aspatial-data" class="level4">
<h4 class="anchored" data-anchor-id="import-geospatial-and-aspatial-data">Import geospatial and aspatial data</h4>
<p>In the code chunk below , import geospatial data using st_read() from <code>sf</code> library. The output has projection of WSG84 and 88 observations. Class of ‘sf’ and ‘tibble df’, and in tibble df contains a geometry list. In ‘sf’, each row/observation represents a geographical region/area/unit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a> hunan<span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="at">dsn=</span><span class="st">"data/geospatial"</span>, <span class="at">layer =</span> <span class="st">"Hunan"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `Hunan' from data source 
  `C:\yixin-neo\ISSS624_AGA\In-class_Ex2\data\geospatial' using driver `ESRI Shapefile'
Simple feature collection with 88 features and 7 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1"></a> <span class="fu">class</span>(hunan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
</div>
<p>In the code chunk below , import aspatial data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1"></a>hunan_2012 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/aspatial/Hunan_2012.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Combine both files together using left_join hunan (geo) with hunan_2012 (aspatial) to retain the <code>sf</code> class. If the unique identifier is not specified, R will use identical columns, in this case ‘County’ columns in both objects.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>hunan_GDPPC <span class="ot">&lt;-</span> <span class="fu">left_join</span>(hunan, hunan_2012,</span>
<span id="cb7-2"><a href="#cb7-2"></a>                   <span class="at">by =</span> <span class="fu">c</span>(<span class="st">'County'</span> <span class="ot">=</span> <span class="st">'County'</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>, <span class="dv">7</span>,<span class="dv">15</span>)</span>
<span id="cb7-4"><a href="#cb7-4"></a></span>
<span id="cb7-5"><a href="#cb7-5"></a>hunan</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 88 features and 7 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812
Geodetic CRS:  WGS 84
First 10 features:
     NAME_2  ID_3    NAME_3   ENGTYPE_3 Shape_Leng Shape_Area    County
1   Changde 21098   Anxiang      County   1.869074 0.10056190   Anxiang
2   Changde 21100   Hanshou      County   2.360691 0.19978745   Hanshou
3   Changde 21101    Jinshi County City   1.425620 0.05302413    Jinshi
4   Changde 21102        Li      County   3.474325 0.18908121        Li
5   Changde 21103     Linli      County   2.289506 0.11450357     Linli
6   Changde 21104    Shimen      County   4.171918 0.37194707    Shimen
7  Changsha 21109   Liuyang County City   4.060579 0.46016789   Liuyang
8  Changsha 21110 Ningxiang      County   3.323754 0.26614198 Ningxiang
9  Changsha 21111 Wangcheng      County   2.292093 0.13049161 Wangcheng
10 Chenzhou 21112     Anren      County   2.240739 0.13343936     Anren
                         geometry
1  POLYGON ((112.0625 29.75523...
2  POLYGON ((112.2288 29.11684...
3  POLYGON ((111.8927 29.6013,...
4  POLYGON ((111.3731 29.94649...
5  POLYGON ((111.6324 29.76288...
6  POLYGON ((110.8825 30.11675...
7  POLYGON ((113.9905 28.5682,...
8  POLYGON ((112.7181 28.38299...
9  POLYGON ((112.7914 28.52688...
10 POLYGON ((113.1757 26.82734...</code></pre>
</div>
</div>
<p>Plot a choropleth map</p>
<div class="cell" data-fig.asp="0.68">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="fu">tm_shape</span>(hunan_GDPPC) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3"></a>  <span class="fu">tm_fill</span>(<span class="st">"GDPPC"</span>, </span>
<span id="cb9-4"><a href="#cb9-4"></a>          <span class="at">style =</span> <span class="st">"quantile"</span>, </span>
<span id="cb9-5"><a href="#cb9-5"></a>          <span class="at">palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb9-6"><a href="#cb9-6"></a>          <span class="at">title =</span> <span class="st">"GDPPC"</span>) <span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Distribution of GDP per capita by district, Hunan Province"</span>,</span>
<span id="cb9-9"><a href="#cb9-9"></a>            <span class="at">main.title.position =</span> <span class="st">"center"</span>,</span>
<span id="cb9-10"><a href="#cb9-10"></a>            <span class="at">main.title.size =</span> <span class="fl">1.2</span>,</span>
<span id="cb9-11"><a href="#cb9-11"></a>            <span class="at">legend.height =</span> <span class="fl">0.45</span>, </span>
<span id="cb9-12"><a href="#cb9-12"></a>            <span class="at">legend.width =</span> <span class="fl">0.35</span>,</span>
<span id="cb9-13"><a href="#cb9-13"></a>            <span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb9-14"><a href="#cb9-14"></a>  <span class="fu">tm_compass</span>(<span class="at">type=</span><span class="st">"8star"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb9-15"><a href="#cb9-15"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb9-16"><a href="#cb9-16"></a>  <span class="fu">tm_grid</span>(<span class="at">alpha =</span><span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="1344"></p>
</div>
</div>
</section>
<section id="identifying-contiguity-neighbours-using-queens-method" class="level4">
<h4 class="anchored" data-anchor-id="identifying-contiguity-neighbours-using-queens-method">1.1 Identifying contiguity neighbours using Queen’s method</h4>
<p>We can see the neighbours list in the first column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1"></a>nb_queen <span class="ot">&lt;-</span> hunan_GDPPC <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb10-3"><a href="#cb10-3"></a>         <span class="at">.before =</span> <span class="dv">1</span>)</span>
<span id="cb10-4"><a href="#cb10-4"></a></span>
<span id="cb10-5"><a href="#cb10-5"></a><span class="fu">kable</span>(<span class="fu">head</span>(nb_queen,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 18%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">nb</th>
<th style="text-align: left;">NAME_2</th>
<th style="text-align: right;">ID_3</th>
<th style="text-align: left;">NAME_3</th>
<th style="text-align: left;">ENGTYPE_3</th>
<th style="text-align: left;">County</th>
<th style="text-align: right;">GDPPC</th>
<th style="text-align: left;">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2, 3, 4, 57, 85</td>
<td style="text-align: left;">Changde</td>
<td style="text-align: right;">21098</td>
<td style="text-align: left;">Anxiang</td>
<td style="text-align: left;">County</td>
<td style="text-align: left;">Anxiang</td>
<td style="text-align: right;">23667</td>
<td style="text-align: left;">POLYGON ((112.0625 29.75523…</td>
</tr>
<tr class="even">
<td style="text-align: left;">1, 57, 58, 78, 85</td>
<td style="text-align: left;">Changde</td>
<td style="text-align: right;">21100</td>
<td style="text-align: left;">Hanshou</td>
<td style="text-align: left;">County</td>
<td style="text-align: left;">Hanshou</td>
<td style="text-align: right;">20981</td>
<td style="text-align: left;">POLYGON ((112.2288 29.11684…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1, 4, 5, 85</td>
<td style="text-align: left;">Changde</td>
<td style="text-align: right;">21101</td>
<td style="text-align: left;">Jinshi</td>
<td style="text-align: left;">County City</td>
<td style="text-align: left;">Jinshi</td>
<td style="text-align: right;">34592</td>
<td style="text-align: left;">POLYGON ((111.8927 29.6013,…</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Identifying higher order neighbors</strong></p>
<p>To identify higher order contiguity nb, we can use <code>st_nb_lag_cumul()</code> should be used as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>nb2_queen <span class="ot">&lt;-</span>  hunan_GDPPC <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb11-3"><a href="#cb11-3"></a>         <span class="at">nb2 =</span> <span class="fu">st_nb_lag_cumul</span>(nb, <span class="dv">2</span>),</span>
<span id="cb11-4"><a href="#cb11-4"></a>         <span class="at">.before =</span> <span class="dv">1</span>)</span>
<span id="cb11-5"><a href="#cb11-5"></a></span>
<span id="cb11-6"><a href="#cb11-6"></a><span class="fu">kable</span>(<span class="fu">head</span>(nb2_queen,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 11%">
<col style="width: 39%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">nb</th>
<th style="text-align: left;">nb2</th>
<th style="text-align: left;">NAME_2</th>
<th style="text-align: right;">ID_3</th>
<th style="text-align: left;">NAME_3</th>
<th style="text-align: left;">ENGTYPE_3</th>
<th style="text-align: left;">County</th>
<th style="text-align: right;">GDPPC</th>
<th style="text-align: left;">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2, 3, 4, 57, 85</td>
<td style="text-align: left;">2, 3, 4, 5, 6, 32, 56, 57, 58, 64, 69, 75, 76, 78, 85</td>
<td style="text-align: left;">Changde</td>
<td style="text-align: right;">21098</td>
<td style="text-align: left;">Anxiang</td>
<td style="text-align: left;">County</td>
<td style="text-align: left;">Anxiang</td>
<td style="text-align: right;">23667</td>
<td style="text-align: left;">POLYGON ((112.0625 29.75523…</td>
</tr>
<tr class="even">
<td style="text-align: left;">1, 57, 58, 78, 85</td>
<td style="text-align: left;">1, 3, 4, 5, 6, 8, 9, 32, 56, 57, 58, 64, 68, 69, 75, 76, 78, 85</td>
<td style="text-align: left;">Changde</td>
<td style="text-align: right;">21100</td>
<td style="text-align: left;">Hanshou</td>
<td style="text-align: left;">County</td>
<td style="text-align: left;">Hanshou</td>
<td style="text-align: right;">20981</td>
<td style="text-align: left;">POLYGON ((112.2288 29.11684…</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1, 4, 5, 85</td>
<td style="text-align: left;">1, 2, 4, 5, 6, 32, 56, 57, 69, 75, 78, 85</td>
<td style="text-align: left;">Changde</td>
<td style="text-align: right;">21101</td>
<td style="text-align: left;">Jinshi</td>
<td style="text-align: left;">County City</td>
<td style="text-align: left;">Jinshi</td>
<td style="text-align: right;">34592</td>
<td style="text-align: left;">POLYGON ((111.8927 29.6013,…</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="deriving-contiguity-spatial-weights" class="level4">
<h4 class="anchored" data-anchor-id="deriving-contiguity-spatial-weights">1.2 Deriving Contiguity Spatial Weights</h4>
<p>Deriving Contiguity spatial weights using <code>sfdep</code> (wrapper of spdep: allows for mutate using spatial functions) instead of <code>spdep</code> library.</p>
<p>In the code chunk below <a href="https://sfdep.josiahparry.com/reference/st_contiguity.html"><code>st_contiguity()</code></a> is used to derive a contiguity neighbour list by using Queen’s method.</p>
<p>Use two functions from <code>spdep</code> library, use less objects.</p>
<p>Note: ‘<em>nb</em>’ and ‘<em>wt</em>’ fields contain lists.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1"></a>wm_q <span class="ot">&lt;-</span> hunan_GDPPC <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry), <span class="co"># calculate by queen default</span></span>
<span id="cb12-3"><a href="#cb12-3"></a>         <span class="at">wt =</span> <span class="fu">st_weights</span>(nb,           <span class="co"># calculate row-stand spatial weight matrix</span></span>
<span id="cb12-4"><a href="#cb12-4"></a>                         <span class="at">style=</span><span class="st">'W'</span>),</span>
<span id="cb12-5"><a href="#cb12-5"></a>         <span class="at">.before =</span><span class="dv">1</span>)   <span class="co"># put these two columns at front of wm_q sf df</span></span>
<span id="cb12-6"><a href="#cb12-6"></a></span>
<span id="cb12-7"><a href="#cb12-7"></a><span class="fu">class</span>(wm_q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
</div>
</section>
<section id="distance-based-weights" class="level4">
<h4 class="anchored" data-anchor-id="distance-based-weights">1.3 Distance based-weights</h4>
<p>There are three popularly used distance-based spatial weights, they are:</p>
<ul>
<li><p>fixed distance weights,</p></li>
<li><p>adaptive distance weights, and</p></li>
<li><p>inverse distance weights (IDW).</p></li>
</ul>
<section id="deriving-fixed-distance-weights" class="level5">
<h5 class="anchored" data-anchor-id="deriving-fixed-distance-weights">1.3.1 Deriving fixed distance weights</h5>
<p>To determine the upper limit for distance band:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1"></a>geo <span class="ot">&lt;-</span> sf<span class="sc">::</span><span class="fu">st_geometry</span>(hunan_GDPPC)</span>
<span id="cb14-2"><a href="#cb14-2"></a>nb <span class="ot">&lt;-</span> <span class="fu">st_knn</span>(geo, <span class="at">k=</span><span class="dv">1</span>, <span class="at">longlat =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-3"><a href="#cb14-3"></a></span>
<span id="cb14-4"><a href="#cb14-4"></a>dists <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">st_nb_dists</span>(geo, nb))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<blockquote class="blockquote">
<ul>
<li><p><a href="https://sfdep.josiahparry.com/reference/st_nb_dists.html"><code>st_nb_dists()</code></a> of sfdep is used to calculate the nearest neighbour distance. The output is a list of distances for each observation’s neighbors list.</p></li>
<li><p><a href="https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/unlist"><code>unlist()</code></a> of Base R is then used to return the output as a vector so that the summary statistics of the nearest neighbour distances can be derived.</p></li>
</ul>
</blockquote>
<p>Derieve summary statistics of nearest nb distances</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="fu">summary</span>(dists)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  21.56   29.11   36.89   37.34   43.21   65.80 </code></pre>
</div>
</div>
<p>The maximum nearest neighbour distance is 65.8 km, thus we will use threshold value of 66km to ensure each spatial unit as least one neighbour.</p>
<p>Compute the fixed distance weights by using the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a>wm_fd <span class="ot">&lt;-</span> hunan_GDPPC <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_dist_band</span>(geometry,</span>
<span id="cb17-3"><a href="#cb17-3"></a>                           <span class="at">upper =</span> <span class="dv">66</span>),</span>
<span id="cb17-4"><a href="#cb17-4"></a>               <span class="at">wt =</span> <span class="fu">st_weights</span>(nb,</span>
<span id="cb17-5"><a href="#cb17-5"></a>                               <span class="at">style =</span> <span class="st">'W'</span>),</span>
<span id="cb17-6"><a href="#cb17-6"></a>               <span class="at">.before =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p><a href="https://sfdep.josiahparry.com/reference/st_dist_band.html"><code>st_dists_band()</code></a> of sfdep is used to identify neighbors based on a distance band (i.e.&nbsp;66km). The output is a list of neighbours (i.e.&nbsp;nb).</p></li>
<li><p><a href="https://sfdep.josiahparry.com/reference/st_weights.html"><code>st_weights()</code></a> is then used to calculate polygon spatial weights of the nb list. Note that:</p>
<ul>
<li><p>the default <code>style</code> argument is set to “W” for row standardized weights, and</p></li>
<li><p>the default <code>allow_zero</code> is set to TRUE, assigns zero as lagged value to zone without neighbors.</p></li>
</ul></li>
</ul>
</section>
<section id="section" class="level5">
<h5 class="anchored" data-anchor-id="section"></h5>
</section>
<section id="deriving-adaptive-distance-weights" class="level5">
<h5 class="anchored" data-anchor-id="deriving-adaptive-distance-weights">1.3.2 Deriving adaptive distance weights</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>wm_ad <span class="ot">&lt;-</span> hunan_GDPPC <span class="sc">%&gt;%</span> </span>
<span id="cb18-2"><a href="#cb18-2"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_knn</span>(geometry,</span>
<span id="cb18-3"><a href="#cb18-3"></a>                     <span class="at">k=</span><span class="dv">8</span>),</span>
<span id="cb18-4"><a href="#cb18-4"></a>         <span class="at">wt =</span> <span class="fu">st_weights</span>(nb),  <span class="co"># refers to `nb` generated above light</span></span>
<span id="cb18-5"><a href="#cb18-5"></a>               <span class="at">.before =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p><a href="https://sfdep.josiahparry.com/reference/st_knn.html"><code>st_knn()</code></a> of sfdep is used to identify neighbors based on k (i.e.&nbsp;k = 8 indicates the nearest eight neighbours). The output is a list of neighbours (i.e.&nbsp;nb).</p></li>
<li><p><a href="https://sfdep.josiahparry.com/reference/st_weights.html"><code>st_weights()</code></a> is then used to calculate polygon spatial weights of the nb list. Note that:</p>
<ul>
<li><p>the default <code>style</code> argument is set to “W” for row standardized weights, and</p></li>
<li><p>the default <code>allow_zero</code> is set to TRUE, assigns zero as lagged value to zone without neighbors.</p></li>
</ul></li>
</ul>
</section>
<section id="calculate-inverse-distance-weights" class="level5">
<h5 class="anchored" data-anchor-id="calculate-inverse-distance-weights">1.3.3 Calculate inverse distance weights</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a>wm_idw <span class="ot">&lt;-</span> hunan_GDPPC <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2"></a>  <span class="fu">mutate</span>(<span class="at">nb =</span> <span class="fu">st_contiguity</span>(geometry),</span>
<span id="cb19-3"><a href="#cb19-3"></a>         <span class="at">wts =</span> <span class="fu">st_inverse_distance</span>(nb, geometry,</span>
<span id="cb19-4"><a href="#cb19-4"></a>                                   <span class="at">scale =</span> <span class="dv">1</span>,</span>
<span id="cb19-5"><a href="#cb19-5"></a>                                   <span class="at">alpha =</span> <span class="dv">1</span>),</span>
<span id="cb19-6"><a href="#cb19-6"></a>         <span class="at">.before =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p><a href="https://sfdep.josiahparry.com/reference/st_contiguity.html"><code>st_contiguity()</code></a> of sfdep is used to identify the neighbours by using contiguity criteria. The output is a list of neighbours (i.e.&nbsp;nb).</p></li>
<li><p><a href="https://sfdep.josiahparry.com/reference/st_inverse_distance.html"><code>st_inverse_distance()</code></a> is then used to calculate inverse distance weights of neighbours on the nb list.</p></li>
</ul>
</section>
</section>
</section>
<section id="part-2-performing-global-and-local-autocorrelation-of-spatial-association-using-sfdep-methods" class="level3">
<h3 class="anchored" data-anchor-id="part-2-performing-global-and-local-autocorrelation-of-spatial-association-using-sfdep-methods">Part 2 : Performing Global and Local autocorrelation of spatial association using sfdep methods</h3>
<p>After deriving the spatial weights matrix <code>wm_q</code> (class: ‘sf’ and ‘df’ ) (‘nb’ and ‘wt’) using the Queen’s method, we can calculate</p>
<section id="computing-global-moran-i-no-simulation" class="level4">
<h4 class="anchored" data-anchor-id="computing-global-moran-i-no-simulation">2.1 Computing Global Moran’ I (No simulation)</h4>
<p>Using the sfdep package, it can be calculated using the code chunk below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a><span class="fu">global_moran_test</span>(wm_q<span class="sc">$</span>GDPPC,</span>
<span id="cb20-2"><a href="#cb20-2"></a>                       wm_q<span class="sc">$</span>nb,</span>
<span id="cb20-3"><a href="#cb20-3"></a>                       wm_q<span class="sc">$</span>wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  x  
weights: listw    

Moran I statistic standard deviate = 4.7351, p-value = 1.095e-06
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
      0.300749970      -0.011494253       0.004348351 </code></pre>
</div>
</div>
<ul>
<li><p>The default for <code>alternative</code> argument is “two.sided”. Other supported arguments are “greater” or “less”. randomization, and</p></li>
<li><p>By default the <code>randomization</code> argument is <strong>TRUE</strong>. If FALSE, under the assumption of normality.</p></li>
</ul>
</section>
<section id="computing-global-moran-i-simulation" class="level4">
<h4 class="anchored" data-anchor-id="computing-global-moran-i-simulation">2.2 Computing Global Moran’ I (Simulation)</h4>
<p>Monte carlo simulation should be used to perform the statistical test. For <strong>sfdep</strong>, it is supported by <a href="https://sfdep.josiahparry.com/reference/global_moran_perm.html"><code>globel_moran_perm()</code></a>. Do not assume normality.</p>
<p>It is always a good practice to use <code>set.seed()</code> before performing simulation. This is to ensure that the computation is reproducible.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="fu">global_moran_perm</span>(wm_q<span class="sc">$</span>GDPPC,</span>
<span id="cb23-2"><a href="#cb23-2"></a>                       wm_q<span class="sc">$</span>nb,</span>
<span id="cb23-3"><a href="#cb23-3"></a>                       wm_q<span class="sc">$</span>wt,</span>
<span id="cb23-4"><a href="#cb23-4"></a>                  <span class="at">nsim =</span> <span class="dv">99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Monte-Carlo simulation of Moran I

data:  x 
weights: listw  
number of simulations + 1: 100 

statistic = 0.30075, observed rank = 100, p-value &lt; 2.2e-16
alternative hypothesis: two.sided</code></pre>
</div>
</div>
<p>Since p-value is smaller than 0.05 , we can reject the null hypothesis that the spatial patterns spatial independent. Because the Moran’s I statistics is <strong>greater than 0</strong>. We can infer the spatial distribution shows sign of <strong>clustering</strong>.</p>
</section>
<section id="local-moran-using-sfdep." class="level4">
<h4 class="anchored" data-anchor-id="local-moran-using-sfdep."><strong>2.3 Local Moran using sfdep.</strong></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a>lisa <span class="ot">&lt;-</span> wm_q <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2"></a>  <span class="fu">mutate</span>(<span class="at">local_moran =</span> <span class="fu">local_moran</span>(</span>
<span id="cb25-3"><a href="#cb25-3"></a>    GDPPC, nb,wt, <span class="at">nsim=</span><span class="dv">99</span>),   <span class="co"># straightaway use simulation instead of typical p-value</span></span>
<span id="cb25-4"><a href="#cb25-4"></a>    <span class="at">.before=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-5"><a href="#cb25-5"></a>  <span class="fu">unnest</span>(local_moran)  <span class="co"># due to local_moran() function it produces output in a group object. to see it, need to unnest()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The output of local_moran() is a sf df containing the columns</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="fu">colnames</span>(lisa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "ii"           "eii"          "var_ii"       "z_ii"         "p_ii"        
 [6] "p_ii_sim"     "p_folded_sim" "skewness"     "kurtosis"     "mean"        
[11] "median"       "pysal"        "nb"           "wt"           "NAME_2"      
[16] "ID_3"         "NAME_3"       "ENGTYPE_3"    "County"       "GDPPC"       
[21] "geometry"    </code></pre>
</div>
</div>
<ul>
<li><p>ii: local moran statistic</p></li>
<li><p>eii: expectation of local moran statistic; for localmoran_permthe permutation sample means</p></li>
<li><p>var_ii: variance of local moran statistic; for localmoran_permthe permutation sample standard deviations</p></li>
<li><p>z_ii: p-value</p></li>
<li><p>skewness: For <code>localmoran_perm</code>, the output of e1071::skewness() for the permutation samples underlying the standard deviates</p></li>
<li><p>kurtosis: For <code>localmoran_perm</code>, the output of e1071::kurtosis() for the permutation samples underlying the standard deviates.</p></li>
</ul>
<p>Print the <code>lisa</code> sf df.</p>
<p>The quadrants (HH, LH, HL, LL) is automatically calculated for us.</p>
<p>Usually we use mean for the Moran-Scatterplot. However, if the data GDPPC is <strong>highly skewed</strong>, use <strong>median</strong> instead of mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(lisa,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">ii</th>
<th style="text-align: right;">eii</th>
<th style="text-align: right;">var_ii</th>
<th style="text-align: right;">z_ii</th>
<th style="text-align: right;">p_ii</th>
<th style="text-align: right;">p_ii_sim</th>
<th style="text-align: right;">p_folded_sim</th>
<th style="text-align: right;">skewness</th>
<th style="text-align: right;">kurtosis</th>
<th style="text-align: left;">mean</th>
<th style="text-align: left;">median</th>
<th style="text-align: left;">pysal</th>
<th style="text-align: left;">nb</th>
<th style="text-align: left;">wt</th>
<th style="text-align: left;">NAME_2</th>
<th style="text-align: right;">ID_3</th>
<th style="text-align: left;">NAME_3</th>
<th style="text-align: left;">ENGTYPE_3</th>
<th style="text-align: left;">County</th>
<th style="text-align: right;">GDPPC</th>
<th style="text-align: left;">geometry</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">-0.0014685</td>
<td style="text-align: right;">0.0017692</td>
<td style="text-align: right;">0.0004180</td>
<td style="text-align: right;">-0.1583623</td>
<td style="text-align: right;">0.8741713</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">-0.8122108</td>
<td style="text-align: right;">0.6518754</td>
<td style="text-align: left;">Low-High</td>
<td style="text-align: left;">High-High</td>
<td style="text-align: left;">Low-High</td>
<td style="text-align: left;">2, 3, 4, 57, 85</td>
<td style="text-align: left;">0.2, 0.2, 0.2, 0.2, 0.2</td>
<td style="text-align: left;">Changde</td>
<td style="text-align: right;">21098</td>
<td style="text-align: left;">Anxiang</td>
<td style="text-align: left;">County</td>
<td style="text-align: left;">Anxiang</td>
<td style="text-align: right;">23667</td>
<td style="text-align: left;">POLYGON ((112.0625 29.75523…</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.0258782</td>
<td style="text-align: right;">0.0064149</td>
<td style="text-align: right;">0.0105104</td>
<td style="text-align: right;">0.1898479</td>
<td style="text-align: right;">0.8494283</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">-1.0905447</td>
<td style="text-align: right;">1.8891775</td>
<td style="text-align: left;">Low-Low</td>
<td style="text-align: left;">High-High</td>
<td style="text-align: left;">Low-Low</td>
<td style="text-align: left;">1, 57, 58, 78, 85</td>
<td style="text-align: left;">0.2, 0.2, 0.2, 0.2, 0.2</td>
<td style="text-align: left;">Changde</td>
<td style="text-align: right;">21100</td>
<td style="text-align: left;">Hanshou</td>
<td style="text-align: left;">County</td>
<td style="text-align: left;">Hanshou</td>
<td style="text-align: right;">20981</td>
<td style="text-align: left;">POLYGON ((112.2288 29.11684…</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-0.0119876</td>
<td style="text-align: right;">-0.0374069</td>
<td style="text-align: right;">0.1020555</td>
<td style="text-align: right;">0.0795690</td>
<td style="text-align: right;">0.9365800</td>
<td style="text-align: right;">0.76</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.8239085</td>
<td style="text-align: right;">0.0460951</td>
<td style="text-align: left;">High-Low</td>
<td style="text-align: left;">High-High</td>
<td style="text-align: left;">High-Low</td>
<td style="text-align: left;">1, 4, 5, 85</td>
<td style="text-align: left;">0.25, 0.25, 0.25, 0.25</td>
<td style="text-align: left;">Changde</td>
<td style="text-align: right;">21101</td>
<td style="text-align: left;">Jinshi</td>
<td style="text-align: left;">County City</td>
<td style="text-align: left;">Jinshi</td>
<td style="text-align: right;">34592</td>
<td style="text-align: left;">POLYGON ((111.8927 29.6013,…</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="visualising-local-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="visualising-local-morans-i">2.4 Visualising local Moran’s I</h4>
<p>Use tmap core functions to build a choropleth, using the local moran’s I (ii) field</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb29-2"><a href="#cb29-2"></a></span>
<span id="cb29-3"><a href="#cb29-3"></a>map1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4"></a>  <span class="fu">tm_fill</span>(<span class="st">"ii"</span>) <span class="sc">+</span> </span>
<span id="cb29-5"><a href="#cb29-5"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>)) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"local Moran's I of GDPPC"</span>,</span>
<span id="cb29-8"><a href="#cb29-8"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb29-9"><a href="#cb29-9"></a></span>
<span id="cb29-10"><a href="#cb29-10"></a>map1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="visualising-the-p-value-of-local-morans-i" class="level4">
<h4 class="anchored" data-anchor-id="visualising-the-p-value-of-local-morans-i">2.5 Visualising the p-value of local Moran’s I</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb30-2"><a href="#cb30-2"></a></span>
<span id="cb30-3"><a href="#cb30-3"></a>map2<span class="ot">&lt;-</span><span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_ii_sim"</span>,</span>
<span id="cb30-5"><a href="#cb30-5"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb30-6"><a href="#cb30-6"></a>          <span class="at">palette=</span><span class="st">"-Blues"</span>,</span>
<span id="cb30-7"><a href="#cb30-7"></a>          <span class="at">title =</span> <span class="st">"local Moran's I p-values"</span>) <span class="sc">+</span> </span>
<span id="cb30-8"><a href="#cb30-8"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb30-9"><a href="#cb30-9"></a>   <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"p-value of local Moran's I"</span>,</span>
<span id="cb30-10"><a href="#cb30-10"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb30-11"><a href="#cb30-11"></a></span>
<span id="cb30-12"><a href="#cb30-12"></a>map2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Putting both maps side by side</p>
<div class="cell" data-fig.asp="0.68">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="fu">tmap_arrange</span>(map1, map2, <span class="at">asp=</span><span class="dv">1</span>, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="1344"></p>
</div>
</div>
</section>
<section id="visualising-lisa-map" class="level4">
<h4 class="anchored" data-anchor-id="visualising-lisa-map"><strong>2.6 Visualising LISA map</strong></h4>
<p>LISA map is a categorical map showing outliers and clusters. There are two types of outliers namely: High-Low and Low-High outliers. Likewise, there are two type of clusters namely: High-High and Low-Low cluaters. In fact, LISA map is an interpreted map by combining local Moran’s I of geographical areas and their respective p-values.</p>
<p>In lisa sf data.frame, we can find three fields contain the LISA categories. They are <strong><em>mean</em>, <em>median</em> and <em>pysal</em>.</strong> In general, classification in <strong><em>mean</em></strong> will be used as shown in the code chunk below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb32-2"><a href="#cb32-2"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="#cb32-3"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1"></a>lisa_sig <span class="ot">&lt;-</span> lisa  <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2"></a>  <span class="fu">filter</span>(p_ii <span class="sc">&lt;</span> <span class="fl">0.05</span>)  <span class="co"># lpot only sig region at 95% Conf.lvl</span></span>
<span id="cb33-3"><a href="#cb33-3"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb33-4"><a href="#cb33-4"></a></span>
<span id="cb33-5"><a href="#cb33-5"></a><span class="fu">tm_shape</span>(lisa_sig) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6"></a>  <span class="fu">tm_fill</span>(<span class="st">"mean"</span>) <span class="sc">+</span> </span>
<span id="cb33-7"><a href="#cb33-7"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell" data-fig.asp="0.68">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a>lisa_sig <span class="ot">&lt;-</span> lisa  <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2"></a>  <span class="fu">filter</span>(p_ii <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb34-3"><a href="#cb34-3"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb34-4"><a href="#cb34-4"></a><span class="fu">tm_shape</span>(lisa) <span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7"></a><span class="fu">tm_shape</span>(lisa_sig) <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8"></a>  <span class="fu">tm_fill</span>(<span class="st">"mean"</span>) <span class="sc">+</span> </span>
<span id="cb34-9"><a href="#cb34-9"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="1344"></p>
</div>
</div>
</section>
</section>
<section id="part-3-hot-spot-and-cold-spot-area-analysis-hcsa" class="level3">
<h3 class="anchored" data-anchor-id="part-3-hot-spot-and-cold-spot-area-analysis-hcsa">Part 3: Hot Spot and Cold Spot Area Analysis (HCSA)</h3>
<p>HCSA uses spatial weights to identify locations of statistically significant hot spots and cold spots in an spatially weighted attribute that are in proximity to one another based on a calculated distance. The analysis groups features when similar high (hot) or low (cold) values are found in a cluster. The polygon features usually represent administration boundaries or a custom grid structure.</p>
<section id="section-1" class="level4">
<h4 class="anchored" data-anchor-id="section-1"></h4>
</section>
<section id="computing-local-gi-statistics" class="level4">
<h4 class="anchored" data-anchor-id="computing-local-gi-statistics"><strong>3.1 Computing Local Gi* statistics</strong></h4>
<p>Using the inverse distance spatial weights matrix <code>wm_idw</code> derived in section 1.3.3, we can use the <code>local_gstar_perm()</code> of sfdep library to compute Gi* values of each region stored in HCSA, class: ‘sf’, tbl_df’, ‘tbl’, ‘df’.</p>
<p>It contains not just the Gi* values based on simulated data but also the p-values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1"></a>HCSA <span class="ot">&lt;-</span> wm_idw <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2"></a>  <span class="fu">mutate</span>(<span class="at">local_Gi =</span> <span class="fu">local_gstar_perm</span>(</span>
<span id="cb35-3"><a href="#cb35-3"></a>    GDPPC, nb, wt, <span class="at">nsim=</span><span class="dv">99</span>),   <span class="co"># these 3 var are found in wm_idw</span></span>
<span id="cb35-4"><a href="#cb35-4"></a>    <span class="at">.before=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb35-5"><a href="#cb35-5"></a>  <span class="fu">unnest</span>(local_Gi)</span>
<span id="cb35-6"><a href="#cb35-6"></a></span>
<span id="cb35-7"><a href="#cb35-7"></a>HCSA</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 88 features and 16 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812
Geodetic CRS:  WGS 84
# A tibble: 88 × 17
   gi_star   e_gi    var_gi p_value   p_sim p_folded_sim skewness kurtosis nb   
     &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;nb&gt; 
 1  0.0416 0.0114   6.41e-6  0.0493 9.61e-1         0.7      0.35    0.875 &lt;int&gt;
 2 -0.333  0.0106   3.84e-6 -0.0941 9.25e-1         1        0.5     0.661 &lt;int&gt;
 3  0.281  0.0126   7.51e-6 -0.151  8.80e-1         0.9      0.45    0.640 &lt;int&gt;
 4  0.411  0.0118   9.22e-6  0.264  7.92e-1         0.6      0.3     0.853 &lt;int&gt;
 5  0.387  0.0115   9.56e-6  0.339  7.34e-1         0.62     0.31    1.07  &lt;int&gt;
 6 -0.368  0.0118   5.91e-6 -0.583  5.60e-1         0.72     0.36    0.594 &lt;int&gt;
 7  3.56   0.0151   7.31e-6  2.61   9.01e-3         0.06     0.03    1.09  &lt;int&gt;
 8  2.52   0.0136   6.14e-6  1.49   1.35e-1         0.2      0.1     1.12  &lt;int&gt;
 9  4.56   0.0144   5.84e-6  3.53   4.17e-4         0.04     0.02    1.23  &lt;int&gt;
10  1.16   0.0104   3.70e-6  1.82   6.86e-2         0.12     0.06    0.416 &lt;int&gt;
# ℹ 78 more rows
# ℹ 8 more variables: wts &lt;list&gt;, NAME_2 &lt;chr&gt;, ID_3 &lt;int&gt;, NAME_3 &lt;chr&gt;,
#   ENGTYPE_3 &lt;chr&gt;, County &lt;chr&gt;, GDPPC &lt;dbl&gt;, geometry &lt;POLYGON [°]&gt;</code></pre>
</div>
</div>
</section>
<section id="visualising-local-gi-sig-and-not-sig" class="level4">
<h4 class="anchored" data-anchor-id="visualising-local-gi-sig-and-not-sig">3.2 Visualising Local Gi* (sig and not-sig)</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb37-2"><a href="#cb37-2"></a></span>
<span id="cb37-3"><a href="#cb37-3"></a>map1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4"></a>  <span class="fu">tm_fill</span>(<span class="st">"gi_star"</span>) <span class="sc">+</span> </span>
<span id="cb37-5"><a href="#cb37-5"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb37-6"><a href="#cb37-6"></a>  <span class="fu">tm_view</span>(<span class="at">set.zoom.limits =</span> <span class="fu">c</span>(<span class="dv">6</span>,<span class="dv">8</span>))<span class="sc">+</span></span>
<span id="cb37-7"><a href="#cb37-7"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Gi* of GDPPC"</span>,</span>
<span id="cb37-8"><a href="#cb37-8"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb37-9"><a href="#cb37-9"></a></span>
<span id="cb37-10"><a href="#cb37-10"></a>map1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="visualising-p-value-of-hcsa-gi" class="level4">
<h4 class="anchored" data-anchor-id="visualising-p-value-of-hcsa-gi">3.3 <strong>Visualising p-value of HCSA (Gi*)</strong></h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb38-2"><a href="#cb38-2"></a></span>
<span id="cb38-3"><a href="#cb38-3"></a>map2<span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4"></a>  <span class="fu">tm_fill</span>(<span class="st">"p_sim"</span>,</span>
<span id="cb38-5"><a href="#cb38-5"></a>          <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.05</span>, <span class="fl">0.1</span>, <span class="cn">Inf</span>),</span>
<span id="cb38-6"><a href="#cb38-6"></a>          <span class="at">palette=</span><span class="st">"-Blues"</span>,</span>
<span id="cb38-7"><a href="#cb38-7"></a>          <span class="at">title =</span> <span class="st">"local Gi* sim p-values"</span>) <span class="sc">+</span> </span>
<span id="cb38-8"><a href="#cb38-8"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"p-value of Gi*"</span>,</span>
<span id="cb38-10"><a href="#cb38-10"></a>            <span class="at">main.title.size =</span> <span class="fl">0.8</span>)</span>
<span id="cb38-11"><a href="#cb38-11"></a></span>
<span id="cb38-12"><a href="#cb38-12"></a>map2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Putting both maps side by side</p>
<div class="cell" data-fig.asp="0.68">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a><span class="fu">tmap_arrange</span>(map1, map2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="1344"></p>
</div>
</div>
</section>
<section id="section-2" class="level4">
<h4 class="anchored" data-anchor-id="section-2"></h4>
</section>
<section id="visualising-hot-spot-and-cold-spot-areas" class="level4">
<h4 class="anchored" data-anchor-id="visualising-hot-spot-and-cold-spot-areas">3.4 Visualising hot spot and cold spot areas</h4>
<p>To plot only the significant (i.e.&nbsp;p-values less than 0.05) hot spot and cold spot areas by using appropriate tmap functions as shown below</p>
<div class="cell" data-fig.asp="0.68">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1"></a>HCSA_sig <span class="ot">&lt;-</span> HCSA  <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2"></a>  <span class="fu">filter</span>(p_sim <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb40-3"><a href="#cb40-3"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>)</span>
<span id="cb40-4"><a href="#cb40-4"></a><span class="fu">tm_shape</span>(HCSA) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7"></a><span class="fu">tm_shape</span>(HCSA_sig) <span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8"></a>  <span class="fu">tm_fill</span>(<span class="st">"gi_star"</span>) <span class="sc">+</span> </span>
<span id="cb40-9"><a href="#cb40-9"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="1344"></p>
</div>
</div>
</section>
</section>
<section id="part-4-emerging-hotspots-analysis" class="level3">
<h3 class="anchored" data-anchor-id="part-4-emerging-hotspots-analysis">Part 4: Emerging hotspots analysis</h3>
<p>In this section, we will load in additional set of data. Requires time series data to perform emerging hot spots analysis. The Hunan_GDPPC.csv file contains 10 years worth of GDPPC for each region.</p>
<p>The GDPPC has to be in NUMERICAL field. The time field year can be in numerical /pct or date format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>GDPPC <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">'data/aspatial/Hunan_GDPPC.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="creating-a-time-series-cube" class="level4">
<h4 class="anchored" data-anchor-id="creating-a-time-series-cube">4.1. Creating a Time series cube</h4>
<p>Using spacetime() of sfdep. Creating OLAP cube on the fly.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1"></a>GDPPC_st <span class="ot">&lt;-</span> <span class="fu">spacetime</span>(GDPPC, hunan,</span>
<span id="cb42-2"><a href="#cb42-2"></a>                      <span class="at">.loc_col =</span> <span class="st">'County'</span>,  <span class="co">#location column</span></span>
<span id="cb42-3"><a href="#cb42-3"></a>                      <span class="at">.time_col =</span> <span class="st">'Year'</span>)    <span class="co"># time column</span></span>
<span id="cb42-4"><a href="#cb42-4"></a></span>
<span id="cb42-5"><a href="#cb42-5"></a><span class="fu">class</span>(GDPPC_st)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "spacetime"   "spec_tbl_df" "tbl_df"      "tbl"         "data.frame" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a><span class="fu">str</span>(GDPPC_st)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spacetim [1,496 × 3] (S3: spacetime/spec_tbl_df/tbl_df/tbl/data.frame)
 $ Year  : num [1:1496] 2005 2005 2005 2005 2005 ...
 $ County: chr [1:1496] "Longshan" "Changsha" "Wangcheng" "Ningxiang" ...
 $ GDPPC : num [1:1496] 3469 24612 14659 11687 13406 ...
 - attr(*, "spec")=
  .. cols(
  ..   Year = col_double(),
  ..   County = col_character(),
  ..   GDPPC = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; 
 - attr(*, "active")= chr "data"
 - attr(*, "data")= spc_tbl_ [1,496 × 3] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
  ..$ Year  : num [1:1496] 2005 2005 2005 2005 2005 ...
  ..$ County: chr [1:1496] "Longshan" "Changsha" "Wangcheng" "Ningxiang" ...
  ..$ GDPPC : num [1:1496] 3469 24612 14659 11687 13406 ...
  ..- attr(*, "spec")=
  .. .. cols(
  .. ..   Year = col_double(),
  .. ..   County = col_character(),
  .. ..   GDPPC = col_double()
  .. .. )
  ..- attr(*, "problems")=&lt;externalptr&gt; 
 - attr(*, "geometry")=Classes 'sf' and 'data.frame':   88 obs. of  8 variables:
  ..$ NAME_2    : chr [1:88] "Changde" "Changde" "Changde" "Changde" ...
  ..$ ID_3      : int [1:88] 21098 21100 21101 21102 21103 21104 21109 21110 21111 21112 ...
  ..$ NAME_3    : chr [1:88] "Anxiang" "Hanshou" "Jinshi" "Li" ...
  ..$ ENGTYPE_3 : chr [1:88] "County" "County" "County City" "County" ...
  ..$ Shape_Leng: num [1:88] 1.87 2.36 1.43 3.47 2.29 ...
  ..$ Shape_Area: num [1:88] 0.101 0.2 0.053 0.189 0.115 ...
  ..$ County    : chr [1:88] "Anxiang" "Hanshou" "Jinshi" "Li" ...
  ..$ geometry  :sfc_POLYGON of length 88; first list element: List of 1
  .. ..$ : num [1:427, 1:2] 112 112 112 112 112 ...
  .. ..- attr(*, "class")= chr [1:3] "XY" "POLYGON" "sfg"
  ..- attr(*, "sf_column")= chr "geometry"
  ..- attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA
  .. ..- attr(*, "names")= chr [1:7] "NAME_2" "ID_3" "NAME_3" "ENGTYPE_3" ...
 - attr(*, "loc_col")= chr "County"
 - attr(*, "locs")= chr [1:88] "Anxiang" "Hanshou" "Jinshi" "Li" ...
 - attr(*, "n_locs")= int 88
 - attr(*, "time_col")= chr "Year"
 - attr(*, "times")= num [1:17] 2005 2006 2007 2008 2009 ...
 - attr(*, "n_times")= int 17</code></pre>
</div>
</div>
<p>Note: GDPPC_st looks identical to GDPPC but they are not the same class type. To verify, use the code below</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a><span class="fu">is_spacetime_cube</span>(GDPPC_st)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="computing-gi" class="level4">
<h4 class="anchored" data-anchor-id="computing-gi">4.2 Computing Gi*</h4>
<section id="derive-the-spatial-weights-need-to-be-distance-matrix" class="level5">
<h5 class="anchored" data-anchor-id="derive-the-spatial-weights-need-to-be-distance-matrix">4.2.1 Derive the spatial weights (need to be distance matrix)</h5>
<p>The code chunk below will identify nb and derive a <u><em>space-time</em></u> inverse weights distance weights. The earlier derived were spatial weights matrix, this time round involves time dimension too.</p>
<p>Note that this dataset now has neighbors and weights for <strong>each time-slice</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a>GDPPC_nb <span class="ot">&lt;-</span> GDPPC_st <span class="sc">%&gt;%</span> </span>
<span id="cb48-2"><a href="#cb48-2"></a>  <span class="fu">activate</span>(<span class="st">'geometry'</span>) <span class="sc">%&gt;%</span> <span class="co"># space-time cube has 'geometry' and 'attributes' component, we have to activate the geometry component before able to derive neighbours</span></span>
<span id="cb48-3"><a href="#cb48-3"></a>  <span class="fu">mutate</span>(<span class="at">nb=</span> <span class="fu">include_self</span>(<span class="fu">st_contiguity</span>(geometry)),  <span class="co"># need to inlude self to get Gi*. otherwise its Gi.</span></span>
<span id="cb48-4"><a href="#cb48-4"></a>         <span class="at">wt =</span> <span class="fu">st_inverse_distance</span>(nb, geometry,</span>
<span id="cb48-5"><a href="#cb48-5"></a>                                  <span class="at">scale =</span><span class="dv">1</span>,</span>
<span id="cb48-6"><a href="#cb48-6"></a>                                  <span class="at">alpha =</span><span class="dv">1</span>),</span>
<span id="cb48-7"><a href="#cb48-7"></a>         <span class="at">.before =</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-8"><a href="#cb48-8"></a>  <span class="fu">set_nbs</span>(<span class="st">'nb'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb48-9"><a href="#cb48-9"></a>  <span class="fu">set_wts</span>(<span class="st">'wt'</span>)</span>
<span id="cb48-10"><a href="#cb48-10"></a></span>
<span id="cb48-11"><a href="#cb48-11"></a><span class="fu">class</span>(GDPPC_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "spacetime"  "tbl_df"     "tbl"        "data.frame"</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p><code>activate()</code> of dplyr package is used to activate the geometry context</p></li>
<li><p><code>mutate()</code> of dplyr package is used to create two new columns <em>nb</em> and <em>wt</em>.</p></li>
<li><p>Then we will activate the data context again and copy over the nb and wt columns to each time-slice using <code>set_nbs()</code> and <code>set_wts()</code></p>
<ul>
<li>row order is very important so do not rearrange the observations after using <code>set_nbs()</code> or <code>set_wts()</code>.</li>
</ul></li>
</ul>
</div>
</div>
<p>Explaining why need to activate geometry, show table later</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a><span class="fu">head</span>(GDPPC_nb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
   Year County  GDPPC nb        wt       
  &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;list&gt;    &lt;list&gt;   
1  2005 Anxiang  8184 &lt;int [6]&gt; &lt;dbl [6]&gt;
2  2005 Hanshou  6560 &lt;int [6]&gt; &lt;dbl [6]&gt;
3  2005 Jinshi   9956 &lt;int [5]&gt; &lt;dbl [5]&gt;
4  2005 Li       8394 &lt;int [5]&gt; &lt;dbl [5]&gt;
5  2005 Linli    8850 &lt;int [5]&gt; &lt;dbl [5]&gt;
6  2005 Shimen   9244 &lt;int [6]&gt; &lt;dbl [6]&gt;</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>GDPPC_st : space-time cube</p>
<p>GDPPC_nb: space-time weights matrixs</p>
</div>
</div>
</section>
<section id="computing-gi-1" class="level5">
<h5 class="anchored" data-anchor-id="computing-gi-1">4.2.2 Computing GI*</h5>
<p>We can use the time-space weights matrix <code>GDPPC_nb</code> to manually calculate the local Gi* for each location.</p>
<ul>
<li><p>group by <em>Year</em> and using <code>local_gstar_perm()</code> of sfdep package.</p></li>
<li><p>use <code>unnest()</code> to unnest <em>gi_star</em> column of the newly created <em>gi_stars</em> data.frame. THe output of this function is grouped and thus we cannot see it unless unnest().</p>
<p><code>gi_stars</code> df has 1496 rows instead of 88 because we have ten years worth of data</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a>gi_stars <span class="ot">&lt;-</span> GDPPC_nb <span class="sc">%&gt;%</span> </span>
<span id="cb52-2"><a href="#cb52-2"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span>   <span class="co"># look at a time slice, for all locations</span></span>
<span id="cb52-3"><a href="#cb52-3"></a>  <span class="fu">mutate</span>(<span class="at">gi_star =</span> <span class="fu">local_gstar_perm</span>(</span>
<span id="cb52-4"><a href="#cb52-4"></a>  GDPPC, nb, wt)) <span class="sc">%&gt;%</span> </span>
<span id="cb52-5"><a href="#cb52-5"></a>  tidyr<span class="sc">::</span><span class="fu">unnest</span>(gi_star)</span>
<span id="cb52-6"><a href="#cb52-6"></a></span>
<span id="cb52-7"><a href="#cb52-7"></a>gi_stars</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,496 × 13
# Groups:   Year [17]
    Year County    GDPPC nb        wt    gi_star   e_gi  var_gi  p_value   p_sim
   &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;list&gt;    &lt;lis&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
 1  2005 Anxiang    8184 &lt;int [6]&gt; &lt;dbl&gt;   0.398 0.0115 2.69e-6  0.382   7.02e-1
 2  2005 Hanshou    6560 &lt;int [6]&gt; &lt;dbl&gt;  -0.237 0.0109 2.64e-6  0.00199 9.98e-1
 3  2005 Jinshi     9956 &lt;int [5]&gt; &lt;dbl&gt;   1.05  0.0126 3.33e-6  0.507   6.12e-1
 4  2005 Li         8394 &lt;int [5]&gt; &lt;dbl&gt;   0.966 0.0117 3.24e-6  0.920   3.57e-1
 5  2005 Linli      8850 &lt;int [5]&gt; &lt;dbl&gt;   1.05  0.0120 3.23e-6  0.885   3.76e-1
 6  2005 Shimen     9244 &lt;int [6]&gt; &lt;dbl&gt;   0.210 0.0121 2.99e-6 -0.215   8.30e-1
 7  2005 Liuyang   13406 &lt;int [5]&gt; &lt;dbl&gt;   3.91  0.0142 2.52e-6  3.36    7.69e-4
 8  2005 Ningxiang 11687 &lt;int [8]&gt; &lt;dbl&gt;   1.61  0.0127 2.30e-6  0.895   3.71e-1
 9  2005 Wangcheng 14659 &lt;int [7]&gt; &lt;dbl&gt;   3.88  0.0140 2.49e-6  2.73    6.28e-3
10  2005 Anren      7423 &lt;int [9]&gt; &lt;dbl&gt;   1.67  0.0113 2.14e-6  1.87    6.21e-2
# ℹ 1,486 more rows
# ℹ 3 more variables: p_folded_sim &lt;dbl&gt;, skewness &lt;dbl&gt;, kurtosis &lt;dbl&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a><span class="fu">str</span>(gi_stars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>gropd_df [1,496 × 13] (S3: grouped_df/tbl_df/tbl/data.frame)
 $ Year        : num [1:1496] 2005 2005 2005 2005 2005 ...
 $ County      : chr [1:1496] "Anxiang" "Hanshou" "Jinshi" "Li" ...
 $ GDPPC       : num [1:1496] 8184 6560 9956 8394 8850 ...
 $ nb          :List of 1496
  ..$ : int [1:6] 1 2 3 4 57 85
  ..$ : int [1:6] 1 2 57 58 78 85
  ..$ : int [1:5] 1 3 4 5 85
  ..$ : int [1:5] 1 3 4 5 6
  ..$ : int [1:5] 3 4 5 6 85
  ..$ : int [1:6] 4 5 6 69 75 85
  ..$ : int [1:5] 7 67 71 74 84
  ..$ : int [1:8] 8 9 46 47 56 78 80 86
  ..$ : int [1:7] 8 9 66 68 78 84 86
  ..$ : int [1:9] 10 16 17 19 20 22 70 72 73
  ..$ : int [1:4] 11 14 17 72
  ..$ : int [1:6] 12 13 60 61 63 83
  ..$ : int [1:5] 12 13 15 60 83
  ..$ : int [1:4] 11 14 15 17
  ..$ : int [1:5] 13 14 15 17 83
  ..$ : int [1:6] 10 16 17 22 72 83
  ..$ : int [1:8] 10 11 14 15 16 17 72 83
  ..$ : int [1:6] 18 20 22 23 77 83
  ..$ : int [1:7] 10 19 20 21 73 74 86
  ..$ : int [1:8] 10 18 19 20 21 22 23 82
  ..$ : int [1:6] 19 20 21 35 82 86
  ..$ : int [1:6] 10 16 18 20 22 83
  ..$ : int [1:8] 18 20 23 38 41 77 79 82
  ..$ : int [1:6] 24 25 28 31 32 54
  ..$ : int [1:6] 24 25 28 31 33 81
  ..$ : int [1:5] 26 27 33 42 81
  ..$ : int [1:4] 26 27 29 42
  ..$ : int [1:6] 24 25 28 33 49 54
  ..$ : int [1:4] 27 29 37 42
  ..$ : int [1:2] 30 33
  ..$ : int [1:9] 24 25 31 32 36 39 40 56 81
  ..$ : int [1:9] 24 31 32 50 54 55 56 75 85
  ..$ : int [1:6] 25 26 28 30 33 81
  ..$ : int [1:4] 34 36 45 80
  ..$ : int [1:7] 21 35 41 47 80 82 86
  ..$ : int [1:7] 31 34 36 40 45 56 80
  ..$ : int [1:5] 29 37 42 43 44
  ..$ : int [1:5] 23 38 44 77 79
  ..$ : int [1:6] 31 39 40 42 43 81
  ..$ : int [1:7] 31 36 39 40 43 45 79
  ..$ : int [1:7] 23 35 41 45 79 80 82
  ..$ : int [1:8] 26 27 29 37 39 42 43 81
  ..$ : int [1:7] 37 39 40 42 43 44 79
  ..$ : int [1:5] 37 38 43 44 79
  ..$ : int [1:7] 34 36 40 41 45 79 80
  ..$ : int [1:4] 8 46 47 86
  ..$ : int [1:6] 8 35 46 47 80 86
  ..$ : int [1:6] 48 50 51 52 53 55
  ..$ : int [1:5] 28 49 51 52 54
  ..$ : int [1:6] 32 48 50 52 54 55
  ..$ : int [1:4] 48 49 51 52
  ..$ : int [1:6] 48 49 50 51 52 54
  ..$ : int [1:4] 48 53 55 75
  ..$ : int [1:7] 24 28 32 49 50 52 54
  ..$ : int [1:6] 32 48 50 53 55 75
  ..$ : int [1:8] 8 31 32 36 56 78 80 85
  ..$ : int [1:7] 1 2 57 58 64 76 85
  ..$ : int [1:6] 2 57 58 68 76 78
  ..$ : int [1:5] 59 60 61 87 88
  ..$ : int [1:5] 12 13 59 60 61
  ..$ : int [1:8] 12 59 60 61 62 63 77 87
  ..$ : int [1:4] 61 62 77 87
  ..$ : int [1:5] 12 61 63 77 83
  ..$ : int [1:3] 57 64 76
  ..$ : int [1:2] 65 76
  ..$ : int [1:6] 9 66 67 68 76 84
  ..$ : int [1:5] 7 66 67 76 84
  ..$ : int [1:6] 9 58 66 68 76 78
  ..$ : int [1:4] 6 69 75 85
  ..$ : int [1:4] 10 70 72 73
  ..$ : int [1:4] 7 71 73 74
  ..$ : int [1:6] 10 11 16 17 70 72
  ..$ : int [1:6] 10 19 70 71 73 74
  ..$ : int [1:7] 7 19 71 73 74 84 86
  ..$ : int [1:7] 6 32 53 55 69 75 85
  ..$ : int [1:8] 57 58 64 65 66 67 68 76
  ..$ : int [1:8] 18 23 38 61 62 63 77 83
  ..$ : int [1:8] 2 8 9 56 58 68 78 85
  ..$ : int [1:8] 23 38 40 41 43 44 45 79
  ..$ : int [1:9] 8 34 35 36 41 45 47 56 80
  ..$ : int [1:7] 25 26 31 33 39 42 81
  ..$ : int [1:6] 20 21 23 35 41 82
  ..$ : int [1:10] 12 13 15 16 17 18 22 63 77 83
  ..$ : int [1:7] 7 9 66 67 74 84 86
  ..$ : int [1:12] 1 2 3 5 6 32 56 57 69 75 ...
  ..$ : int [1:10] 8 9 19 21 35 46 47 74 84 86
  ..$ : int [1:5] 59 61 62 87 88
  ..$ : int [1:3] 59 87 88
  ..$ : int [1:6] 1 2 3 4 57 85
  ..$ : int [1:6] 1 2 57 58 78 85
  ..$ : int [1:5] 1 3 4 5 85
  ..$ : int [1:5] 1 3 4 5 6
  ..$ : int [1:5] 3 4 5 6 85
  ..$ : int [1:6] 4 5 6 69 75 85
  ..$ : int [1:5] 7 67 71 74 84
  ..$ : int [1:8] 8 9 46 47 56 78 80 86
  ..$ : int [1:7] 8 9 66 68 78 84 86
  ..$ : int [1:9] 10 16 17 19 20 22 70 72 73
  ..$ : int [1:4] 11 14 17 72
  .. [list output truncated]
  ..- attr(*, "class")= chr [1:2] "list" "nb"
 $ wt          :List of 1496
  ..$ : num [1:6] 0 0.0153 0.0352 0.0218 0.0284 ...
  ..$ : num [1:6] 0.0153 0 0.016 0.0191 0.0233 ...
  ..$ : num [1:5] 0.0352 0 0.0458 0.0412 0.0121
  ..$ : num [1:5] 0.0218 0.0458 0 0.0464 0.0159
  ..$ : num [1:5] 0.0412 0.0464 0 0.019 0.0135
  ..$ : num [1:6] 0.0159 0.019 0 0.0271 0.0114 ...
  ..$ : num [1:5] 0 0.0162 0.0154 0.0113 0.0184
  ..$ : num [1:8] 0 0.0193 0.0268 0.0215 0.0108 ...
  ..$ : num [1:7] 0.0193 0 0.0165 0.018 0.0147 ...
  ..$ : num [1:9] 0 0.0274 0.0139 0.0146 0.0216 ...
  ..$ : num [1:4] 0 0.0234 0.0236 0.0239
  ..$ : num [1:6] 0 0.0288 0.0271 0.0251 0.0293 ...
  ..$ : num [1:5] 0.0288 0 0.0449 0.0283 0.0175
  ..$ : num [1:4] 0.02339 0 0.00972 0.0204
  ..$ : num [1:5] 0.04488 0.00972 0 0.01052 0.01695
  ..$ : num [1:6] 0.0274 0 0.0273 0.0233 0.019 ...
  ..$ : num [1:8] 0.0139 0.0236 0.0204 0.0105 0.0273 ...
  ..$ : num [1:6] 0 0.0148 0.0188 0.018 0.018 ...
  ..$ : num [1:7] 0.0146 0 0.0253 0.0454 0.0225 ...
  ..$ : num [1:8] 0.0216 0.0148 0.0253 0 0.0194 ...
  ..$ : num [1:6] 0.0454 0.0194 0 0.0147 0.0227 ...
  ..$ : num [1:6] 0.0242 0.0233 0.0188 0.0255 0 ...
  ..$ : num [1:8] 0.018 0.0121 0 0.0142 0.0188 ...
  ..$ : num [1:6] 0 0.0244 0.0185 0.0228 0.012 ...
  ..$ : num [1:6] 0.0244 0 0.0172 0.019 0.0159 ...
  ..$ : num [1:5] 0 0.022 0.0187 0.0199 0.0213
  ..$ : num [1:4] 0.022 0 0.0253 0.0158
  ..$ : num [1:6] 0.0185 0.0172 0 0.0205 0.0343 ...
  ..$ : num [1:4] 0.0253 0 0.0166 0.0127
  ..$ : num [1:2] 0 0.0237
  ..$ : num [1:9] 0.0228 0.019 0 0.0119 0.0157 ...
  ..$ : num [1:9] 0.012 0.0119 0 0.0164 0.014 ...
  ..$ : num [1:6] 0.0159 0.0187 0.0205 0.0237 0 ...
  ..$ : num [1:4] 0 0.0311 0.039 0.03
  ..$ : num [1:7] 0.0147 0 0.022 0.0255 0.0218 ...
  ..$ : num [1:7] 0.0157 0.0311 0 0.015 0.0189 ...
  ..$ : num [1:5] 0.0166 0 0.0247 0.0149 0.014
  ..$ : num [1:5] 0.0142 0 0.0205 0.0228 0.0177
  ..$ : num [1:6] 0.0133 0 0.0237 0.0164 0.0266 ...
  ..$ : num [1:7] 0.0162 0.015 0.0237 0 0.0153 ...
  ..$ : num [1:7] 0.0188 0.022 0 0.0236 0.0188 ...
  ..$ : num [1:8] 0.0199 0.0158 0.0127 0.0247 0.0164 ...
  ..$ : num [1:7] 0.0149 0.0266 0.0153 0.0201 0 ...
  ..$ : num [1:5] 0.014 0.0205 0.0316 0 0.0166
  ..$ : num [1:7] 0.039 0.0189 0.0191 0.0236 0 ...
  ..$ : num [1:4] 0.0268 0 0.039 0.0267
  ..$ : num [1:6] 0.0215 0.0255 0.039 0 0.0192 ...
  ..$ : num [1:6] 0 0.0207 0.0344 0.0214 0.0165 ...
  ..$ : num [1:5] 0.0343 0 0.0231 0.0266 0.0208
  ..$ : num [1:6] 0.0164 0.0207 0 0.0269 0.0227 ...
  ..$ : num [1:4] 0.0344 0.0231 0 0.0306
  ..$ : num [1:6] 0.0214 0.0266 0.0269 0.0306 0 ...
  ..$ : num [1:4] 0.0165 0 0.0207 0.0122
  ..$ : num [1:7] 0.0273 0.0177 0.014 0.0208 0.0227 ...
  ..$ : num [1:6] 0.0114 0.016 0.0181 0.0207 0 ...
  ..$ : num [1:8] 0.0108 0.011 0.0131 0.0204 0 ...
  ..$ : num [1:7] 0.0284 0.016 0 0.0258 0.041 ...
  ..$ : num [1:6] 0.0191 0.0258 0 0.0309 0.0153 ...
  ..$ : num [1:5] 0 0.0169 0.0127 0.0162 0.0184
  ..$ : num [1:5] 0.0271 0.0283 0.0169 0 0.0219
  ..$ : num [1:8] 0.0251 0.0127 0.0219 0 0.024 ...
  ..$ : num [1:4] 0.024 0 0.0184 0.0225
  ..$ : num [1:5] 0.0293 0.0292 0 0.0152 0.0172
  ..$ : num [1:3] 0.041 0 0.0184
  ..$ : num [1:2] 0 0.0209
  ..$ : num [1:6] 0.0165 0 0.0183 0.0344 0.016 ...
  ..$ : num [1:5] 0.0162 0.0183 0 0.0121 0.0135
  ..$ : num [1:6] 0.018 0.0309 0.0344 0 0.0154 ...
  ..$ : num [1:4] 0.0271 0 0.0146 0.0156
  ..$ : num [1:4] 0.0235 0 0.018 0.0274
  ..$ : num [1:4] 0.0154 0 0.0158 0.0297
  ..$ : num [1:6] 0.0178 0.0239 0.019 0.0166 0.018 ...
  ..$ : num [1:6] 0.0162 0.0225 0.0274 0.0158 0 ...
  ..$ : num [1:7] 0.0113 0.0175 0.0297 0.0151 0 ...
  ..$ : num [1:7] 0.0114 0.0108 0.0122 0.0223 0.0146 ...
  ..$ : num [1:8] 0.0165 0.0153 0.0184 0.0209 0.016 ...
  ..$ : num [1:8] 0.018 0.0194 0.0228 0.0128 0.0184 ...
  ..$ : num [1:8] 0.0233 0.0261 0.0147 0.012 0.0164 ...
  ..$ : num [1:8] 0.013 0.0177 0.0197 0.0188 0.0155 ...
  ..$ : num [1:9] 0.0152 0.03 0.0218 0.0175 0.0163 ...
  ..$ : num [1:7] 0.029 0.0213 0.0122 0.0195 0.018 ...
  ..$ : num [1:6] 0.0171 0.0227 0.0215 0.0197 0.0168 ...
  ..$ : num [1:10] 0.0207 0.0175 0.017 0.015 0.0159 ...
  ..$ : num [1:7] 0.0184 0.0302 0.0197 0.0135 0.0134 ...
  ..$ : num [1:12] 0.0103 0.0159 0.0121 0.0135 0.0108 ...
  ..$ : num [1:10] 0.0134 0.0161 0.0146 0.0184 0.0142 ...
  ..$ : num [1:5] 0.0162 0.0209 0.0225 0 0.0233
  ..$ : num [1:3] 0.0184 0.0233 0
  ..$ : num [1:6] 0 0.0153 0.0352 0.0218 0.0284 ...
  ..$ : num [1:6] 0.0153 0 0.016 0.0191 0.0233 ...
  ..$ : num [1:5] 0.0352 0 0.0458 0.0412 0.0121
  ..$ : num [1:5] 0.0218 0.0458 0 0.0464 0.0159
  ..$ : num [1:5] 0.0412 0.0464 0 0.019 0.0135
  ..$ : num [1:6] 0.0159 0.019 0 0.0271 0.0114 ...
  ..$ : num [1:5] 0 0.0162 0.0154 0.0113 0.0184
  ..$ : num [1:8] 0 0.0193 0.0268 0.0215 0.0108 ...
  ..$ : num [1:7] 0.0193 0 0.0165 0.018 0.0147 ...
  ..$ : num [1:9] 0 0.0274 0.0139 0.0146 0.0216 ...
  ..$ : num [1:4] 0 0.0234 0.0236 0.0239
  .. [list output truncated]
 $ gi_star     : num [1:1496] 0.398 -0.237 1.053 0.966 1.048 ...
 $ e_gi        : num [1:1496] 0.0115 0.0109 0.0126 0.0117 0.012 ...
 $ var_gi      : num [1:1496] 2.69e-06 2.64e-06 3.33e-06 3.24e-06 3.23e-06 ...
 $ p_value     : num [1:1496] 0.3821 0.00199 0.50708 0.92031 0.88485 ...
 $ p_sim       : num [1:1496] 0.702 0.998 0.612 0.357 0.376 ...
 $ p_folded_sim: num [1:1496] 0.608 0.892 0.528 0.308 0.352 0.92 0.008 0.396 0.036 0.08 ...
 $ skewness    : num [1:1496] 0.304 0.446 0.264 0.154 0.176 0.46 0.004 0.198 0.018 0.04 ...
 $ kurtosis    : num [1:1496] 0.893 0.82 0.929 1.185 0.874 ...
 - attr(*, "groups")= tibble [17 × 2] (S3: tbl_df/tbl/data.frame)
  ..$ Year : num [1:17] 2005 2006 2007 2008 2009 ...
  ..$ .rows: list&lt;int&gt; [1:17] 
  .. ..$ : int [1:88] 1 2 3 4 5 6 7 8 9 10 ...
  .. ..$ : int [1:88] 89 90 91 92 93 94 95 96 97 98 ...
  .. ..$ : int [1:88] 177 178 179 180 181 182 183 184 185 186 ...
  .. ..$ : int [1:88] 265 266 267 268 269 270 271 272 273 274 ...
  .. ..$ : int [1:88] 353 354 355 356 357 358 359 360 361 362 ...
  .. ..$ : int [1:88] 441 442 443 444 445 446 447 448 449 450 ...
  .. ..$ : int [1:88] 529 530 531 532 533 534 535 536 537 538 ...
  .. ..$ : int [1:88] 617 618 619 620 621 622 623 624 625 626 ...
  .. ..$ : int [1:88] 705 706 707 708 709 710 711 712 713 714 ...
  .. ..$ : int [1:88] 793 794 795 796 797 798 799 800 801 802 ...
  .. ..$ : int [1:88] 881 882 883 884 885 886 887 888 889 890 ...
  .. ..$ : int [1:88] 969 970 971 972 973 974 975 976 977 978 ...
  .. ..$ : int [1:88] 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 ...
  .. ..$ : int [1:88] 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154 ...
  .. ..$ : int [1:88] 1233 1234 1235 1236 1237 1238 1239 1240 1241 1242 ...
  .. ..$ : int [1:88] 1321 1322 1323 1324 1325 1326 1327 1328 1329 1330 ...
  .. ..$ : int [1:88] 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 ...
  .. ..@ ptype: int(0) 
  ..- attr(*, ".drop")= logi TRUE</code></pre>
</div>
</div>
<p>Print the <code>gi_stars</code> df</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a><span class="co">#kable(head(gi_stars,5))</span></span>
<span id="cb56-2"><a href="#cb56-2"></a>gi_stars <span class="sc">%&gt;%</span> </span>
<span id="cb56-3"><a href="#cb56-3"></a>  <span class="fu">arrange</span>(County) <span class="sc">%&gt;%</span> </span>
<span id="cb56-4"><a href="#cb56-4"></a>  <span class="fu">head</span>(<span class="dv">5</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb56-5"><a href="#cb56-5"></a>  <span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 2%">
<col style="width: 3%">
<col style="width: 2%">
<col style="width: 13%">
<col style="width: 42%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Year</th>
<th style="text-align: left;">County</th>
<th style="text-align: right;">GDPPC</th>
<th style="text-align: left;">nb</th>
<th style="text-align: left;">wt</th>
<th style="text-align: right;">gi_star</th>
<th style="text-align: right;">e_gi</th>
<th style="text-align: right;">var_gi</th>
<th style="text-align: right;">p_value</th>
<th style="text-align: right;">p_sim</th>
<th style="text-align: right;">p_folded_sim</th>
<th style="text-align: right;">skewness</th>
<th style="text-align: right;">kurtosis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2005</td>
<td style="text-align: left;">Anhua</td>
<td style="text-align: right;">4411</td>
<td style="text-align: left;">8, 31, 32, 36, 56, 78, 80, 85</td>
<td style="text-align: left;">0.01076895, 0.01100041, 0.01312949, 0.02041572, 0.00000000, 0.01199886, 0.01269364, 0.01519702</td>
<td style="text-align: right;">-1.1495103</td>
<td style="text-align: right;">0.0104408</td>
<td style="text-align: right;">2.8e-06</td>
<td style="text-align: right;">-0.6061786</td>
<td style="text-align: right;">0.5443961</td>
<td style="text-align: right;">0.632</td>
<td style="text-align: right;">0.316</td>
<td style="text-align: right;">0.7466849</td>
</tr>
<tr class="even">
<td style="text-align: right;">2006</td>
<td style="text-align: left;">Anhua</td>
<td style="text-align: right;">5048</td>
<td style="text-align: left;">8, 31, 32, 36, 56, 78, 80, 85</td>
<td style="text-align: left;">0.01076895, 0.01100041, 0.01312949, 0.02041572, 0.00000000, 0.01199886, 0.01269364, 0.01519702</td>
<td style="text-align: right;">-1.2062412</td>
<td style="text-align: right;">0.0103340</td>
<td style="text-align: right;">2.4e-06</td>
<td style="text-align: right;">-0.6666373</td>
<td style="text-align: right;">0.5050038</td>
<td style="text-align: right;">0.532</td>
<td style="text-align: right;">0.266</td>
<td style="text-align: right;">0.6857186</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2007</td>
<td style="text-align: left;">Anhua</td>
<td style="text-align: right;">6130</td>
<td style="text-align: left;">8, 31, 32, 36, 56, 78, 80, 85</td>
<td style="text-align: left;">0.01076895, 0.01100041, 0.01312949, 0.02041572, 0.00000000, 0.01199886, 0.01269364, 0.01519702</td>
<td style="text-align: right;">-1.0623115</td>
<td style="text-align: right;">0.0104177</td>
<td style="text-align: right;">2.3e-06</td>
<td style="text-align: right;">-0.6082854</td>
<td style="text-align: right;">0.5429982</td>
<td style="text-align: right;">0.580</td>
<td style="text-align: right;">0.290</td>
<td style="text-align: right;">0.7884648</td>
</tr>
<tr class="even">
<td style="text-align: right;">2008</td>
<td style="text-align: left;">Anhua</td>
<td style="text-align: right;">7230</td>
<td style="text-align: left;">8, 31, 32, 36, 56, 78, 80, 85</td>
<td style="text-align: left;">0.01076895, 0.01100041, 0.01312949, 0.02041572, 0.00000000, 0.01199886, 0.01269364, 0.01519702</td>
<td style="text-align: right;">-0.9631087</td>
<td style="text-align: right;">0.0104526</td>
<td style="text-align: right;">3.0e-06</td>
<td style="text-align: right;">-0.5122872</td>
<td style="text-align: right;">0.6084500</td>
<td style="text-align: right;">0.696</td>
<td style="text-align: right;">0.348</td>
<td style="text-align: right;">0.6719202</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2009</td>
<td style="text-align: left;">Anhua</td>
<td style="text-align: right;">8528</td>
<td style="text-align: left;">8, 31, 32, 36, 56, 78, 80, 85</td>
<td style="text-align: left;">0.01076895, 0.01100041, 0.01312949, 0.02041572, 0.00000000, 0.01199886, 0.01269364, 0.01519702</td>
<td style="text-align: right;">-0.7063891</td>
<td style="text-align: right;">0.0105453</td>
<td style="text-align: right;">4.2e-06</td>
<td style="text-align: right;">-0.3396736</td>
<td style="text-align: right;">0.7341023</td>
<td style="text-align: right;">0.848</td>
<td style="text-align: right;">0.424</td>
<td style="text-align: right;">0.8584200</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="mann-kendall-test" class="level4">
<h4 class="anchored" data-anchor-id="mann-kendall-test">4.3 Mann-Kendall test</h4>
<p>With these yearly Gi* measures for each location, we can then evaluate each location for a trend using the Mann-Kendall test. The code chunk below uses Changsha county. Test location by location.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a>cbg <span class="ot">&lt;-</span> gi_stars <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="#cb57-2"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span>   <span class="co"># we have grouped it earlier by Year</span></span>
<span id="cb57-3"><a href="#cb57-3"></a>  <span class="fu">filter</span>(County <span class="sc">==</span> <span class="st">'Changsha'</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb57-4"><a href="#cb57-4"></a>  <span class="fu">select</span>(County, Year, gi_star)</span>
<span id="cb57-5"><a href="#cb57-5"></a></span>
<span id="cb57-6"><a href="#cb57-6"></a>cbg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 3
   County    Year gi_star
   &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;
 1 Changsha  2005    5.03
 2 Changsha  2006    5.17
 3 Changsha  2007    5.30
 4 Changsha  2008    5.60
 5 Changsha  2009    6.28
 6 Changsha  2010    5.94
 7 Changsha  2011    5.75
 8 Changsha  2012    5.69
 9 Changsha  2013    5.71
10 Changsha  2014    5.76
11 Changsha  2015    6.10
12 Changsha  2016    6.00
13 Changsha  2017    6.20
14 Changsha  2018    6.04
15 Changsha  2019    6.58
16 Changsha  2020    5.77
17 Changsha  2021    5.75</code></pre>
</div>
</div>
<p>Plotting using ggplot2() functions</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> cbg,</span>
<span id="cb59-2"><a href="#cb59-2"></a>       <span class="fu">aes</span>(<span class="at">x=</span> Year,</span>
<span id="cb59-3"><a href="#cb59-3"></a>           <span class="at">y =</span> gi_star)) <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5"></a>  <span class="fu">theme_light</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Use <code>ggploty()</code> from <code>plotly</code> library to make the chart interactive.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a><span class="fu">ggplotly</span>(<span class="fu">ggplot</span>(<span class="at">data =</span> cbg,</span>
<span id="cb60-2"><a href="#cb60-2"></a>       <span class="fu">aes</span>(<span class="at">x=</span> Year,</span>
<span id="cb60-3"><a href="#cb60-3"></a>           <span class="at">y =</span> gi_star)) <span class="sc">+</span></span>
<span id="cb60-4"><a href="#cb60-4"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb60-5"><a href="#cb60-5"></a>  <span class="fu">theme_light</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-9ff13a907ae150a3bad3" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-9ff13a907ae150a3bad3">{"x":{"data":[{"x":[2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021],"y":[5.0282995066289047,5.1692011079782345,5.2958892892912894,5.6039537096873993,6.2788862246004742,5.9357455762937326,5.7508709054298892,5.6942475830114576,5.7085054237054784,5.7608121561733521,6.097127241257188,6.0036547779673146,6.2028053540357906,6.0371816202738318,6.579432171885526,5.7669155664195504,5.7486534794156494],"text":["Year: 2005<br />gi_star: 5.028300","Year: 2006<br />gi_star: 5.169201","Year: 2007<br />gi_star: 5.295889","Year: 2008<br />gi_star: 5.603954","Year: 2009<br />gi_star: 6.278886","Year: 2010<br />gi_star: 5.935746","Year: 2011<br />gi_star: 5.750871","Year: 2012<br />gi_star: 5.694248","Year: 2013<br />gi_star: 5.708505","Year: 2014<br />gi_star: 5.760812","Year: 2015<br />gi_star: 6.097127","Year: 2016<br />gi_star: 6.003655","Year: 2017<br />gi_star: 6.202805","Year: 2018<br />gi_star: 6.037182","Year: 2019<br />gi_star: 6.579432","Year: 2020<br />gi_star: 5.766916","Year: 2021<br />gi_star: 5.748653"],"type":"scatter","mode":"lines","line":{"width":1.8897637795275593,"color":"rgba(0,0,0,1)","dash":"solid"},"hoveron":"points","showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.228310502283104,"r":7.3059360730593621,"b":40.182648401826491,"l":43.105022831050235},"plot_bgcolor":"rgba(255,255,255,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[2004.2,2021.8],"tickmode":"array","ticktext":["2005","2010","2015","2020"],"tickvals":[2005,2010,2015,2020],"categoryorder":"array","categoryarray":["2005","2010","2015","2020"],"nticks":null,"ticks":"outside","tickcolor":"rgba(179,179,179,1)","ticklen":3.6529680365296811,"tickwidth":0.33208800332088001,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(222,222,222,1)","gridwidth":0.33208800332088001,"zeroline":false,"anchor":"y","title":{"text":"Year","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[4.9507428733660737,6.656988805148357],"tickmode":"array","ticktext":["5.0","5.5","6.0","6.5"],"tickvals":[5,5.5,6,6.5],"categoryorder":"array","categoryarray":["5.0","5.5","6.0","6.5"],"nticks":null,"ticks":"outside","tickcolor":"rgba(179,179,179,1)","ticklen":3.6529680365296811,"tickwidth":0.33208800332088001,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(222,222,222,1)","gridwidth":0.33208800332088001,"zeroline":false,"anchor":"x","title":{"text":"gi_star","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":"transparent","line":{"color":"rgba(179,179,179,1)","width":0.66417600664176002,"linetype":"solid"},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"5fc05fe6469":{"x":{},"y":{},"type":"scatter"}},"cur_data":"5fc05fe6469","visdat":{"5fc05fe6469":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Performing the Mann-Kendall test.</p>
<p>The ‘sl’ column is the p_value. ‘tau’ column is the trend</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1"></a>cbg <span class="sc">%&gt;%</span></span>
<span id="cb61-2"><a href="#cb61-2"></a>  <span class="fu">summarise</span>(<span class="at">mk =</span> <span class="fu">list</span>(</span>
<span id="cb61-3"><a href="#cb61-3"></a>    <span class="fu">unclass</span>(</span>
<span id="cb61-4"><a href="#cb61-4"></a>      Kendall<span class="sc">::</span><span class="fu">MannKendall</span>(gi_star)))) <span class="sc">%&gt;%</span> </span>
<span id="cb61-5"><a href="#cb61-5"></a>  tidyr<span class="sc">::</span><span class="fu">unnest_wider</span>(mk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
    tau      sl     S     D  varS
  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 0.485 0.00742    66  136.  589.</code></pre>
</div>
</div>
<p>There is a slight upward but insignificant trend (&gt; 0.05)</p>
<section id="perform-mann-kendall-for-all-locations" class="level5">
<h5 class="anchored" data-anchor-id="perform-mann-kendall-for-all-locations">4.3.1 Perform Mann-Kendall for all locations</h5>
<p>To replicate this code for each location (to check for statistical sig for trend in all location), use the <code>group_by</code> function. The number of rows is back to 88.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1"></a>ehsa <span class="ot">&lt;-</span> gi_stars <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2"></a>  <span class="fu">group_by</span>(County) <span class="sc">%&gt;%</span></span>
<span id="cb63-3"><a href="#cb63-3"></a>  <span class="fu">summarise</span>(<span class="at">mk =</span> <span class="fu">list</span>(</span>
<span id="cb63-4"><a href="#cb63-4"></a>    <span class="fu">unclass</span>(</span>
<span id="cb63-5"><a href="#cb63-5"></a>      Kendall<span class="sc">::</span><span class="fu">MannKendall</span>(gi_star)))) <span class="sc">%&gt;%</span></span>
<span id="cb63-6"><a href="#cb63-6"></a>  tidyr<span class="sc">::</span><span class="fu">unnest_wider</span>(mk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Print the output in an interactive table</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a><span class="fu">datatable</span>(ehsa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div class="datatables html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-abdf314ed31241557a52" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-abdf314ed31241557a52">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88"],["Anhua","Anren","Anxiang","Baojing","Chaling","Changning","Changsha","Chengbu","Chenxi","Cili","Dao","Dongan","Dongkou","Fenghuang","Guidong","Guiyang","Guzhang","Hanshou","Hengdong","Hengnan","Hengshan","Hengyang","Hongjiang","Huarong","Huayuan","Huitong","Jiahe","Jianghua","Jiangyong","Jingzhou","Jinshi","Jishou","Lanshan","Leiyang","Lengshuijiang","Li","Lianyuan","Liling","Linli","Linwu","Linxiang","Liuyang","Longhui","Longshan","Luxi","Mayang","Miluo","Nan","Ningxiang","Ningyuan","Pingjiang","Qidong","Qiyang","Rucheng","Sangzhi","Shaodong","Shaoshan","Shaoyang","Shimen","Shuangfeng","Shuangpai","Suining","Taojiang","Taoyuan","Tongdao","Wangcheng","Wugang","Xiangtan","Xiangxiang","Xiangyin","Xinhua","Xinhuang","Xinning","Xinshao","Xintian","Xupu","Yanling","Yizhang","Yongshun","Yongxing","You","Yuanjiang","Yuanling","Yueyang","Zhijiang","Zhongfang","Zhuzhou","Zixing"],[0.1911764889955521,-0.2941176891326904,0,-0.6911765336990356,-0.08823530375957489,-0.7500000596046448,0.4852941632270813,-0.8235294818878174,-0.1176470741629601,0.1029411852359772,-0.04411765187978745,-0.8235294818878174,-0.7647059559822083,-0.7058824300765991,0.1323529630899429,-0.2500000298023224,-0.617647111415863,0.1029411852359772,0.3823529779911041,-0.5882353782653809,0.4852941632270813,0.1029411852359772,-0.2647059261798859,0.04411765187978745,-0.7941177487373352,-0.3088235557079315,-0.4705882966518402,0.3970588743686676,0.1764706075191498,-0.2647059261798859,0.01470588427037001,-0.7500000596046448,-0.5588235855102539,-0.5882353782653809,-0.7647059559822083,0.02941176854074001,0.1911764889955521,0.7058824300765991,0.08823530375957489,-0.4558824002742767,0.4117647409439087,0.7794118523597717,0.1176470741629601,0,-0.3970588743686676,0,0.5147059559822083,-0.01470588427037001,0.4264706373214722,-0.5294118523597717,0.64705890417099,-0.2058823704719543,-0.4264706373214722,-0.1764706075191498,-0.1911764889955521,0.64705890417099,0.7941177487373352,0.2352941483259201,0.1617647260427475,0.8676471710205078,-0.279411792755127,-0.7205883264541626,0.2941176891326904,0.2058823704719543,-0.7500000596046448,0.4264706373214722,-0.8088236451148987,0.8676471710205078,0.8676471710205078,0.5588235855102539,-0.2500000298023224,0.1470588445663452,-0.7647059559822083,-0.2500000298023224,-0.1029411852359772,-0.05882353708148003,0.2058823704719543,-0.2352941483259201,-0.2205882668495178,0.07352942228317261,0.1470588445663452,0.4558824002742767,-0.2058823704719543,0.4264706373214722,0.05882353708148003,0.04411765187978745,0.7647059559822083,-0.07352942228317261],[0.3030965328216553,0.1081613376736641,1,0.0001276678376598284,0.6504631042480469,3.176133031956851e-05,0.007416963577270508,4.822107712243451e-06,0.5366482734680176,0.5923012495040894,0.8368197083473206,4.822107712243451e-06,2.207080615335144e-05,9.104339551413432e-05,0.4837558269500732,0.1740335673093796,0.0006285444251261652,0.5923012495040894,0.03565645217895508,0.00113705126568675,0.007416963577270508,0.5923012495040894,0.1493751555681229,0.8368196487426758,1.045168482960435e-05,0.09123902767896652,0.009455357678234577,0.02902042865753174,0.3434194326400757,0.1493751555681229,0.9671423435211182,3.176133031956851e-05,0.002005293034017086,0.00113705126568675,2.207080615335144e-05,0.9016494750976562,0.3030965328216553,9.107589721679688e-05,0.6504631042480469,0.01197940856218338,0.023476243019104,1.52587890625e-05,0.5366482734680176,1,0.0290203932672739,1,0.004479050636291504,0.9671423435211182,0.0188755989074707,0.003448142670094967,0.0003386735916137695,0.266051709651947,0.01887554675340652,0.3434194326400757,0.3030965328216553,0.0003386735916137695,1.049041748046875e-05,0.2016122341156006,0.3870139122009277,1.430511474609375e-06,0.1274769306182861,6.450741784647107e-05,0.1081613302230835,0.2660517692565918,3.176133031956851e-05,0.0188755989074707,7.122434453776805e-06,1.430511474609375e-06,1.430511474609375e-06,0.002005338668823242,0.1740335673093796,0.4338268041610718,2.207080615335144e-05,0.1740335673093796,0.5923012495040894,0.773080050945282,0.2660517692565918,0.2016122937202454,0.2322487235069275,0.7108359336853027,0.4338268041610718,0.01197946071624756,0.266051709651947,0.0188755989074707,0.7730801105499268,0.8368196487426758,2.205371856689453e-05,0.7108359336853027],[26,-40,0,-94,-12,-102,66,-112,-16,14,-6,-112,-104,-96,18,-34,-84,14,52,-80,66,14,-36,6,-108,-42,-64,54,24,-36,2,-102,-76,-80,-104,4,26,96,12,-62,56,106,16,0,-54,0,70,-2,58,-72,88,-28,-58,-24,-26,88,108,32,22,118,-38,-98,40,28,-102,58,-110,118,118,76,-34,20,-104,-34,-14,-8,28,-32,-30,10,20,62,-28,58,8,6,104,-10],[135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109,135.9999847412109],[589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812,589.3333129882812]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>County<\/th>\n      <th>tau<\/th>\n      <th>sl<\/th>\n      <th>S<\/th>\n      <th>D<\/th>\n      <th>varS<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[2,3,4,5,6]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="section-3" class="level5">
<h5 class="anchored" data-anchor-id="section-3"></h5>
</section>
<section id="sort-by-top-5-emerging-and-significant-hotspots" class="level5">
<h5 class="anchored" data-anchor-id="sort-by-top-5-emerging-and-significant-hotspots">4.3.2 Sort by top 5 emerging and significant hotspots</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1"></a>emerging <span class="ot">&lt;-</span> ehsa <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="#cb65-2"></a>  <span class="fu">arrange</span>(sl, <span class="fu">abs</span>(tau)) <span class="sc">%&gt;%</span> </span>
<span id="cb65-3"><a href="#cb65-3"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>)</span>
<span id="cb65-4"><a href="#cb65-4"></a></span>
<span id="cb65-5"><a href="#cb65-5"></a><span class="fu">kable</span>(emerging)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">tau</th>
<th style="text-align: right;">sl</th>
<th style="text-align: right;">S</th>
<th style="text-align: right;">D</th>
<th style="text-align: right;">varS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Shuangfeng</td>
<td style="text-align: right;">0.8676472</td>
<td style="text-align: right;">1.4e-06</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">589.3333</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xiangtan</td>
<td style="text-align: right;">0.8676472</td>
<td style="text-align: right;">1.4e-06</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">589.3333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Xiangxiang</td>
<td style="text-align: right;">0.8676472</td>
<td style="text-align: right;">1.4e-06</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">589.3333</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chengbu</td>
<td style="text-align: right;">-0.8235295</td>
<td style="text-align: right;">4.8e-06</td>
<td style="text-align: right;">-112</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">589.3333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dongan</td>
<td style="text-align: right;">-0.8235295</td>
<td style="text-align: right;">4.8e-06</td>
<td style="text-align: right;">-112</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">589.3333</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="emerging-hot-spot-analysis" class="level4">
<h4 class="anchored" data-anchor-id="emerging-hot-spot-analysis">4.4 Emerging hot spot analysis</h4>
<section id="calculating-ehsa-using-spacetime-cube" class="level5">
<h5 class="anchored" data-anchor-id="calculating-ehsa-using-spacetime-cube">4.4.1 <strong>Calculating ehsa using spacetime cube</strong></h5>
<p>We will perform EHSA analysis by using <a href="https://sfdep.josiahparry.com/reference/emerging_hotspot_analysis.html"><code>emerging_hotspot_analysis()</code></a> of sfdep package. It requires</p>
<ol type="1">
<li>a spacetime object, x (i.e.&nbsp;GDPPC_st)</li>
<li>the quoted name of the variable of interest, .var (i.e.&nbsp;GDPPC)</li>
<li>k argument is used to specify the number of time lags which is set to 1 by default.</li>
<li>nsim map numbers of simulation to be performed.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a>ehsa <span class="ot">&lt;-</span> <span class="fu">emerging_hotspot_analysis</span>(</span>
<span id="cb66-2"><a href="#cb66-2"></a>  <span class="at">x =</span> GDPPC_st, <span class="co"># timeseries data stored in this spacetime cube</span></span>
<span id="cb66-3"><a href="#cb66-3"></a>  <span class="at">.var=</span><span class="st">'GDPPC'</span>,  <span class="co"># spatial element found inside this column</span></span>
<span id="cb66-4"><a href="#cb66-4"></a>  <span class="at">k=</span><span class="dv">1</span>,   <span class="co"># timelag</span></span>
<span id="cb66-5"><a href="#cb66-5"></a>  <span class="at">nsim=</span><span class="dv">99</span></span>
<span id="cb66-6"><a href="#cb66-6"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Print the output</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1"></a><span class="fu">datatable</span>(ehsa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">

<div class="datatables html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-182c25701bfa220289d2" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-182c25701bfa220289d2">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88"],["Anxiang","Hanshou","Jinshi","Li","Linli","Shimen","Liuyang","Ningxiang","Wangcheng","Anren","Guidong","Jiahe","Linwu","Rucheng","Yizhang","Yongxing","Zixing","Changning","Hengdong","Hengnan","Hengshan","Leiyang","Qidong","Chenxi","Zhongfang","Huitong","Jingzhou","Mayang","Tongdao","Xinhuang","Xupu","Yuanling","Zhijiang","Lengshuijiang","Shuangfeng","Xinhua","Chengbu","Dongan","Dongkou","Longhui","Shaodong","Suining","Wugang","Xinning","Xinshao","Shaoshan","Xiangxiang","Baojing","Fenghuang","Guzhang","Huayuan","Jishou","Longshan","Luxi","Yongshun","Anhua","Nan","Yuanjiang","Jianghua","Lanshan","Ningyuan","Shuangpai","Xintian","Huarong","Linxiang","Miluo","Pingjiang","Xiangyin","Cili","Chaling","Liling","Yanling","You","Zhuzhou","Sangzhi","Yueyang","Qiyang","Taojiang","Shaoyang","Lianyuan","Hongjiang","Hengyang","Guiyang","Changsha","Taoyuan","Xiangtan","Dao","Jiangyong"],[0.2205882668495178,0.1470588445663452,0.4411765336990356,-0.8235294818878174,0.1176470741629601,-0.4705882966518402,0.8676471710205078,-0.5588235855102539,-0.1617647260427475,0.4558824002742767,0.279411792755127,-0.4852941632270813,-0.3382353186607361,-0.8088236451148987,0.1176470741629601,-0.04411765187978745,-0.6323530077934265,0.4117647409439087,0.4264706373214722,-0.3529412150382996,0.5294118523597717,0.367647111415863,-0.1617647260427475,0.7205883264541626,-0.8235294818878174,-0.2058823704719543,-0.1176470741629601,0.3970588743686676,0.323529452085495,-0.1617647260427475,0.1617647260427475,-0.7647059559822083,-0.2500000298023224,-0.01470588427037001,-0.4705882966518402,0.1323529630899429,0.3529412150382996,0.89705890417099,0.3970588743686676,-0.1911764889955521,0.6911765336990356,0.8382353782653809,0.01470588427037001,-0.2500000298023224,-0.367647111415863,0.08823530375957489,0.8382353782653809,0.2352941483259201,0.7647059559822083,-0.1176470741629601,0.8823530673980713,0.1470588445663452,-0.279411792755127,-0.07352942228317261,0.1323529630899429,0.4264706373214722,0.9117648005485535,0.3088235557079315,0.3970588743686676,0.7941177487373352,0.02941176854074001,-0.3970588743686676,0.5147059559822083,0.4558824002742767,-0.5588235855102539,0.7500000596046448,-0.5000000596046448,0.8235294818878174,0.8235294818878174,0.8235294818878174,-0.3088235557079315,0.01470588427037001,-0.5147059559822083,-0.1323529630899429,0.1470588445663452,-0.05882353708148003,0.279411792755127,-0.02941176854074001,-0.2941176891326904,0.2941176891326904,0.3823529779911041,0.5441176891326904,-0.05882353708148003,0.7794118523597717,0.1323529630899429,0.02941176854074001,0.8235294818878174,0.07352942228317261],[0.2322487831115723,0.4338268041610718,0.0150836706161499,4.822107712243451e-06,0.5366482734680176,0.009455357678234577,1.430511474609375e-06,0.002005293034017086,0.3870139718055725,0.01197946071624756,0.1274769306182861,0.007416919805109501,0.06378662586212158,7.122434453776805e-06,0.5366482734680176,0.8368197083473206,0.0004628665337804705,0.023476243019104,0.0188755989074707,0.05286114662885666,0.003448128700256348,0.04354560375213623,0.3870139718055725,6.449222564697266e-05,4.822107712243451e-06,0.266051709651947,0.5366482734680176,0.02902042865753174,0.07651364803314209,0.3870139718055725,0.3870139122009277,2.207080615335144e-05,0.1740335673093796,0.9671423435211182,0.009455357678234577,0.4837558269500732,0.05286109447479248,5.960464477539062e-07,0.02902042865753174,0.3030965328216553,0.0001276731491088867,3.218650817871094e-06,0.9671423435211182,0.1740335673093796,0.04354557767510414,0.6504631042480469,3.218650817871094e-06,0.2016122341156006,2.205371856689453e-05,0.5366482734680176,9.5367431640625e-07,0.4338268041610718,0.1274769306182861,0.7108359336853027,0.4837558269500732,0.0188755989074707,3.576278686523438e-07,0.09123897552490234,0.02902042865753174,1.049041748046875e-05,0.9016494750976562,0.0290203932672739,0.004479050636291504,0.01197946071624756,0.002005293034017086,3.170967102050781e-05,0.00578179769217968,4.76837158203125e-06,4.76837158203125e-06,4.76837158203125e-06,0.09123902767896652,0.9671423435211182,0.004479054361581802,0.4837557673454285,0.4338268041610718,0.773080050945282,0.1274769306182861,0.9016494750976562,0.1081613376736641,0.1081613302230835,0.03565645217895508,0.002637863159179688,0.773080050945282,1.52587890625e-05,0.4837558269500732,0.9016494750976562,4.76837158203125e-06,0.7108359336853027],["sporadic coldspot","sporadic hotspot","oscilating hotspot","sporadic coldspot","oscilating hotspot","oscilating coldspot","sporadic hotspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic hotspot","sporadic hotspot","sporadic coldspot","sporadic coldspot","oscilating hotspot","oscilating coldspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","oscilating hotspot","sporadic coldspot","sporadic coldspot","no pattern detected","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic hotspot","sporadic coldspot","sporadic coldspot","oscilating coldspot","sporadic hotspot","sporadic hotspot","oscilating hotspot","sporadic hotspot","sporadic hotspot","sporadic hotspot","oscilating hotspot","sporadic hotspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic hotspot","oscilating hotspot","sporadic hotspot","sporadic coldspot","consecutive hotspot","sporadic coldspot","sporadic coldspot","no pattern detected","sporadic coldspot","sporadic coldspot","sporadic hotspot","sporadic coldspot","oscilating coldspot","oscilating hotspot","sporadic coldspot","sporadic coldspot","sporadic hotspot","sporadic coldspot","sporadic coldspot","sporadic hotspot","sporadic coldspot","sporadic hotspot","sporadic hotspot","sporadic hotspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic coldspot","sporadic hotspot","sporadic hotspot","sporadic coldspot","sporadic hotspot","sporadic hotspot","oscilating hotspot","sporadic coldspot","oscilating hotspot","sporadic coldspot","sporadic coldspot","sporadic hotspot","oscilating hotspot"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>location<\/th>\n      <th>tau<\/th>\n      <th>p_value<\/th>\n      <th>classification<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[2,3]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="visualising-the-distribution-of-ehsa-classes" class="level5">
<h5 class="anchored" data-anchor-id="visualising-the-distribution-of-ehsa-classes">4.4.2 <strong>Visualising the distribution of EHSA classes</strong></h5>
<p>plot barchart to check distribution of EHSA classes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a><span class="fu">ggplotly</span>(<span class="fu">ggplot</span>(<span class="at">data =</span> ehsa,</span>
<span id="cb68-2"><a href="#cb68-2"></a>       <span class="fu">aes</span>(<span class="at">x =</span> classification)) <span class="sc">+</span></span>
<span id="cb68-3"><a href="#cb68-3"></a>  <span class="fu">geom_bar</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item-overflow-hidden html-fill-item" id="htmlwidget-ffb0a1dc5031e673a973" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-ffb0a1dc5031e673a973">{"x":{"data":[{"orientation":"v","width":[0.89999999999999991,0.90000000000000013,0.90000000000000036,0.90000000000000036,0.90000000000000036,0.90000000000000036],"base":[0,0,0,0,0,0],"x":[1,2,3,4,5,6],"y":[1,2,4,11,46,24],"text":["count:  1<br />classification: consecutive hotspot","count:  2<br />classification: no pattern detected","count:  4<br />classification: oscilating coldspot","count: 11<br />classification: oscilating hotspot","count: 46<br />classification: sporadic coldspot","count: 24<br />classification: sporadic hotspot"],"type":"bar","textposition":"none","marker":{"autocolorscale":false,"color":"rgba(89,89,89,1)","line":{"width":1.8897637795275593,"color":"transparent"}},"showlegend":false,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":26.228310502283104,"r":7.3059360730593621,"b":40.182648401826491,"l":37.260273972602747},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.40000000000000002,6.5999999999999996],"tickmode":"array","ticktext":["consecutive hotspot","no pattern detected","oscilating coldspot","oscilating hotspot","sporadic coldspot","sporadic hotspot"],"tickvals":[1,2,3,3.9999999999999996,5,6],"categoryorder":"array","categoryarray":["consecutive hotspot","no pattern detected","oscilating coldspot","oscilating hotspot","sporadic coldspot","sporadic hotspot"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"classification","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[-2.3000000000000003,48.299999999999997],"tickmode":"array","ticktext":["0","10","20","30","40"],"tickvals":[0,10,20,29.999999999999996,40],"categoryorder":"array","categoryarray":["0","10","20","30","40"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"count","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"5fc042a62052":{"x":{},"type":"bar"}},"cur_data":"5fc042a62052","visdat":{"5fc042a62052":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Sporadic cold spots has the highest numbers of county</p>
</section>
<section id="visualising-ehsa-on-map" class="level5">
<h5 class="anchored" data-anchor-id="visualising-ehsa-on-map">4.4.3 Visualising EHSA on map</h5>
<p>Because ehsa df does not have geometry data, we can join both hunan geospatial df with ehsa to make a sf object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1"></a>hunan_ehsa <span class="ot">&lt;-</span><span class="fu">left_join</span>(hunan, ehsa,</span>
<span id="cb69-2"><a href="#cb69-2"></a>            <span class="at">by=</span><span class="fu">c</span>(<span class="st">'County'</span> <span class="ot">=</span> <span class="st">'location'</span>))</span>
<span id="cb69-3"><a href="#cb69-3"></a></span>
<span id="cb69-4"><a href="#cb69-4"></a><span class="fu">class</span>(hunan_ehsa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "sf"         "data.frame"</code></pre>
</div>
</div>
<p>Use tmap functions to plot choropleth map We can use the p-value inside to plot only the significant emerging hot/cold spots, by filtering rows with p_values &lt; 0.05</p>
<p>Take note: no pattern (yellow) doesnt mean not-sig (grey)</p>
<div class="cell" data-fig.asp="0.68">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1"></a>ehsa_sig <span class="ot">&lt;-</span>  hunan_ehsa <span class="sc">%&gt;%</span> </span>
<span id="cb71-2"><a href="#cb71-2"></a>  <span class="fu">filter</span>(p_value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb71-3"><a href="#cb71-3"></a></span>
<span id="cb71-4"><a href="#cb71-4"></a><span class="fu">tmap_mode</span>(<span class="st">'plot'</span>)</span>
<span id="cb71-5"><a href="#cb71-5"></a><span class="co">#base</span></span>
<span id="cb71-6"><a href="#cb71-6"></a><span class="fu">tm_shape</span>(hunan_ehsa) <span class="sc">+</span></span>
<span id="cb71-7"><a href="#cb71-7"></a>  <span class="fu">tm_polygons</span>() <span class="sc">+</span></span>
<span id="cb71-8"><a href="#cb71-8"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb71-9"><a href="#cb71-9"></a>  <span class="co">#sif</span></span>
<span id="cb71-10"><a href="#cb71-10"></a>  <span class="fu">tm_shape</span>(ehsa_sig) <span class="sc">+</span></span>
<span id="cb71-11"><a href="#cb71-11"></a>  <span class="fu">tm_fill</span>(<span class="st">'classification'</span>) <span class="sc">+</span></span>
<span id="cb71-12"><a href="#cb71-12"></a>  <span class="fu">tm_borders</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="In-class_Ex2_files/figure-html/unnamed-chunk-49-1.png" class="img-fluid" width="1344"></p>
</div>
</div>
<div class="cell" data-fig.asp="0.68">

</div>


</section>
</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>