{
  "hash": "e3d73a7b6d788fa013542b5292685391",
  "result": {
    "markdown": "---\ntitle: \"Hands-on Exercise 4.1: Geopraphically Weighted Regression\"\nauthor: \"NeoYX\"\ndate: '4 Dec 2023'\ndate-modified: \"2023-12-05\"\neditor: visual\nexecute: \n  freeze: auto\n  warning: false\n  #echo: false\n  #message: false\nformat: \n  html:\n    code-fold: false\n    code-overflow: scroll\n    code-summary: \"Show the code\"\n    code-line-numbers: true\n---\n\n\n## **13.1 Overview**\n\n**Geographically weighted regression (GWR)** is a spatial statistical technique that takes **non-stationary variables** into consideration (e.g., climate; demographic factors; physical environment characteristics) and models the local relationships between these independent variables and an outcome of interest (also known as dependent variable).\n\nIn this hands-on exercise, we will learn how to build [hedonic pricing](https://www.investopedia.com/terms/h/hedonicpricing.asp) models by using GWR methods.\n\nHedonic Pricing is a model that identifies price factors according to the premise that price is determined by internal and external factors affecting it. For housing, internal could mean size, height, appearance, solar panels while external could mean crime rate, distance to school or downtown area.\n\nThe **dependent** variable is the **resale** prices of condominium in 2015. The **independent** variables are divided into either **structural** and **locational**.\n\n## **13.2 The Data**\n\nTwo data sets will be used in this model building exercise, they are:\n\n-   URA Master Plan subzone boundary in shapefile format (i.e. *MP14_SUBZONE_WEB_PL*)\n\n-   Condo_resale_2015 in csv format (i.e. *Condo_resale_2015.csv*)\n\nUsing MP14 instead of MP19 because of condo_resale_2015.\n\n## **13.3 Getting Started**\n\nBefore we get started, it is important for us to install the necessary R packages into R and launch these R packages into R environment.\n\nThe R packages needed for this exercise are as follows:\n\n-   R package for building OLS and performing diagnostics tests\n\n    -   [**olsrr**](https://olsrr.rsquaredacademy.com/)\n    -   It enhances the capabilities of the basic linear modeling functionality and provides a comprehensive set of regression diagnostics, model comparisons, and other statistics, including normality of residuals, homoscedasticity, and influential observations.\n\n-   R package for calibrating geographical weighted family of models\n\n    -   [**GWmodel**](https://cran.r-project.org/web/packages/GWmodel/)\n\n-   R package for multivariate data visualisation and analysis\n\n    -   [**corrplot**](https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html)\n    -   In this exercise, we will be using this package to visualise the correlation matrix\n\n-   [ggpubr](https://rpkgs.datanovia.com/ggpubr/) for some easy-to-use functions for creating and customizing 'ggplot2'- based publication ready plots.\n\n-   Spatial data handling\n\n    -   **sf** for importing, integrating, processing and transforming geospatial data.\n\n-   Attribute data handling\n\n    -   **tidyverse**, especially **readr**, **ggplot2** and **dplyr**\n\n-   Choropleth mapping\n\n    -   **tmap** for creating thematic maps\n\n-   Create publication ready summary tables in R\n\n    -   [gtsummary](https://www.danieldsjoberg.com/gtsummary/) package and its [tbl_regression()](https://www.danieldsjoberg.com/gtsummary/reference/tbl_regression.html) function\n\nThe code chunks below installs and launches these R packages into R environment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(olsrr, corrplot, ggpubr, sf, spdep, GWmodel, tmap, tidyverse, gtsummary, DT, knitr)\n```\n:::\n\n\n## **13.4 A short note about GWmodel**\n\n[**GWmodel**](https://www.jstatsoft.org/article/view/v063i17) package provides a collection of **localised** spatial statistical methods, namely: GW summary statistics, GW principal components analysis, GW discriminant analysis and various forms of GW regression; some of which are provided in basic and robust (outlier resistant) forms. Commonly, outputs or parameters of the GWmodel are mapped to provide a useful exploratory tool, which can often precede (and direct) a more traditional or sophisticated statistical analysis.\n\n## **13.5 Geospatial Data Wrangling**\n\n### **13.5.1 Importing geospatial data**\n\nThe geospatial data used in this hands-on exercise is called MP14_SUBZONE_WEB_PL. It is in ESRI shapefile format. The shapefile consists of URA Master Plan 2014's planning subzone boundaries. Polygon features are used to represent these geographic boundaries. The GIS data is in svy21 projected coordinates systems.\n\nThe code chunk below is used to import *MP_SUBZONE_WEB_PL* shapefile by using `st_read()` of **sf** packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz = st_read(dsn = \"data/geospatial\", layer = \"MP14_SUBZONE_WEB_PL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReading layer `MP14_SUBZONE_WEB_PL' from data source \n  `C:\\yixin-neo\\ISSS624_AGA\\Hands-on_Ex4\\data\\geospatial' using driver `ESRI Shapefile'\nSimple feature collection with 323 features and 15 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\n```\n:::\n\n```{.r .cell-code}\nst_crs(mpsz)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCoordinate Reference System:\n  User input: SVY21 \n  wkt:\nPROJCRS[\"SVY21\",\n    BASEGEOGCRS[\"SVY21[WGS84]\",\n        DATUM[\"World Geodetic System 1984\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ID[\"EPSG\",6326]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"Degree\",0.0174532925199433]]],\n    CONVERSION[\"unnamed\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"Degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"Degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1,\n                ID[\"EPSG\",9001]]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1,\n                ID[\"EPSG\",9001]]]]\n```\n:::\n:::\n\n\nThe report above shows that the R object used to contain the imported MP14_SUBZONE_WEB_PL shapefile is called *mpsz* and it is a simple feature object. The geometry type is *multipolygon*. it is also important to note that mpsz simple feature object **does not** have EPSG information.\n\n### **13.5.2 Updating CRS information**\n\nThe code chunk below updates the newly imported *mpsz* with the correct ESPG code (i.e. 3414)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_svy21 <- mpsz %>%  \n  st_transform(crs=3414)\n```\n:::\n\n\nThe EPSG: is indicated as *3414* now.\n\nNext, we will reveal the extent (rectangular boundary) of *mpsz_svy21* by using `st_bbox()` of sf package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_bbox(mpsz_svy21)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     xmin      ymin      xmax      ymax \n 2667.538 15748.721 56396.440 50256.334 \n```\n:::\n:::\n\n\n## **13.6 Aspatial Data Wrangling**\n\n### **13.6.1 Importing the aspatial data**\n\nThe *condo_resale_2015* is in csv file format. The codes chunk below uses `read_csv()` function of **readr** package to import *condo_resale_2015* into R as a tibble data frame called *condo_resale*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale <- read_csv('data/aspatial/Condo_resale_2015.csv')\n```\n:::\n\n\nLet us examine if the data file has been imported correctly.\n\nThe codes chunks below uses `glimpse()` to display the data structure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(condo_resale)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 1,436\nColumns: 23\n$ LATITUDE             <dbl> 1.287145, 1.328698, 1.313727, 1.308563, 1.321437,…\n$ LONGITUDE            <dbl> 103.7802, 103.8123, 103.7971, 103.8247, 103.9505,…\n$ POSTCODE             <dbl> 118635, 288420, 267833, 258380, 467169, 466472, 3…\n$ SELLING_PRICE        <dbl> 3000000, 3880000, 3325000, 4250000, 1400000, 1320…\n$ AREA_SQM             <dbl> 309, 290, 248, 127, 145, 139, 218, 141, 165, 168,…\n$ AGE                  <dbl> 30, 32, 33, 7, 28, 22, 24, 24, 27, 31, 17, 22, 6,…\n$ PROX_CBD             <dbl> 7.941259, 6.609797, 6.898000, 4.038861, 11.783402…\n$ PROX_CHILDCARE       <dbl> 0.16597932, 0.28027246, 0.42922669, 0.39473543, 0…\n$ PROX_ELDERLYCARE     <dbl> 2.5198118, 1.9333338, 0.5021395, 1.9910316, 1.121…\n$ PROX_URA_GROWTH_AREA <dbl> 6.618741, 7.505109, 6.463887, 4.906512, 6.410632,…\n$ PROX_HAWKER_MARKET   <dbl> 1.76542207, 0.54507614, 0.37789301, 1.68259969, 0…\n$ PROX_KINDERGARTEN    <dbl> 0.05835552, 0.61592412, 0.14120309, 0.38200076, 0…\n$ PROX_MRT             <dbl> 0.5607188, 0.6584461, 0.3053433, 0.6910183, 0.528…\n$ PROX_PARK            <dbl> 1.1710446, 0.1992269, 0.2779886, 0.9832843, 0.116…\n$ PROX_PRIMARY_SCH     <dbl> 1.6340256, 0.9747834, 1.4715016, 1.4546324, 0.709…\n$ PROX_TOP_PRIMARY_SCH <dbl> 3.3273195, 0.9747834, 1.4715016, 2.3006394, 0.709…\n$ PROX_SHOPPING_MALL   <dbl> 2.2102717, 2.9374279, 1.2256850, 0.3525671, 1.307…\n$ PROX_SUPERMARKET     <dbl> 0.9103958, 0.5900617, 0.4135583, 0.4162219, 0.581…\n$ PROX_BUS_STOP        <dbl> 0.10336166, 0.28673408, 0.28504777, 0.29872340, 0…\n$ NO_Of_UNITS          <dbl> 18, 20, 27, 30, 30, 31, 32, 32, 32, 32, 34, 34, 3…\n$ FAMILY_FRIENDLY      <dbl> 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0…\n$ FREEHOLD             <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1…\n$ LEASEHOLD_99YR       <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n```\n:::\n:::\n\n\nCheck the first five longitude (X) and latitude (Y) columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale %>% select(1,2) %>% head()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 2\n  LATITUDE LONGITUDE\n     <dbl>     <dbl>\n1     1.29      104.\n2     1.33      104.\n3     1.31      104.\n4     1.31      104.\n5     1.32      104.\n6     1.31      104.\n```\n:::\n:::\n\n\nNext, `summary()` of base R is used to display the summary statistics of *cond_resale* tibble data frame.\n\nLongitude and latitude are in decimal deg (\\< 360deg) , WSG84 (or crs 4326).\n\nSome postal codes are only 5 digits, the number 0 in front could have been truncated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(condo_resale)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    LATITUDE       LONGITUDE        POSTCODE      SELLING_PRICE     \n Min.   :1.240   Min.   :103.7   Min.   : 18965   Min.   :  540000  \n 1st Qu.:1.309   1st Qu.:103.8   1st Qu.:259849   1st Qu.: 1100000  \n Median :1.328   Median :103.8   Median :469298   Median : 1383222  \n Mean   :1.334   Mean   :103.8   Mean   :440439   Mean   : 1751211  \n 3rd Qu.:1.357   3rd Qu.:103.9   3rd Qu.:589486   3rd Qu.: 1950000  \n Max.   :1.454   Max.   :104.0   Max.   :828833   Max.   :18000000  \n    AREA_SQM          AGE           PROX_CBD       PROX_CHILDCARE    \n Min.   : 34.0   Min.   : 0.00   Min.   : 0.3869   Min.   :0.004927  \n 1st Qu.:103.0   1st Qu.: 5.00   1st Qu.: 5.5574   1st Qu.:0.174481  \n Median :121.0   Median :11.00   Median : 9.3567   Median :0.258135  \n Mean   :136.5   Mean   :12.14   Mean   : 9.3254   Mean   :0.326313  \n 3rd Qu.:156.0   3rd Qu.:18.00   3rd Qu.:12.6661   3rd Qu.:0.368293  \n Max.   :619.0   Max.   :37.00   Max.   :19.1804   Max.   :3.465726  \n PROX_ELDERLYCARE  PROX_URA_GROWTH_AREA PROX_HAWKER_MARKET PROX_KINDERGARTEN \n Min.   :0.05451   Min.   :0.2145       Min.   :0.05182    Min.   :0.004927  \n 1st Qu.:0.61254   1st Qu.:3.1643       1st Qu.:0.55245    1st Qu.:0.276345  \n Median :0.94179   Median :4.6186       Median :0.90842    Median :0.413385  \n Mean   :1.05351   Mean   :4.5981       Mean   :1.27987    Mean   :0.458903  \n 3rd Qu.:1.35122   3rd Qu.:5.7550       3rd Qu.:1.68578    3rd Qu.:0.578474  \n Max.   :3.94916   Max.   :9.1554       Max.   :5.37435    Max.   :2.229045  \n    PROX_MRT         PROX_PARK       PROX_PRIMARY_SCH  PROX_TOP_PRIMARY_SCH\n Min.   :0.05278   Min.   :0.02906   Min.   :0.07711   Min.   :0.07711     \n 1st Qu.:0.34646   1st Qu.:0.26211   1st Qu.:0.44024   1st Qu.:1.34451     \n Median :0.57430   Median :0.39926   Median :0.63505   Median :1.88213     \n Mean   :0.67316   Mean   :0.49802   Mean   :0.75471   Mean   :2.27347     \n 3rd Qu.:0.84844   3rd Qu.:0.65592   3rd Qu.:0.95104   3rd Qu.:2.90954     \n Max.   :3.48037   Max.   :2.16105   Max.   :3.92899   Max.   :6.74819     \n PROX_SHOPPING_MALL PROX_SUPERMARKET PROX_BUS_STOP       NO_Of_UNITS    \n Min.   :0.0000     Min.   :0.0000   Min.   :0.001595   Min.   :  18.0  \n 1st Qu.:0.5258     1st Qu.:0.3695   1st Qu.:0.098356   1st Qu.: 188.8  \n Median :0.9357     Median :0.5687   Median :0.151710   Median : 360.0  \n Mean   :1.0455     Mean   :0.6141   Mean   :0.193974   Mean   : 409.2  \n 3rd Qu.:1.3994     3rd Qu.:0.7862   3rd Qu.:0.220466   3rd Qu.: 590.0  \n Max.   :3.4774     Max.   :2.2441   Max.   :2.476639   Max.   :1703.0  \n FAMILY_FRIENDLY     FREEHOLD      LEASEHOLD_99YR  \n Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  \n 1st Qu.:0.0000   1st Qu.:0.0000   1st Qu.:0.0000  \n Median :0.0000   Median :0.0000   Median :0.0000  \n Mean   :0.4868   Mean   :0.4227   Mean   :0.4882  \n 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  \n Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  \n```\n:::\n:::\n\n\n### **13.6.2 Converting aspatial data frame into a sf object**\n\nCurrently, the *condo_resale* tibble data frame is aspatial. We will convert it to a **sf** object. The code chunk below converts condo_resale data frame into a simple feature **POINT** data frame by using `st_as_sf()` of **sf** packages.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf <- st_as_sf(condo_resale,\n                            coords = c('LONGITUDE',\n                                       'LATITUDE'),\n                            crs = 4326) %>% \n  st_transform(crs= 3414)\n```\n:::\n\n\nNotice that `st_transform()` of **sf** package is used to convert the coordinates from wgs84 (i.e. crs:4326) to svy21 (i.e. crs=3414).\n\nNext, `head()` is used to list the content of *condo_resale.sf* object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(condo_resale.sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSimple feature collection with 6 features and 21 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 22085.12 ymin: 29951.54 xmax: 41042.56 ymax: 34546.2\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 6 × 22\n  POSTCODE SELLING_PRICE AREA_SQM   AGE PROX_CBD PROX_CHILDCARE PROX_ELDERLYCARE\n     <dbl>         <dbl>    <dbl> <dbl>    <dbl>          <dbl>            <dbl>\n1   118635       3000000      309    30     7.94          0.166            2.52 \n2   288420       3880000      290    32     6.61          0.280            1.93 \n3   267833       3325000      248    33     6.90          0.429            0.502\n4   258380       4250000      127     7     4.04          0.395            1.99 \n5   467169       1400000      145    28    11.8           0.119            1.12 \n6   466472       1320000      139    22    10.3           0.125            0.789\n# ℹ 15 more variables: PROX_URA_GROWTH_AREA <dbl>, PROX_HAWKER_MARKET <dbl>,\n#   PROX_KINDERGARTEN <dbl>, PROX_MRT <dbl>, PROX_PARK <dbl>,\n#   PROX_PRIMARY_SCH <dbl>, PROX_TOP_PRIMARY_SCH <dbl>,\n#   PROX_SHOPPING_MALL <dbl>, PROX_SUPERMARKET <dbl>, PROX_BUS_STOP <dbl>,\n#   NO_Of_UNITS <dbl>, FAMILY_FRIENDLY <dbl>, FREEHOLD <dbl>,\n#   LEASEHOLD_99YR <dbl>, geometry <POINT [m]>\n```\n:::\n:::\n\n\nNotice that the output is in point feature data frame.\n\n## **13.7 Exploratory Data Analysis (EDA)**\n\nIn the section, wewill learn how to use statistical graphics functions of **ggplot2** package to perform EDA.\n\n### **13.7.1 EDA using statistical graphics**\n\nWe can plot the distribution of *SELLING_PRICE* by using appropriate Exploratory Data Analysis (EDA) as shown in the code chunk below.\n\n\n::: {.cell fig.asp='0.68'}\n\n```{.r .cell-code}\nggplot(data=condo_resale.sf, aes(x=`SELLING_PRICE`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex4_1_files/figure-html/unnamed-chunk-11-1.png){width=1344}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\nThe figure above reveals a **right skewed** distribution. This means that **more** condominium units were transacted at relative **lower** prices.\n\nStatistically, the skewed distribution can be normalised by using **log** transformation. The code chunk below is used to derive a new variable called *LOG_SELLING_PRICE* by using a log transformation on the variable *SELLING_PRICE*. It is performed using `mutate()` of **dplyr** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo_resale.sf <- condo_resale.sf %>% \n  mutate(`LOG_SELLING_PRICE` = log(SELLING_PRICE))\n```\n:::\n\n\nNow, we can plot the *LOG_SELLING_PRICE* using the code chunk below.\n\n\n::: {.cell fig.asp='0.68'}\n\n```{.r .cell-code}\nggplot(data=condo_resale.sf, aes(x=`LOG_SELLING_PRICE`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\") \n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex4_1_files/figure-html/unnamed-chunk-14-1.png){width=1344}\n:::\n:::\n\n\nCheck for normality of the LOG_SELLING_PRICE. Although it is still not normally-distributed, it is less skewed after the transformation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnortest::ad.test(condo_resale.sf$`LOG_SELLING_PRICE`)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tAnderson-Darling normality test\n\ndata:  condo_resale.sf$LOG_SELLING_PRICE\nA = 19.973, p-value < 2.2e-16\n```\n:::\n:::\n\n\n### **13.7.2 Multiple Histogram Plots distribution of variables**\n\nIn this section, we will learn how to draw a small multiple histograms (also known as trellis plot) by using `ggarrange()` of [**ggpubr**](https://cran.r-project.org/web/packages/ggpubr/) package.\n\nThe code chunk below is used to create 12 histograms. Then, `ggarrange()` is used to organised these histogram into a 3 columns by 4 rows small multiple plot.\n\n\n::: {.cell fig.asp='0.68'}\n\n```{.r .cell-code}\nAREA_SQM <- ggplot(data=condo_resale.sf, aes(x= `AREA_SQM`)) + \n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nAGE <- ggplot(data=condo_resale.sf, aes(x= `AGE`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_CBD <- ggplot(data=condo_resale.sf, aes(x= `PROX_CBD`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_CHILDCARE <- ggplot(data=condo_resale.sf, aes(x= `PROX_CHILDCARE`)) + \n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_ELDERLYCARE <- ggplot(data=condo_resale.sf, aes(x= `PROX_ELDERLYCARE`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_URA_GROWTH_AREA <- ggplot(data=condo_resale.sf, \n                               aes(x= `PROX_URA_GROWTH_AREA`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_HAWKER_MARKET <- ggplot(data=condo_resale.sf, aes(x= `PROX_HAWKER_MARKET`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_KINDERGARTEN <- ggplot(data=condo_resale.sf, aes(x= `PROX_KINDERGARTEN`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_MRT <- ggplot(data=condo_resale.sf, aes(x= `PROX_MRT`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_PARK <- ggplot(data=condo_resale.sf, aes(x= `PROX_PARK`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_PRIMARY_SCH <- ggplot(data=condo_resale.sf, aes(x= `PROX_PRIMARY_SCH`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nPROX_TOP_PRIMARY_SCH <- ggplot(data=condo_resale.sf, \n                               aes(x= `PROX_TOP_PRIMARY_SCH`)) +\n  geom_histogram(bins=20, color=\"black\", fill=\"light blue\")\n\nggarrange(AREA_SQM, AGE, PROX_CBD, PROX_CHILDCARE, PROX_ELDERLYCARE, \n          PROX_URA_GROWTH_AREA, PROX_HAWKER_MARKET, PROX_KINDERGARTEN, PROX_MRT,\n          PROX_PARK, PROX_PRIMARY_SCH, PROX_TOP_PRIMARY_SCH,  \n          ncol = 3, nrow = 4)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex4_1_files/figure-html/unnamed-chunk-16-1.png){width=1344}\n:::\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n### **13.7.3 Drawing Statistical Point Map**\n\nLastly, we want to reveal the geospatial distribution condominium resale prices in Singapore. The map will be prepared by using **tmap** package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_mode('plot')\n#tmap_mode('view')\n#tmap_options(check.and.fix = TRUE)\n \ntm_shape(mpsz_svy21)+\n  tm_polygons(alpha=0.5) +\ntm_shape(condo_resale.sf) +  \n  tm_dots(col = \"SELLING_PRICE\",\n          alpha = 0.6,\n          style=\"quantile\") +\n  tm_view(set.zoom.limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex4_1_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nNotice that [`tm_dots()`](https://www.rdocumentation.org/packages/tmap/versions/2.2/topics/tm_symbols) is used instead of `tm_bubbles()`.\n\nIf in tmap_mode('view') mode,\n\n`set.zoom.limits` argument of `tm_view()` sets the minimum and maximum zoom level to 11 and 14 respectively.\n\n## **13.8 Hedonic Pricing Modelling in R**\n\nIn this section, we will learn how to building hedonic pricing models for condominium resale units using [`lm()`](https://www.rdocumentation.org/packages/stats/versions/3.5.2/topics/lm) of R base.\n\nBy calibration, we meant estimating local parameters that vary spatially for each location in the study area, considering nearby observations with higher weights and more distant observations with lower weights. This allows the relationship between variables to vary spatially, capturing local variations in the relationships.\n\nThe significance of the variables can be assessed locally, telling us where (at which location) specific predictors have a more significant impact on our dependent variable.\n\nModel Evaluation:: The calibration process in GWR involves fitting the model to the data at each location, and the quality of the fit can be assessed through various diagnostics (e.g., residuals, local R-squared values).\n\nWhen calibrating a Geographically Weighted Regression model, the emphasis is on capturing spatial heterogeneity in the relationships between variables and understanding how these relationships change across the study area. This is different from traditional models that assume a globally constant relationship. (Hands-on3 and In-class3)\n\n### **13.8.1 Simple Linear Regression Method**\n\nFirst, we will build a simple linear regression model by using *SELLING_PRICE* as the dependent variable and *AREA_SQM* as the independent variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.slr <- lm(formula=SELLING_PRICE ~ AREA_SQM, \n                data = condo_resale.sf)\nclass(condo.slr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"lm\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nattributes(condo.slr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$names\n [1] \"coefficients\"  \"residuals\"     \"effects\"       \"rank\"         \n [5] \"fitted.values\" \"assign\"        \"qr\"            \"df.residual\"  \n [9] \"xlevels\"       \"call\"          \"terms\"         \"model\"        \n\n$class\n[1] \"lm\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmethods(class=class(condo.slr))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] add1               alias              anova              case.names        \n [5] coerce             confint            cooks.distance     deviance          \n [9] dfbeta             dfbetas            drop1              dummy.coef        \n[13] effects            extractAIC         family             formula           \n[17] fortify            hatvalues          influence          initialize        \n[21] kappa              labels             logLik             model.frame       \n[25] model.matrix       nobs               ols_regress        ols_test_normality\n[29] plot               predict            print              proj              \n[33] qqnorm             qr                 residuals          rstandard         \n[37] rstudent           show               simulate           slotsFromS3       \n[41] summary            variable.names     vcov              \nsee '?methods' for accessing help and source code\n```\n:::\n:::\n\n\n`lm()` returns an object of class \"lm\" or for multiple responses of class c(\"mlm\", \"lm\").\n\nThe functions `summary()` and `anova()` can be used to obtain and print a summary and analysis of variance table of the results. The generic accessor functions coefficients, effects, fitted.values and residuals extract various useful features of the value returned by `lm`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(condo.slr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-3695815  -391764   -87517   258900 13503875 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -258121.1    63517.2  -4.064 5.09e-05 ***\nAREA_SQM      14719.0      428.1  34.381  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 942700 on 1434 degrees of freedom\nMultiple R-squared:  0.4518,\tAdjusted R-squared:  0.4515 \nF-statistic:  1182 on 1 and 1434 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe output report reveals that the SELLING_PRICE can be explained by using the formula:\n\n\\*y = -258121.1 + 14719x1\\*\n\nThe R-squared of 0.4518 reveals that the independent variable is able to explain about 45% of the variation in the dependent variable, resale prices.\n\nSince p-value is much smaller than 0.0001, we will reject the null hypothesis that mean is a good estimator of SELLING_PRICE. This will allow us to infer that simple linear regression model above is a good estimator of *SELLING_PRICE*.\n\nThe **Coefficients:** section of the report reveals that the p-values of both the estimates of the Intercept and ARA_SQM are smaller than 0.001. In view of this, the null hypothesis of the B0 and B1 are equal to 0 will be rejected. As a results, we will be able to infer that the B0 and B1 are good parameter estimates.\n\nTo visualise the best fit curve on a scatterplot, we can incorporate `lm()` as a method function in ggplot's geometry as shown in the code chunk below.\n\n\n::: {.cell fig.asp='0.68'}\n\n```{.r .cell-code}\nplotly::ggplotly(ggplot(data= condo_resale.sf,\n      aes(x = `AREA_SQM`,\n          y= `SELLING_PRICE`)) +\n  geom_point() +\n  geom_smooth(method = lm))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div class=\"plotly html-widget html-fill-item-overflow-hidden html-fill-item\" id=\"htmlwidget-79e708d2ca6f45824007\" style=\"width:100%;height:442px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-79e708d2ca6f45824007\">{\"x\":{\"data\":[{\"x\":[309,290,248,127,145,139,218,141,165,168,112,89,302,97,164,216,177,152,148,368,116,129,136,133,115,258,199,121,123,123,152,134,322,96,111,278,191,207,129,65,122,117,117,227,115,179,156,198,171,109,149,58,60,211,109,131,197,235,112,89,167,80,284,241,81,137,157,111,376,264,98,116,244,97,103,300,92,120,147,74,91,204,188,334,325,322,162,118,97,78,105,164,118,129,188,112,164,81,109,101,112,145,92,98,291,192,120,148,422,228,47,351,307,190,165,203,236,94,162,117,90,49,47,186,209,124,143,188,203,226,113,118,218,116,94,202,212,164,116,105,105,175,115,136,171,97,135,56,323,119,96,113,113,157,135,109,619,152,124,112,151,93,241,87,131,106,134,173,204,204,200,122,171,281,264,281,272,361,167,155,156,34,35,89,126,158,127,188,188,189,108,106,108,111,47,149,174,136,87,120,99,206,124,115,106,164,115,95,122,74,84,259,120,170,170,170,105,105,88,114,210,97,144,106,115,113,170,204,114,137,115,123,124,153,266,120,102,37,84,119,134,113,86,103,236,303,176,102,122,185,135,246,266,163,82,86,139,161,311,111,116,137,151,154,195,156,139,138,204,116,179,384,192,123,153,74,154,121,157,84,122,97,86,119,117,195,179,126,122,145,101,122,129,170,150,124,88,129,316,39,142,87,240,240,240,354,322,146,88,121,117,88,280,98,112,53,353,120,91,137,142,96,182,144,363,152,126,90,126,176,200,200,144,349,169,211,185,341,137,123,123,119,181,138,138,207,135,113,96,71,123,96,143,100,125,193,188,106,106,91,108,108,131,134,215,218,129,169,108,115,138,153,107,144,182,62,99,93,151,175,186,109,176,109,108,162,162,462,230,230,230,355,210,119,119,108,188,103,209,190,126,89,90,68,188,183,90,79,240,231,159,181,152,130,89,99,183,144,62,122,128,143,224,96,72,232,258,111,122,122,136,138,250,125,97,128,143,150,155,190,130,156,85,111,121,135,90,90,222,167,130,131,270,134,165,197,113,113,125,182,81,191,137,136,139,124,112,111,88,128,125,139,140,125,142,160,155,115,116,115,80,92,185,92,159,184,112,141,183,191,150,114,244,188,219,93,169,113,113,113,144,87,162,147,101,175,127,171,189,119,135,131,86,89,113,93,84,259,193,176,113,83,179,184,77,140,126,117,183,167,159,159,262,211,172,96,124,95,92,139,99,122,76,75,154,93,117,151,158,95,116,137,94,115,224,211,224,84,112,149,111,88,319,202,196,94,146,115,115,153,153,295,210,117,121,51,93,55,84,84,189,78,196,196,118,120,104,99,115,87,55,160,206,93,170,110,108,113,110,106,67,83,93,99,115,91,96,128,85,115,84,121,127,118,121,122,120,122,88,118,118,122,140,140,122,140,154,116,76,81,105,116,134,105,80,81,83,79,83,57,107,57,143,57,79,57,82,100,57,123,142,141,89,116,94,166,213,149,194,152,104,132,84,118,139,125,81,107,152,64,97,37,102,268,268,90,120,170,154,142,58,79,82,88,193,192,130,88,121,142,122,192,192,121,145,121,192,171,274,129,163,149,170,176,122,87,170,170,106,58,109,93,79,100,100,130,144,115,162,115,194,135,146,194,108,118,91,177,142,174,174,132,119,119,134,122,115,146,115,116,121,121,143,94,172,110,93,133,110,72,300,91,138,229,138,107,108,81,138,202,91,91,129,145,124,145,122,132,151,103,116,143,239,77,207,345,121,345,85,45,131,137,130,131,159,142,119,91,120,149,88,117,83,140,55,106,93,55,85,196,89,54,150,144,140,140,140,128,120,106,100,116,134,152,179,107,107,271,215,116,188,105,176,176,116,116,116,126,93,130,113,112,126,117,90,113,126,145,114,84,126,95,110,110,132,137,109,122,89,127,92,149,112,155,116,112,113,107,92,81,66,81,108,109,110,83,109,109,66,139,172,126,120,99,126,127,116,126,87,121,121,181,217,216,104,127,115,117,104,184,149,137,120,119,98,209,162,160,162,159,95,111,111,121,115,113,128,126,115,115,174,75,75,82,54,103,103,55,75,95,78,75,107,97,80,108,198,141,129,154,199,146,129,87,103,141,172,59,107,107,103,117,119,92,112,126,113,134,186,105,124,221,174,108,73,79,113,118,147,149,250,120,118,114,152,62,110,110,118,43,118,141,85,224,199,199,86,147,153,108,163,256,244,284,206,124,98,77,119,297,95,297,138,249,129,112,92,124,164,118,173,167,117,82,117,83,106,107,77,113,126,142,92,126,126,92,163,91,142,142,91,90,99,137,135,122,121,211,169,162,178,115,82,162,183,54,140,156,115,114,139,92,92,114,114,153,113,153,131,52,141,108,108,117,158,158,156,154,155,157,160,135,124,121,123,103,84,113,132,114,114,132,117,114,114,105,168,119,154,154,114,154,114,114,154,154,105,117,139,117,119,117,117,137,299,86,63,63,122,82,123,55,104,86,121,142,93,121,161,89,89,91,109,81,45,105,106,146,106,45,113,147,107,108,108,107,86,112,90,90,297,167,153,194,97,99,113,127,143,98,106,100,47,225,99,100,141,116,118,116,233,110,103,69,114,74,108,95,95,87,127,122,122,145,170,87,93,86,87,115,92,190,135,135,135,114,211,135,214,114,112,190,114,114,114,158,181,158,155,117,80,158,119,70,89,80,80,121,121,113,132,120,141,141,123,164,163,163,163,88,107,109,131,89,109,109,90,120,90,116,40,56,40,40,56,47,40,40,40,113,180,89,112,92,409,73,333,86,351,141,124,124,112,124,124,251,271,95,141,113,146,114,137,114,119,115,115,129,81,130,112,116,116,167,128,115,116,116,98,116,116,115,112,114,102,143,114,123,123,111,110,110,85,123,82,143,123,143,113,158,113,126,130,183,124,208,114,130,114,114,187,180,180,140,164,115,170,193,84,132,84,84,121,114,157,114,131,114,104,103,86,72,97,112,72,97,85,105,112,85,97,97,122,145,125,181,145,115,115,53,112,80,115,112,96,127,126,130,96,132,131,130,132,100,129,114,114,114,114,114,126,119,118,432,119,119,83,123,124,124,112,114,193,152,124,110,90,86,133,89,110,91,350,211,99,174,184,191,95,93,191,191,100,191,191,191,93,355,174,174,174,174,97,204,87,87,87,87,87,87,371,243,120,76,193,106,91,113,259,103,74,51,113,113,92,113,97,97,87,128,92,89,92,196,140,73],\"y\":[3000000,3880000,3325000,4250000,1400000,1320000,3410000,1420000,2025000,2550000,927000,1305000,8200000,970000,2400000,4850000,3100000,1300000,1317500,15844000,1668000,1830000,1000000,1340000,900000,8575376,3828000,1080000,1090000,1080000,1980000,1440000,5100000,1750000,1510000,5236000,2900000,3225000,1400000,750000,1149000,1700000,1080000,1107500,2200000,3300000,1900000,4091520,3180000,1315000,2680000,880000,690000,1430000,1030000,2988000,4770000,5787000,1138000,880000,3175000,1018000,10000000,3950000,1130000,1390000,1950000,1124000,8090000,2250000,1530000,1810000,2750000,1320000,1030000,4534000,1520000,1340000,1630000,880000,855000,2408888,2420000,3637000,4000000,5718000,2180000,950000,1040000,880000,980000,2250000,1850000,1668888,2080000,1327000,1520000,1087500,1410000,1140000,1425000,2319000,1108000,872000,4100000,2785000,2100000,2200000,6000000,3100000,900000,6960000,5525000,2050000,2000000,2250000,2600000,1190000,1680000,1500000,1200000,858000,688000,1544000,3300000,1025000,1830000,2900000,3300000,4134444,3060000,1680000,3500000,1260000,1966110,2600000,5200000,4150000,1965000,970000,1050000,2292500,4650000,1905000,3364444,1780000,2550000,1160000,18000000,1620000,1030000,1050000,985000,2125000,1090000,1500000,13900000,1537500,1204000,1020000,1350000,1201200,3050000,1710000,1480000,1138000,1160000,1390000,2196000,2196000,5500000,2530000,1660000,2080000,1850000,2050000,1858888,2700000,2310000,2750000,2130000,595000,630000,980000,1980000,2400000,1940000,4865000,5425000,3350000,1699000,1580000,950000,990000,753800,2750000,3060000,2550000,1690000,1140000,1065000,1900000,1200000,1430000,1350000,1400000,1657500,1095000,2465900,1290000,1759000,5100000,1383944,1606000,1480000,1545750,1485000,1514400,1280000,1700000,2150000,1540000,1677500,1860000,1172500,1159000,2750000,3400000,1349000,1720000,1300000,912500,1731500,2930000,5000000,2060000,2250900,640000,1100000,1472500,1680000,1439999.5,1025000,1030000,3325000,3750000,2725000,1538000,1088000,1400000,1182500,4600000,5050000,2750000,1950000,1500000,1925000,2400000,8500000,1180000,1265000,1288000,2480000,2300000,2809500,3650000,3075000,2737500,3323000,1790000,2700000,5800000,2135000,2975000,2050000,1440000,2000000,1688715,3200000,868000,1190000,1787500,1520000,2100000,2880000,1950000,1835000,1452840,1420000,1427500,1170000,1420000,1650000,1800000,1650000,1580000,1255000,1660000,3600000,680000,1440000,1310000,5350000,5500000,6750000,4130000,4150000,4150000,1450000,1890000,1994000,1458000,2200000,1450000,1361740,1440000,3194000,2060000,1205000,1445000,1500000,1520000,2530000,1385000,1820000,2080000,2000000,1645000,1500000,1610000,1780000,1770000,1868000,4515000,3450000,3800000,2490000,2410000,1395000,1150000,1220000,1600000,2500000,1606444,2115000,2418000,1500000,1319000,1050000,875000,1310000,1950304,2855000,2062094,2170000,4125000,3015000,1070000,1089000,1400000,1540000,1590000,1490000,1630000,1900000,2388000,1610000,1940000,1236000,983000,1065000,1030000,1360000,2730000,3486000,894444,890000,818000,2000000,2500000,2520000,2475000,2620000,1290000,1300000,2200000,2140000,3900000,1988000,1910000,1780000,10500000,10000000,1272500,1590000,2450000,1200000,1870000,3900000,3400000,2200000,850000,863888,685000,5180000,5500000,1299000,1441875,2750000,2600000,1690000,1780000,2210000,2300000,1848500,2260000,2149500,1680000,1080000,1550000,2250000,2350000,3600000,1935000,1230000,2300000,1762500,1460000,1580000,1557500,1432500,1378000,6500000,1080000,958000,1195000,1620000,1950000,2050000,2658000,2965000,3180000,1549444,1234000,1270000,1360000,892500,1214000,3240000,3800000,3874000,1107500,1427500,1950000,2425000,2950000,985000,1050000,2750000,4050000,1620000,2501000,2458800,2230000,2550000,4840000,1560000,1465000,1315000,1980000,1850000,2095000,2125000,1267600,1350000,1498888,1535000,1309888,1440000,1367500,1802500,1900000,3900000,3100000,3455000,3219444,1794000,1175000,1250000,1438000,1042500,2290000,3850000,3550000,3227500,1935000,3800000,1160000,1145000,1205500,1490000,1758000,2185000,2030000,1345000,2200000,1730000,1950000,1210000,940000,1035000,1292500,1070000,1250000,990000,960000,1347500,4590000,3500000,2698000,1850000,2350000,2150000,2030000,1690000,1240000,1220000,1210000,2000000,1512500,1630000,1680000,4577500,3550000,2920000,1990000,2400000,1825000,1613700,2125000,1705000,2039888,869800,850000,3103000,2030000,1380000,1615000,1630000,1240000,1542500,1275000,1145000,1390000,1281500,1570000,1550000,1350000,1800000,1140000,984000,840000,6500000,3025000,2875000,1877500,1820000,1330000,1160000,1330000,1380000,5375000,3900000,1200000,1510000,1045000,1660000,1900000,1535000,1638000,1375000,863000,2325000,2125000,1075000,950000,815000,1127500,1200000,1265000,1311200,3605000,1190000,1180000,1030000,823000,800000,1320444,792500,808000,900000,1160000,1064000,1150000,1615000,1830000,2272500,2080000,1395000,1150000,990000,1356444,1400000,1215000,1192500,1280000,1295000,1295000,1145000,1204000,1255000,1010000,1100000,1273000,1025000,1150000,1785500,1540000,1388000,1005000,1425000,1530000,1500000,1406500,1100000,770000,780000,782500,840000,660000,1000000,660000,1210000,682500,888000,667500,818000,950000,675000,1160000,1350000,1388000,1089000,1295944,1700000,2202500,2950000,2590000,2070000,1000000,770000,968000,850000,1160000,1360000,1291500,1238000,1080000,1600000,760000,929000,655000,1330000,8300000,8450000,1620000,1545000,3000000,2742500,1825000,690000,870000,1038888,1150000,1705000,2400000,1670000,1125000,1380000,1350000,1388000,1230000,1317500,945000,1100000,902500,1300000,1818000,1900000,1380000,1350000,1250000,2530000,2528000,1630000,965000,1120000,1310000,900000,1350000,1050000,980000,900000,1220000,1200000,1700000,1850000,1019444,1449000,1025000,1625000,1225000,1300000,1648000,1495000,1300000,1284000,1190000,930000,1180000,1490000,992500,860000,940000,950000,1730000,1204000,1363000,1150000,1355000,1197500,1282500,1525000,1620000,2662500,795000,768000,910000,888888,1125000,2100000,1580000,2430000,3550000,2300000,1398888,1340000,1329000,1233800,2930000,880000,884000,1100000,2005000,1480000,1920000,1730000,1824000,1950000,1130000,1128000,1340000,3093000,1238000,2420000,1650000,1720000,2335000,1125000,734000,2100000,2060000,2140000,1879000,2141115,1339000,1231000,955000,1270000,1780000,1038888,1307500,1378000,2075000,1311000,1480000,910000,594500,1670000,2021440,1668000,2440000,940000,1035000,898400,900000,860000,1150000,1125000,1360000,1430000,1438000,1700000,3970000,1305000,1255000,1160000,1335000,1267500,1145000,1540000,1050000,1320000,1330000,970000,1020000,982500,968000,760000,1030000,880000,870000,1475000,1600000,1355000,1225000,1530000,1838888,1570000,1165000,1660000,862500,923000,937500,1277500,1050000,900000,1930000,2105000,1790000,1990000,1850000,1200888,1590000,1230000,1230000,1293000,1100000,990000,960000,1150000,940000,1105000,985000,985000,900000,1141344,1085000,750000,1230000,1608000,1180000,1300444,1040000,1307500,1225000,995000,1265000,1020000,1930000,1938000,2850000,3050000,2938000,950000,1200000,1100000,1124000,950000,1350000,1650000,1375000,1360000,1375000,3268000,2405000,2150000,2150000,2120000,1485000,908000,1085000,1130000,1160000,1110000,1130000,1189998,1150000,1033000,1230000,1505000,1065000,830000,870000,642888,1230000,1150000,660000,733888,1132500,1050000,1000000,1220000,1458500,1060000,1179000,2250000,1430000,1456000,1680000,2200000,1642000,1018500,819000,960000,1718600,1792500,1300000,1219000,1188888,1055000,1290000,1350000,1257500,1116000,1210000,1070000,2380000,3500000,2630000,2140000,1965000,1995000,1135000,1052500,1230000,1690000,1465000,1750000,1717100,2350000,1929400,1520000,1420000,1530000,730000,1358888,1320000,1445260,635000,1115000,1460000,1270000,3105000,2855000,3172500,1688800,2120000,1950000,2173480,2672235,2855000,3720000,4120000,3675000,1080000,875000,800000,1048000,1635000,880000,2000000,1468000,1940000,1315000,1390000,962500,1260000,2075000,1724000,1950000,2062000,1420000,1100000,1442500,1120000,1288888,1465000,1057500,1680000,1500000,1490000,1040000,1250000,1367500,1252500,1738444,920000,1400000,1040000,930000,860000,1255000,1760000,1680000,1745000,1840000,1880000,2170900,1600000,1850000,1430000,1360000,1600000,1720000,1045000,1430000,1710000,970000,988000,1108000,828000,815000,970000,1038000,2620000,2065000,2610084,2280000,1679000,2640000,830000,849000,928000,840000,950000,906500,890000,875000,920500,872500,1900000,1797500,2260000,2130000,955000,920000,1207500,1450000,1230000,1168000,1405000,1225000,1212544,1290000,1388444,1635000,1590000,1380000,1395000,1202500,1400000,1300000,1219000,1520000,1408000,890000,1065000,1705000,860000,980000,1057500,1050000,1100000,3050000,1395000,1155000,1125000,1900000,2085444,1952900,700000,965000,908000,1119000,1320000,940000,1320000,1019000,840000,767500,807000,787500,775000,1350000,1660000,1760000,1955000,1940000,1328000,1855000,1694444,1206000,1230000,1260000,1045000,1015000,1382500,1382000,1370000,2650000,1655000,1665000,2100000,1055000,1010700,1142500,1063000,1128000,940000,1138000,1145000,1270000,1892010,1185000,982888,1095000,1027500,1040500,1030584,2000000,1365000,1100000,800000,1270000,840000,851500,900000,869444,1050000,1350000,1380000,1320000,1580000,1560000,1060000,1072500,834444,1060000,1080000,1067500,1332500,1190000,1218000,1260000,1095000,1650000,1235000,1698000,990000,1120000,1400000,1108000,980000,1007500,1100000,1260000,1145000,1150000,1000000,1015000,1328000,1084000,780000,950000,969444,852000,1605400,1739000,1481500,1635000,1612000,2000000,1935000,1220000,1239800,1501500,1500000,1300000,918000,970000,915000,1025000,907500,860000,920000,990000,995000,1080000,1350000,545000,628000,600000,547000,720000,599444,540000,615000,555000,920000,888000,780000,860000,1276238,2550000,1168000,947500,935000,1328000,1430000,1330000,1250000,1069000,1720000,1869000,3690000,1880000,1268888,1035000,1050000,1250000,1035000,1270000,950000,935000,1050000,1035000,1300000,930000,1357500,1240000,1430000,950000,1239440,1130000,950000,1100000,918000,857500,960000,950000,965000,1030000,1030000,838000,1200000,1150000,1160000,1270000,1515000,1455000,1450000,905000,1220000,1044000,1360000,1245000,1409000,1680000,2552000,1630000,1305000,1422500,2200000,1719999,2861666.5,1215000,1214000,1195000,1200000,1380000,1225000,1320000,1825000,2105000,1413888,2220000,2450000,1091500,1421500,1120000,1120000,1295000,1310000,1400000,1358000,1500000,1239000,1112500,1225000,1010000,1007500,1050000,1120000,1230000,1180000,860000,1250000,1190000,980000,1180000,1119000,1600000,2285000,1570000,1690000,2000000,1650000,1519952,1300000,1292500,1350000,1350000,1660000,1115000,1255000,1330000,1365000,1820000,1396500,1350000,1362500,1365000,1009750,1260000,1070700,1090000,995000,1050000,975000,2060000,1890000,1825000,3095590,1870000,1900000,1380000,1970000,1950000,1940000,2065000,1845000,3759000,2565000,1870000,1030000,832500,1012000,958000,885000,940000,905000,3392440,2743530,2700000,2362400,2382100,2629000,1830000,1380000,1668000,2228550,1300000,2124700,1853000,2571350,1280000,3123900,2290890,2359200,2427336,2444000,1365000,1132500,1080000,825000,968000,1095000,990000,870000,9600000,4500000,2900000,1500000,4680000,1919000,2550000,1445000,2750000,1185000,780000,758000,1420000,1340000,1120000,1400000,835000,820000,750000,975000,780000,750250,765000,3282200,2595900,1466100],\"text\":[\"AREA_SQM: 309<br />SELLING_PRICE:  3000000\",\"AREA_SQM: 290<br />SELLING_PRICE:  3880000\",\"AREA_SQM: 248<br />SELLING_PRICE:  3325000\",\"AREA_SQM: 127<br />SELLING_PRICE:  4250000\",\"AREA_SQM: 145<br />SELLING_PRICE:  1400000\",\"AREA_SQM: 139<br />SELLING_PRICE:  1320000\",\"AREA_SQM: 218<br />SELLING_PRICE:  3410000\",\"AREA_SQM: 141<br />SELLING_PRICE:  1420000\",\"AREA_SQM: 165<br />SELLING_PRICE:  2025000\",\"AREA_SQM: 168<br />SELLING_PRICE:  2550000\",\"AREA_SQM: 112<br />SELLING_PRICE:   927000\",\"AREA_SQM:  89<br />SELLING_PRICE:  1305000\",\"AREA_SQM: 302<br />SELLING_PRICE:  8200000\",\"AREA_SQM:  97<br />SELLING_PRICE:   970000\",\"AREA_SQM: 164<br />SELLING_PRICE:  2400000\",\"AREA_SQM: 216<br />SELLING_PRICE:  4850000\",\"AREA_SQM: 177<br />SELLING_PRICE:  3100000\",\"AREA_SQM: 152<br />SELLING_PRICE:  1300000\",\"AREA_SQM: 148<br />SELLING_PRICE:  1317500\",\"AREA_SQM: 368<br />SELLING_PRICE: 15844000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1668000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1830000\",\"AREA_SQM: 136<br />SELLING_PRICE:  1000000\",\"AREA_SQM: 133<br />SELLING_PRICE:  1340000\",\"AREA_SQM: 115<br />SELLING_PRICE:   900000\",\"AREA_SQM: 258<br />SELLING_PRICE:  8575376\",\"AREA_SQM: 199<br />SELLING_PRICE:  3828000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1080000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1090000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1080000\",\"AREA_SQM: 152<br />SELLING_PRICE:  1980000\",\"AREA_SQM: 134<br />SELLING_PRICE:  1440000\",\"AREA_SQM: 322<br />SELLING_PRICE:  5100000\",\"AREA_SQM:  96<br />SELLING_PRICE:  1750000\",\"AREA_SQM: 111<br />SELLING_PRICE:  1510000\",\"AREA_SQM: 278<br />SELLING_PRICE:  5236000\",\"AREA_SQM: 191<br />SELLING_PRICE:  2900000\",\"AREA_SQM: 207<br />SELLING_PRICE:  3225000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1400000\",\"AREA_SQM:  65<br />SELLING_PRICE:   750000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1149000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1700000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1080000\",\"AREA_SQM: 227<br />SELLING_PRICE:  1107500\",\"AREA_SQM: 115<br />SELLING_PRICE:  2200000\",\"AREA_SQM: 179<br />SELLING_PRICE:  3300000\",\"AREA_SQM: 156<br />SELLING_PRICE:  1900000\",\"AREA_SQM: 198<br />SELLING_PRICE:  4091520\",\"AREA_SQM: 171<br />SELLING_PRICE:  3180000\",\"AREA_SQM: 109<br />SELLING_PRICE:  1315000\",\"AREA_SQM: 149<br />SELLING_PRICE:  2680000\",\"AREA_SQM:  58<br />SELLING_PRICE:   880000\",\"AREA_SQM:  60<br />SELLING_PRICE:   690000\",\"AREA_SQM: 211<br />SELLING_PRICE:  1430000\",\"AREA_SQM: 109<br />SELLING_PRICE:  1030000\",\"AREA_SQM: 131<br />SELLING_PRICE:  2988000\",\"AREA_SQM: 197<br />SELLING_PRICE:  4770000\",\"AREA_SQM: 235<br />SELLING_PRICE:  5787000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1138000\",\"AREA_SQM:  89<br />SELLING_PRICE:   880000\",\"AREA_SQM: 167<br />SELLING_PRICE:  3175000\",\"AREA_SQM:  80<br />SELLING_PRICE:  1018000\",\"AREA_SQM: 284<br />SELLING_PRICE: 10000000\",\"AREA_SQM: 241<br />SELLING_PRICE:  3950000\",\"AREA_SQM:  81<br />SELLING_PRICE:  1130000\",\"AREA_SQM: 137<br />SELLING_PRICE:  1390000\",\"AREA_SQM: 157<br />SELLING_PRICE:  1950000\",\"AREA_SQM: 111<br />SELLING_PRICE:  1124000\",\"AREA_SQM: 376<br />SELLING_PRICE:  8090000\",\"AREA_SQM: 264<br />SELLING_PRICE:  2250000\",\"AREA_SQM:  98<br />SELLING_PRICE:  1530000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1810000\",\"AREA_SQM: 244<br />SELLING_PRICE:  2750000\",\"AREA_SQM:  97<br />SELLING_PRICE:  1320000\",\"AREA_SQM: 103<br />SELLING_PRICE:  1030000\",\"AREA_SQM: 300<br />SELLING_PRICE:  4534000\",\"AREA_SQM:  92<br />SELLING_PRICE:  1520000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1340000\",\"AREA_SQM: 147<br />SELLING_PRICE:  1630000\",\"AREA_SQM:  74<br />SELLING_PRICE:   880000\",\"AREA_SQM:  91<br />SELLING_PRICE:   855000\",\"AREA_SQM: 204<br />SELLING_PRICE:  2408888\",\"AREA_SQM: 188<br />SELLING_PRICE:  2420000\",\"AREA_SQM: 334<br />SELLING_PRICE:  3637000\",\"AREA_SQM: 325<br />SELLING_PRICE:  4000000\",\"AREA_SQM: 322<br />SELLING_PRICE:  5718000\",\"AREA_SQM: 162<br />SELLING_PRICE:  2180000\",\"AREA_SQM: 118<br />SELLING_PRICE:   950000\",\"AREA_SQM:  97<br />SELLING_PRICE:  1040000\",\"AREA_SQM:  78<br />SELLING_PRICE:   880000\",\"AREA_SQM: 105<br />SELLING_PRICE:   980000\",\"AREA_SQM: 164<br />SELLING_PRICE:  2250000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1850000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1668888\",\"AREA_SQM: 188<br />SELLING_PRICE:  2080000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1327000\",\"AREA_SQM: 164<br />SELLING_PRICE:  1520000\",\"AREA_SQM:  81<br />SELLING_PRICE:  1087500\",\"AREA_SQM: 109<br />SELLING_PRICE:  1410000\",\"AREA_SQM: 101<br />SELLING_PRICE:  1140000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1425000\",\"AREA_SQM: 145<br />SELLING_PRICE:  2319000\",\"AREA_SQM:  92<br />SELLING_PRICE:  1108000\",\"AREA_SQM:  98<br />SELLING_PRICE:   872000\",\"AREA_SQM: 291<br />SELLING_PRICE:  4100000\",\"AREA_SQM: 192<br />SELLING_PRICE:  2785000\",\"AREA_SQM: 120<br />SELLING_PRICE:  2100000\",\"AREA_SQM: 148<br />SELLING_PRICE:  2200000\",\"AREA_SQM: 422<br />SELLING_PRICE:  6000000\",\"AREA_SQM: 228<br />SELLING_PRICE:  3100000\",\"AREA_SQM:  47<br />SELLING_PRICE:   900000\",\"AREA_SQM: 351<br />SELLING_PRICE:  6960000\",\"AREA_SQM: 307<br />SELLING_PRICE:  5525000\",\"AREA_SQM: 190<br />SELLING_PRICE:  2050000\",\"AREA_SQM: 165<br />SELLING_PRICE:  2000000\",\"AREA_SQM: 203<br />SELLING_PRICE:  2250000\",\"AREA_SQM: 236<br />SELLING_PRICE:  2600000\",\"AREA_SQM:  94<br />SELLING_PRICE:  1190000\",\"AREA_SQM: 162<br />SELLING_PRICE:  1680000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1500000\",\"AREA_SQM:  90<br />SELLING_PRICE:  1200000\",\"AREA_SQM:  49<br />SELLING_PRICE:   858000\",\"AREA_SQM:  47<br />SELLING_PRICE:   688000\",\"AREA_SQM: 186<br />SELLING_PRICE:  1544000\",\"AREA_SQM: 209<br />SELLING_PRICE:  3300000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1025000\",\"AREA_SQM: 143<br />SELLING_PRICE:  1830000\",\"AREA_SQM: 188<br />SELLING_PRICE:  2900000\",\"AREA_SQM: 203<br />SELLING_PRICE:  3300000\",\"AREA_SQM: 226<br />SELLING_PRICE:  4134444\",\"AREA_SQM: 113<br />SELLING_PRICE:  3060000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1680000\",\"AREA_SQM: 218<br />SELLING_PRICE:  3500000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1260000\",\"AREA_SQM:  94<br />SELLING_PRICE:  1966110\",\"AREA_SQM: 202<br />SELLING_PRICE:  2600000\",\"AREA_SQM: 212<br />SELLING_PRICE:  5200000\",\"AREA_SQM: 164<br />SELLING_PRICE:  4150000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1965000\",\"AREA_SQM: 105<br />SELLING_PRICE:   970000\",\"AREA_SQM: 105<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 175<br />SELLING_PRICE:  2292500\",\"AREA_SQM: 115<br />SELLING_PRICE:  4650000\",\"AREA_SQM: 136<br />SELLING_PRICE:  1905000\",\"AREA_SQM: 171<br />SELLING_PRICE:  3364444\",\"AREA_SQM:  97<br />SELLING_PRICE:  1780000\",\"AREA_SQM: 135<br />SELLING_PRICE:  2550000\",\"AREA_SQM:  56<br />SELLING_PRICE:  1160000\",\"AREA_SQM: 323<br />SELLING_PRICE: 18000000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1620000\",\"AREA_SQM:  96<br />SELLING_PRICE:  1030000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 113<br />SELLING_PRICE:   985000\",\"AREA_SQM: 157<br />SELLING_PRICE:  2125000\",\"AREA_SQM: 135<br />SELLING_PRICE:  1090000\",\"AREA_SQM: 109<br />SELLING_PRICE:  1500000\",\"AREA_SQM: 619<br />SELLING_PRICE: 13900000\",\"AREA_SQM: 152<br />SELLING_PRICE:  1537500\",\"AREA_SQM: 124<br />SELLING_PRICE:  1204000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1020000\",\"AREA_SQM: 151<br />SELLING_PRICE:  1350000\",\"AREA_SQM:  93<br />SELLING_PRICE:  1201200\",\"AREA_SQM: 241<br />SELLING_PRICE:  3050000\",\"AREA_SQM:  87<br />SELLING_PRICE:  1710000\",\"AREA_SQM: 131<br />SELLING_PRICE:  1480000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1138000\",\"AREA_SQM: 134<br />SELLING_PRICE:  1160000\",\"AREA_SQM: 173<br />SELLING_PRICE:  1390000\",\"AREA_SQM: 204<br />SELLING_PRICE:  2196000\",\"AREA_SQM: 204<br />SELLING_PRICE:  2196000\",\"AREA_SQM: 200<br />SELLING_PRICE:  5500000\",\"AREA_SQM: 122<br />SELLING_PRICE:  2530000\",\"AREA_SQM: 171<br />SELLING_PRICE:  1660000\",\"AREA_SQM: 281<br />SELLING_PRICE:  2080000\",\"AREA_SQM: 264<br />SELLING_PRICE:  1850000\",\"AREA_SQM: 281<br />SELLING_PRICE:  2050000\",\"AREA_SQM: 272<br />SELLING_PRICE:  1858888\",\"AREA_SQM: 361<br />SELLING_PRICE:  2700000\",\"AREA_SQM: 167<br />SELLING_PRICE:  2310000\",\"AREA_SQM: 155<br />SELLING_PRICE:  2750000\",\"AREA_SQM: 156<br />SELLING_PRICE:  2130000\",\"AREA_SQM:  34<br />SELLING_PRICE:   595000\",\"AREA_SQM:  35<br />SELLING_PRICE:   630000\",\"AREA_SQM:  89<br />SELLING_PRICE:   980000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1980000\",\"AREA_SQM: 158<br />SELLING_PRICE:  2400000\",\"AREA_SQM: 127<br />SELLING_PRICE:  1940000\",\"AREA_SQM: 188<br />SELLING_PRICE:  4865000\",\"AREA_SQM: 188<br />SELLING_PRICE:  5425000\",\"AREA_SQM: 189<br />SELLING_PRICE:  3350000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1699000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1580000\",\"AREA_SQM: 108<br />SELLING_PRICE:   950000\",\"AREA_SQM: 111<br />SELLING_PRICE:   990000\",\"AREA_SQM:  47<br />SELLING_PRICE:   753800\",\"AREA_SQM: 149<br />SELLING_PRICE:  2750000\",\"AREA_SQM: 174<br />SELLING_PRICE:  3060000\",\"AREA_SQM: 136<br />SELLING_PRICE:  2550000\",\"AREA_SQM:  87<br />SELLING_PRICE:  1690000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1140000\",\"AREA_SQM:  99<br />SELLING_PRICE:  1065000\",\"AREA_SQM: 206<br />SELLING_PRICE:  1900000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1200000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1430000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 164<br />SELLING_PRICE:  1400000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1657500\",\"AREA_SQM:  95<br />SELLING_PRICE:  1095000\",\"AREA_SQM: 122<br />SELLING_PRICE:  2465900\",\"AREA_SQM:  74<br />SELLING_PRICE:  1290000\",\"AREA_SQM:  84<br />SELLING_PRICE:  1759000\",\"AREA_SQM: 259<br />SELLING_PRICE:  5100000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1383944\",\"AREA_SQM: 170<br />SELLING_PRICE:  1606000\",\"AREA_SQM: 170<br />SELLING_PRICE:  1480000\",\"AREA_SQM: 170<br />SELLING_PRICE:  1545750\",\"AREA_SQM: 105<br />SELLING_PRICE:  1485000\",\"AREA_SQM: 105<br />SELLING_PRICE:  1514400\",\"AREA_SQM:  88<br />SELLING_PRICE:  1280000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1700000\",\"AREA_SQM: 210<br />SELLING_PRICE:  2150000\",\"AREA_SQM:  97<br />SELLING_PRICE:  1540000\",\"AREA_SQM: 144<br />SELLING_PRICE:  1677500\",\"AREA_SQM: 106<br />SELLING_PRICE:  1860000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1172500\",\"AREA_SQM: 113<br />SELLING_PRICE:  1159000\",\"AREA_SQM: 170<br />SELLING_PRICE:  2750000\",\"AREA_SQM: 204<br />SELLING_PRICE:  3400000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1349000\",\"AREA_SQM: 137<br />SELLING_PRICE:  1720000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1300000\",\"AREA_SQM: 123<br />SELLING_PRICE:   912500\",\"AREA_SQM: 124<br />SELLING_PRICE:  1731500\",\"AREA_SQM: 153<br />SELLING_PRICE:  2930000\",\"AREA_SQM: 266<br />SELLING_PRICE:  5000000\",\"AREA_SQM: 120<br />SELLING_PRICE:  2060000\",\"AREA_SQM: 102<br />SELLING_PRICE:  2250900\",\"AREA_SQM:  37<br />SELLING_PRICE:   640000\",\"AREA_SQM:  84<br />SELLING_PRICE:  1100000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1472500\",\"AREA_SQM: 134<br />SELLING_PRICE:  1680000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1440000\",\"AREA_SQM:  86<br />SELLING_PRICE:  1025000\",\"AREA_SQM: 103<br />SELLING_PRICE:  1030000\",\"AREA_SQM: 236<br />SELLING_PRICE:  3325000\",\"AREA_SQM: 303<br />SELLING_PRICE:  3750000\",\"AREA_SQM: 176<br />SELLING_PRICE:  2725000\",\"AREA_SQM: 102<br />SELLING_PRICE:  1538000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1088000\",\"AREA_SQM: 185<br />SELLING_PRICE:  1400000\",\"AREA_SQM: 135<br />SELLING_PRICE:  1182500\",\"AREA_SQM: 246<br />SELLING_PRICE:  4600000\",\"AREA_SQM: 266<br />SELLING_PRICE:  5050000\",\"AREA_SQM: 163<br />SELLING_PRICE:  2750000\",\"AREA_SQM:  82<br />SELLING_PRICE:  1950000\",\"AREA_SQM:  86<br />SELLING_PRICE:  1500000\",\"AREA_SQM: 139<br />SELLING_PRICE:  1925000\",\"AREA_SQM: 161<br />SELLING_PRICE:  2400000\",\"AREA_SQM: 311<br />SELLING_PRICE:  8500000\",\"AREA_SQM: 111<br />SELLING_PRICE:  1180000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1265000\",\"AREA_SQM: 137<br />SELLING_PRICE:  1288000\",\"AREA_SQM: 151<br />SELLING_PRICE:  2480000\",\"AREA_SQM: 154<br />SELLING_PRICE:  2300000\",\"AREA_SQM: 195<br />SELLING_PRICE:  2809500\",\"AREA_SQM: 156<br />SELLING_PRICE:  3650000\",\"AREA_SQM: 139<br />SELLING_PRICE:  3075000\",\"AREA_SQM: 138<br />SELLING_PRICE:  2737500\",\"AREA_SQM: 204<br />SELLING_PRICE:  3323000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1790000\",\"AREA_SQM: 179<br />SELLING_PRICE:  2700000\",\"AREA_SQM: 384<br />SELLING_PRICE:  5800000\",\"AREA_SQM: 192<br />SELLING_PRICE:  2135000\",\"AREA_SQM: 123<br />SELLING_PRICE:  2975000\",\"AREA_SQM: 153<br />SELLING_PRICE:  2050000\",\"AREA_SQM:  74<br />SELLING_PRICE:  1440000\",\"AREA_SQM: 154<br />SELLING_PRICE:  2000000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1688715\",\"AREA_SQM: 157<br />SELLING_PRICE:  3200000\",\"AREA_SQM:  84<br />SELLING_PRICE:   868000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1190000\",\"AREA_SQM:  97<br />SELLING_PRICE:  1787500\",\"AREA_SQM:  86<br />SELLING_PRICE:  1520000\",\"AREA_SQM: 119<br />SELLING_PRICE:  2100000\",\"AREA_SQM: 117<br />SELLING_PRICE:  2880000\",\"AREA_SQM: 195<br />SELLING_PRICE:  1950000\",\"AREA_SQM: 179<br />SELLING_PRICE:  1835000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1452840\",\"AREA_SQM: 122<br />SELLING_PRICE:  1420000\",\"AREA_SQM: 145<br />SELLING_PRICE:  1427500\",\"AREA_SQM: 101<br />SELLING_PRICE:  1170000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1420000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1650000\",\"AREA_SQM: 170<br />SELLING_PRICE:  1800000\",\"AREA_SQM: 150<br />SELLING_PRICE:  1650000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1580000\",\"AREA_SQM:  88<br />SELLING_PRICE:  1255000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1660000\",\"AREA_SQM: 316<br />SELLING_PRICE:  3600000\",\"AREA_SQM:  39<br />SELLING_PRICE:   680000\",\"AREA_SQM: 142<br />SELLING_PRICE:  1440000\",\"AREA_SQM:  87<br />SELLING_PRICE:  1310000\",\"AREA_SQM: 240<br />SELLING_PRICE:  5350000\",\"AREA_SQM: 240<br />SELLING_PRICE:  5500000\",\"AREA_SQM: 240<br />SELLING_PRICE:  6750000\",\"AREA_SQM: 354<br />SELLING_PRICE:  4130000\",\"AREA_SQM: 322<br />SELLING_PRICE:  4150000\",\"AREA_SQM: 146<br />SELLING_PRICE:  4150000\",\"AREA_SQM:  88<br />SELLING_PRICE:  1450000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1890000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1994000\",\"AREA_SQM:  88<br />SELLING_PRICE:  1458000\",\"AREA_SQM: 280<br />SELLING_PRICE:  2200000\",\"AREA_SQM:  98<br />SELLING_PRICE:  1450000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1361740\",\"AREA_SQM:  53<br />SELLING_PRICE:  1440000\",\"AREA_SQM: 353<br />SELLING_PRICE:  3194000\",\"AREA_SQM: 120<br />SELLING_PRICE:  2060000\",\"AREA_SQM:  91<br />SELLING_PRICE:  1205000\",\"AREA_SQM: 137<br />SELLING_PRICE:  1445000\",\"AREA_SQM: 142<br />SELLING_PRICE:  1500000\",\"AREA_SQM:  96<br />SELLING_PRICE:  1520000\",\"AREA_SQM: 182<br />SELLING_PRICE:  2530000\",\"AREA_SQM: 144<br />SELLING_PRICE:  1385000\",\"AREA_SQM: 363<br />SELLING_PRICE:  1820000\",\"AREA_SQM: 152<br />SELLING_PRICE:  2080000\",\"AREA_SQM: 126<br />SELLING_PRICE:  2000000\",\"AREA_SQM:  90<br />SELLING_PRICE:  1645000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1500000\",\"AREA_SQM: 176<br />SELLING_PRICE:  1610000\",\"AREA_SQM: 200<br />SELLING_PRICE:  1780000\",\"AREA_SQM: 200<br />SELLING_PRICE:  1770000\",\"AREA_SQM: 144<br />SELLING_PRICE:  1868000\",\"AREA_SQM: 349<br />SELLING_PRICE:  4515000\",\"AREA_SQM: 169<br />SELLING_PRICE:  3450000\",\"AREA_SQM: 211<br />SELLING_PRICE:  3800000\",\"AREA_SQM: 185<br />SELLING_PRICE:  2490000\",\"AREA_SQM: 341<br />SELLING_PRICE:  2410000\",\"AREA_SQM: 137<br />SELLING_PRICE:  1395000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1150000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1220000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1600000\",\"AREA_SQM: 181<br />SELLING_PRICE:  2500000\",\"AREA_SQM: 138<br />SELLING_PRICE:  1606444\",\"AREA_SQM: 138<br />SELLING_PRICE:  2115000\",\"AREA_SQM: 207<br />SELLING_PRICE:  2418000\",\"AREA_SQM: 135<br />SELLING_PRICE:  1500000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1319000\",\"AREA_SQM:  96<br />SELLING_PRICE:  1050000\",\"AREA_SQM:  71<br />SELLING_PRICE:   875000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1310000\",\"AREA_SQM:  96<br />SELLING_PRICE:  1950304\",\"AREA_SQM: 143<br />SELLING_PRICE:  2855000\",\"AREA_SQM: 100<br />SELLING_PRICE:  2062094\",\"AREA_SQM: 125<br />SELLING_PRICE:  2170000\",\"AREA_SQM: 193<br />SELLING_PRICE:  4125000\",\"AREA_SQM: 188<br />SELLING_PRICE:  3015000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1070000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1089000\",\"AREA_SQM:  91<br />SELLING_PRICE:  1400000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1540000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1590000\",\"AREA_SQM: 131<br />SELLING_PRICE:  1490000\",\"AREA_SQM: 134<br />SELLING_PRICE:  1630000\",\"AREA_SQM: 215<br />SELLING_PRICE:  1900000\",\"AREA_SQM: 218<br />SELLING_PRICE:  2388000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1610000\",\"AREA_SQM: 169<br />SELLING_PRICE:  1940000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1236000\",\"AREA_SQM: 115<br />SELLING_PRICE:   983000\",\"AREA_SQM: 138<br />SELLING_PRICE:  1065000\",\"AREA_SQM: 153<br />SELLING_PRICE:  1030000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1360000\",\"AREA_SQM: 144<br />SELLING_PRICE:  2730000\",\"AREA_SQM: 182<br />SELLING_PRICE:  3486000\",\"AREA_SQM:  62<br />SELLING_PRICE:   894444\",\"AREA_SQM:  99<br />SELLING_PRICE:   890000\",\"AREA_SQM:  93<br />SELLING_PRICE:   818000\",\"AREA_SQM: 151<br />SELLING_PRICE:  2000000\",\"AREA_SQM: 175<br />SELLING_PRICE:  2500000\",\"AREA_SQM: 186<br />SELLING_PRICE:  2520000\",\"AREA_SQM: 109<br />SELLING_PRICE:  2475000\",\"AREA_SQM: 176<br />SELLING_PRICE:  2620000\",\"AREA_SQM: 109<br />SELLING_PRICE:  1290000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1300000\",\"AREA_SQM: 162<br />SELLING_PRICE:  2200000\",\"AREA_SQM: 162<br />SELLING_PRICE:  2140000\",\"AREA_SQM: 462<br />SELLING_PRICE:  3900000\",\"AREA_SQM: 230<br />SELLING_PRICE:  1988000\",\"AREA_SQM: 230<br />SELLING_PRICE:  1910000\",\"AREA_SQM: 230<br />SELLING_PRICE:  1780000\",\"AREA_SQM: 355<br />SELLING_PRICE: 10500000\",\"AREA_SQM: 210<br />SELLING_PRICE: 10000000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1272500\",\"AREA_SQM: 119<br />SELLING_PRICE:  1590000\",\"AREA_SQM: 108<br />SELLING_PRICE:  2450000\",\"AREA_SQM: 188<br />SELLING_PRICE:  1200000\",\"AREA_SQM: 103<br />SELLING_PRICE:  1870000\",\"AREA_SQM: 209<br />SELLING_PRICE:  3900000\",\"AREA_SQM: 190<br />SELLING_PRICE:  3400000\",\"AREA_SQM: 126<br />SELLING_PRICE:  2200000\",\"AREA_SQM:  89<br />SELLING_PRICE:   850000\",\"AREA_SQM:  90<br />SELLING_PRICE:   863888\",\"AREA_SQM:  68<br />SELLING_PRICE:   685000\",\"AREA_SQM: 188<br />SELLING_PRICE:  5180000\",\"AREA_SQM: 183<br />SELLING_PRICE:  5500000\",\"AREA_SQM:  90<br />SELLING_PRICE:  1299000\",\"AREA_SQM:  79<br />SELLING_PRICE:  1441875\",\"AREA_SQM: 240<br />SELLING_PRICE:  2750000\",\"AREA_SQM: 231<br />SELLING_PRICE:  2600000\",\"AREA_SQM: 159<br />SELLING_PRICE:  1690000\",\"AREA_SQM: 181<br />SELLING_PRICE:  1780000\",\"AREA_SQM: 152<br />SELLING_PRICE:  2210000\",\"AREA_SQM: 130<br />SELLING_PRICE:  2300000\",\"AREA_SQM:  89<br />SELLING_PRICE:  1848500\",\"AREA_SQM:  99<br />SELLING_PRICE:  2260000\",\"AREA_SQM: 183<br />SELLING_PRICE:  2149500\",\"AREA_SQM: 144<br />SELLING_PRICE:  1680000\",\"AREA_SQM:  62<br />SELLING_PRICE:  1080000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1550000\",\"AREA_SQM: 128<br />SELLING_PRICE:  2250000\",\"AREA_SQM: 143<br />SELLING_PRICE:  2350000\",\"AREA_SQM: 224<br />SELLING_PRICE:  3600000\",\"AREA_SQM:  96<br />SELLING_PRICE:  1935000\",\"AREA_SQM:  72<br />SELLING_PRICE:  1230000\",\"AREA_SQM: 232<br />SELLING_PRICE:  2300000\",\"AREA_SQM: 258<br />SELLING_PRICE:  1762500\",\"AREA_SQM: 111<br />SELLING_PRICE:  1460000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1580000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1557500\",\"AREA_SQM: 136<br />SELLING_PRICE:  1432500\",\"AREA_SQM: 138<br />SELLING_PRICE:  1378000\",\"AREA_SQM: 250<br />SELLING_PRICE:  6500000\",\"AREA_SQM: 125<br />SELLING_PRICE:  1080000\",\"AREA_SQM:  97<br />SELLING_PRICE:   958000\",\"AREA_SQM: 128<br />SELLING_PRICE:  1195000\",\"AREA_SQM: 143<br />SELLING_PRICE:  1620000\",\"AREA_SQM: 150<br />SELLING_PRICE:  1950000\",\"AREA_SQM: 155<br />SELLING_PRICE:  2050000\",\"AREA_SQM: 190<br />SELLING_PRICE:  2658000\",\"AREA_SQM: 130<br />SELLING_PRICE:  2965000\",\"AREA_SQM: 156<br />SELLING_PRICE:  3180000\",\"AREA_SQM:  85<br />SELLING_PRICE:  1549444\",\"AREA_SQM: 111<br />SELLING_PRICE:  1234000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1270000\",\"AREA_SQM: 135<br />SELLING_PRICE:  1360000\",\"AREA_SQM:  90<br />SELLING_PRICE:   892500\",\"AREA_SQM:  90<br />SELLING_PRICE:  1214000\",\"AREA_SQM: 222<br />SELLING_PRICE:  3240000\",\"AREA_SQM: 167<br />SELLING_PRICE:  3800000\",\"AREA_SQM: 130<br />SELLING_PRICE:  3874000\",\"AREA_SQM: 131<br />SELLING_PRICE:  1107500\",\"AREA_SQM: 270<br />SELLING_PRICE:  1427500\",\"AREA_SQM: 134<br />SELLING_PRICE:  1950000\",\"AREA_SQM: 165<br />SELLING_PRICE:  2425000\",\"AREA_SQM: 197<br />SELLING_PRICE:  2950000\",\"AREA_SQM: 113<br />SELLING_PRICE:   985000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 125<br />SELLING_PRICE:  2750000\",\"AREA_SQM: 182<br />SELLING_PRICE:  4050000\",\"AREA_SQM:  81<br />SELLING_PRICE:  1620000\",\"AREA_SQM: 191<br />SELLING_PRICE:  2501000\",\"AREA_SQM: 137<br />SELLING_PRICE:  2458800\",\"AREA_SQM: 136<br />SELLING_PRICE:  2230000\",\"AREA_SQM: 139<br />SELLING_PRICE:  2550000\",\"AREA_SQM: 124<br />SELLING_PRICE:  4840000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1560000\",\"AREA_SQM: 111<br />SELLING_PRICE:  1465000\",\"AREA_SQM:  88<br />SELLING_PRICE:  1315000\",\"AREA_SQM: 128<br />SELLING_PRICE:  1980000\",\"AREA_SQM: 125<br />SELLING_PRICE:  1850000\",\"AREA_SQM: 139<br />SELLING_PRICE:  2095000\",\"AREA_SQM: 140<br />SELLING_PRICE:  2125000\",\"AREA_SQM: 125<br />SELLING_PRICE:  1267600\",\"AREA_SQM: 142<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 160<br />SELLING_PRICE:  1498888\",\"AREA_SQM: 155<br />SELLING_PRICE:  1535000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1309888\",\"AREA_SQM: 116<br />SELLING_PRICE:  1440000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1367500\",\"AREA_SQM:  80<br />SELLING_PRICE:  1802500\",\"AREA_SQM:  92<br />SELLING_PRICE:  1900000\",\"AREA_SQM: 185<br />SELLING_PRICE:  3900000\",\"AREA_SQM:  92<br />SELLING_PRICE:  3100000\",\"AREA_SQM: 159<br />SELLING_PRICE:  3455000\",\"AREA_SQM: 184<br />SELLING_PRICE:  3219444\",\"AREA_SQM: 112<br />SELLING_PRICE:  1794000\",\"AREA_SQM: 141<br />SELLING_PRICE:  1175000\",\"AREA_SQM: 183<br />SELLING_PRICE:  1250000\",\"AREA_SQM: 191<br />SELLING_PRICE:  1438000\",\"AREA_SQM: 150<br />SELLING_PRICE:  1042500\",\"AREA_SQM: 114<br />SELLING_PRICE:  2290000\",\"AREA_SQM: 244<br />SELLING_PRICE:  3850000\",\"AREA_SQM: 188<br />SELLING_PRICE:  3550000\",\"AREA_SQM: 219<br />SELLING_PRICE:  3227500\",\"AREA_SQM:  93<br />SELLING_PRICE:  1935000\",\"AREA_SQM: 169<br />SELLING_PRICE:  3800000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1160000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1145000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1205500\",\"AREA_SQM: 144<br />SELLING_PRICE:  1490000\",\"AREA_SQM:  87<br />SELLING_PRICE:  1758000\",\"AREA_SQM: 162<br />SELLING_PRICE:  2185000\",\"AREA_SQM: 147<br />SELLING_PRICE:  2030000\",\"AREA_SQM: 101<br />SELLING_PRICE:  1345000\",\"AREA_SQM: 175<br />SELLING_PRICE:  2200000\",\"AREA_SQM: 127<br />SELLING_PRICE:  1730000\",\"AREA_SQM: 171<br />SELLING_PRICE:  1950000\",\"AREA_SQM: 189<br />SELLING_PRICE:  1210000\",\"AREA_SQM: 119<br />SELLING_PRICE:   940000\",\"AREA_SQM: 135<br />SELLING_PRICE:  1035000\",\"AREA_SQM: 131<br />SELLING_PRICE:  1292500\",\"AREA_SQM:  86<br />SELLING_PRICE:  1070000\",\"AREA_SQM:  89<br />SELLING_PRICE:  1250000\",\"AREA_SQM: 113<br />SELLING_PRICE:   990000\",\"AREA_SQM:  93<br />SELLING_PRICE:   960000\",\"AREA_SQM:  84<br />SELLING_PRICE:  1347500\",\"AREA_SQM: 259<br />SELLING_PRICE:  4590000\",\"AREA_SQM: 193<br />SELLING_PRICE:  3500000\",\"AREA_SQM: 176<br />SELLING_PRICE:  2698000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1850000\",\"AREA_SQM:  83<br />SELLING_PRICE:  2350000\",\"AREA_SQM: 179<br />SELLING_PRICE:  2150000\",\"AREA_SQM: 184<br />SELLING_PRICE:  2030000\",\"AREA_SQM:  77<br />SELLING_PRICE:  1690000\",\"AREA_SQM: 140<br />SELLING_PRICE:  1240000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1220000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1210000\",\"AREA_SQM: 183<br />SELLING_PRICE:  2000000\",\"AREA_SQM: 167<br />SELLING_PRICE:  1512500\",\"AREA_SQM: 159<br />SELLING_PRICE:  1630000\",\"AREA_SQM: 159<br />SELLING_PRICE:  1680000\",\"AREA_SQM: 262<br />SELLING_PRICE:  4577500\",\"AREA_SQM: 211<br />SELLING_PRICE:  3550000\",\"AREA_SQM: 172<br />SELLING_PRICE:  2920000\",\"AREA_SQM:  96<br />SELLING_PRICE:  1990000\",\"AREA_SQM: 124<br />SELLING_PRICE:  2400000\",\"AREA_SQM:  95<br />SELLING_PRICE:  1825000\",\"AREA_SQM:  92<br />SELLING_PRICE:  1613700\",\"AREA_SQM: 139<br />SELLING_PRICE:  2125000\",\"AREA_SQM:  99<br />SELLING_PRICE:  1705000\",\"AREA_SQM: 122<br />SELLING_PRICE:  2039888\",\"AREA_SQM:  76<br />SELLING_PRICE:   869800\",\"AREA_SQM:  75<br />SELLING_PRICE:   850000\",\"AREA_SQM: 154<br />SELLING_PRICE:  3103000\",\"AREA_SQM:  93<br />SELLING_PRICE:  2030000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1380000\",\"AREA_SQM: 151<br />SELLING_PRICE:  1615000\",\"AREA_SQM: 158<br />SELLING_PRICE:  1630000\",\"AREA_SQM:  95<br />SELLING_PRICE:  1240000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1542500\",\"AREA_SQM: 137<br />SELLING_PRICE:  1275000\",\"AREA_SQM:  94<br />SELLING_PRICE:  1145000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1390000\",\"AREA_SQM: 224<br />SELLING_PRICE:  1281500\",\"AREA_SQM: 211<br />SELLING_PRICE:  1570000\",\"AREA_SQM: 224<br />SELLING_PRICE:  1550000\",\"AREA_SQM:  84<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1800000\",\"AREA_SQM: 149<br />SELLING_PRICE:  1140000\",\"AREA_SQM: 111<br />SELLING_PRICE:   984000\",\"AREA_SQM:  88<br />SELLING_PRICE:   840000\",\"AREA_SQM: 319<br />SELLING_PRICE:  6500000\",\"AREA_SQM: 202<br />SELLING_PRICE:  3025000\",\"AREA_SQM: 196<br />SELLING_PRICE:  2875000\",\"AREA_SQM:  94<br />SELLING_PRICE:  1877500\",\"AREA_SQM: 146<br />SELLING_PRICE:  1820000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1330000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1160000\",\"AREA_SQM: 153<br />SELLING_PRICE:  1330000\",\"AREA_SQM: 153<br />SELLING_PRICE:  1380000\",\"AREA_SQM: 295<br />SELLING_PRICE:  5375000\",\"AREA_SQM: 210<br />SELLING_PRICE:  3900000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1200000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1510000\",\"AREA_SQM:  51<br />SELLING_PRICE:  1045000\",\"AREA_SQM:  93<br />SELLING_PRICE:  1660000\",\"AREA_SQM:  55<br />SELLING_PRICE:  1900000\",\"AREA_SQM:  84<br />SELLING_PRICE:  1535000\",\"AREA_SQM:  84<br />SELLING_PRICE:  1638000\",\"AREA_SQM: 189<br />SELLING_PRICE:  1375000\",\"AREA_SQM:  78<br />SELLING_PRICE:   863000\",\"AREA_SQM: 196<br />SELLING_PRICE:  2325000\",\"AREA_SQM: 196<br />SELLING_PRICE:  2125000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1075000\",\"AREA_SQM: 120<br />SELLING_PRICE:   950000\",\"AREA_SQM: 104<br />SELLING_PRICE:   815000\",\"AREA_SQM:  99<br />SELLING_PRICE:  1127500\",\"AREA_SQM: 115<br />SELLING_PRICE:  1200000\",\"AREA_SQM:  87<br />SELLING_PRICE:  1265000\",\"AREA_SQM:  55<br />SELLING_PRICE:  1311200\",\"AREA_SQM: 160<br />SELLING_PRICE:  3605000\",\"AREA_SQM: 206<br />SELLING_PRICE:  1190000\",\"AREA_SQM:  93<br />SELLING_PRICE:  1180000\",\"AREA_SQM: 170<br />SELLING_PRICE:  1030000\",\"AREA_SQM: 110<br />SELLING_PRICE:   823000\",\"AREA_SQM: 108<br />SELLING_PRICE:   800000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1320444\",\"AREA_SQM: 110<br />SELLING_PRICE:   792500\",\"AREA_SQM: 106<br />SELLING_PRICE:   808000\",\"AREA_SQM:  67<br />SELLING_PRICE:   900000\",\"AREA_SQM:  83<br />SELLING_PRICE:  1160000\",\"AREA_SQM:  93<br />SELLING_PRICE:  1064000\",\"AREA_SQM:  99<br />SELLING_PRICE:  1150000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1615000\",\"AREA_SQM:  91<br />SELLING_PRICE:  1830000\",\"AREA_SQM:  96<br />SELLING_PRICE:  2272500\",\"AREA_SQM: 128<br />SELLING_PRICE:  2080000\",\"AREA_SQM:  85<br />SELLING_PRICE:  1395000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1150000\",\"AREA_SQM:  84<br />SELLING_PRICE:   990000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1356444\",\"AREA_SQM: 127<br />SELLING_PRICE:  1400000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1215000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1192500\",\"AREA_SQM: 122<br />SELLING_PRICE:  1280000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1295000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1295000\",\"AREA_SQM:  88<br />SELLING_PRICE:  1145000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1204000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1255000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1010000\",\"AREA_SQM: 140<br />SELLING_PRICE:  1100000\",\"AREA_SQM: 140<br />SELLING_PRICE:  1273000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1025000\",\"AREA_SQM: 140<br />SELLING_PRICE:  1150000\",\"AREA_SQM: 154<br />SELLING_PRICE:  1785500\",\"AREA_SQM: 116<br />SELLING_PRICE:  1540000\",\"AREA_SQM:  76<br />SELLING_PRICE:  1388000\",\"AREA_SQM:  81<br />SELLING_PRICE:  1005000\",\"AREA_SQM: 105<br />SELLING_PRICE:  1425000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1530000\",\"AREA_SQM: 134<br />SELLING_PRICE:  1500000\",\"AREA_SQM: 105<br />SELLING_PRICE:  1406500\",\"AREA_SQM:  80<br />SELLING_PRICE:  1100000\",\"AREA_SQM:  81<br />SELLING_PRICE:   770000\",\"AREA_SQM:  83<br />SELLING_PRICE:   780000\",\"AREA_SQM:  79<br />SELLING_PRICE:   782500\",\"AREA_SQM:  83<br />SELLING_PRICE:   840000\",\"AREA_SQM:  57<br />SELLING_PRICE:   660000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1000000\",\"AREA_SQM:  57<br />SELLING_PRICE:   660000\",\"AREA_SQM: 143<br />SELLING_PRICE:  1210000\",\"AREA_SQM:  57<br />SELLING_PRICE:   682500\",\"AREA_SQM:  79<br />SELLING_PRICE:   888000\",\"AREA_SQM:  57<br />SELLING_PRICE:   667500\",\"AREA_SQM:  82<br />SELLING_PRICE:   818000\",\"AREA_SQM: 100<br />SELLING_PRICE:   950000\",\"AREA_SQM:  57<br />SELLING_PRICE:   675000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1160000\",\"AREA_SQM: 142<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 141<br />SELLING_PRICE:  1388000\",\"AREA_SQM:  89<br />SELLING_PRICE:  1089000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1295944\",\"AREA_SQM:  94<br />SELLING_PRICE:  1700000\",\"AREA_SQM: 166<br />SELLING_PRICE:  2202500\",\"AREA_SQM: 213<br />SELLING_PRICE:  2950000\",\"AREA_SQM: 149<br />SELLING_PRICE:  2590000\",\"AREA_SQM: 194<br />SELLING_PRICE:  2070000\",\"AREA_SQM: 152<br />SELLING_PRICE:  1000000\",\"AREA_SQM: 104<br />SELLING_PRICE:   770000\",\"AREA_SQM: 132<br />SELLING_PRICE:   968000\",\"AREA_SQM:  84<br />SELLING_PRICE:   850000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1160000\",\"AREA_SQM: 139<br />SELLING_PRICE:  1360000\",\"AREA_SQM: 125<br />SELLING_PRICE:  1291500\",\"AREA_SQM:  81<br />SELLING_PRICE:  1238000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1080000\",\"AREA_SQM: 152<br />SELLING_PRICE:  1600000\",\"AREA_SQM:  64<br />SELLING_PRICE:   760000\",\"AREA_SQM:  97<br />SELLING_PRICE:   929000\",\"AREA_SQM:  37<br />SELLING_PRICE:   655000\",\"AREA_SQM: 102<br />SELLING_PRICE:  1330000\",\"AREA_SQM: 268<br />SELLING_PRICE:  8300000\",\"AREA_SQM: 268<br />SELLING_PRICE:  8450000\",\"AREA_SQM:  90<br />SELLING_PRICE:  1620000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1545000\",\"AREA_SQM: 170<br />SELLING_PRICE:  3000000\",\"AREA_SQM: 154<br />SELLING_PRICE:  2742500\",\"AREA_SQM: 142<br />SELLING_PRICE:  1825000\",\"AREA_SQM:  58<br />SELLING_PRICE:   690000\",\"AREA_SQM:  79<br />SELLING_PRICE:   870000\",\"AREA_SQM:  82<br />SELLING_PRICE:  1038888\",\"AREA_SQM:  88<br />SELLING_PRICE:  1150000\",\"AREA_SQM: 193<br />SELLING_PRICE:  1705000\",\"AREA_SQM: 192<br />SELLING_PRICE:  2400000\",\"AREA_SQM: 130<br />SELLING_PRICE:  1670000\",\"AREA_SQM:  88<br />SELLING_PRICE:  1125000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1380000\",\"AREA_SQM: 142<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1388000\",\"AREA_SQM: 192<br />SELLING_PRICE:  1230000\",\"AREA_SQM: 192<br />SELLING_PRICE:  1317500\",\"AREA_SQM: 121<br />SELLING_PRICE:   945000\",\"AREA_SQM: 145<br />SELLING_PRICE:  1100000\",\"AREA_SQM: 121<br />SELLING_PRICE:   902500\",\"AREA_SQM: 192<br />SELLING_PRICE:  1300000\",\"AREA_SQM: 171<br />SELLING_PRICE:  1818000\",\"AREA_SQM: 274<br />SELLING_PRICE:  1900000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1380000\",\"AREA_SQM: 163<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 149<br />SELLING_PRICE:  1250000\",\"AREA_SQM: 170<br />SELLING_PRICE:  2530000\",\"AREA_SQM: 176<br />SELLING_PRICE:  2528000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1630000\",\"AREA_SQM:  87<br />SELLING_PRICE:   965000\",\"AREA_SQM: 170<br />SELLING_PRICE:  1120000\",\"AREA_SQM: 170<br />SELLING_PRICE:  1310000\",\"AREA_SQM: 106<br />SELLING_PRICE:   900000\",\"AREA_SQM:  58<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 109<br />SELLING_PRICE:  1050000\",\"AREA_SQM:  93<br />SELLING_PRICE:   980000\",\"AREA_SQM:  79<br />SELLING_PRICE:   900000\",\"AREA_SQM: 100<br />SELLING_PRICE:  1220000\",\"AREA_SQM: 100<br />SELLING_PRICE:  1200000\",\"AREA_SQM: 130<br />SELLING_PRICE:  1700000\",\"AREA_SQM: 144<br />SELLING_PRICE:  1850000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1019444\",\"AREA_SQM: 162<br />SELLING_PRICE:  1449000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1025000\",\"AREA_SQM: 194<br />SELLING_PRICE:  1625000\",\"AREA_SQM: 135<br />SELLING_PRICE:  1225000\",\"AREA_SQM: 146<br />SELLING_PRICE:  1300000\",\"AREA_SQM: 194<br />SELLING_PRICE:  1648000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1495000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1300000\",\"AREA_SQM:  91<br />SELLING_PRICE:  1284000\",\"AREA_SQM: 177<br />SELLING_PRICE:  1190000\",\"AREA_SQM: 142<br />SELLING_PRICE:   930000\",\"AREA_SQM: 174<br />SELLING_PRICE:  1180000\",\"AREA_SQM: 174<br />SELLING_PRICE:  1490000\",\"AREA_SQM: 132<br />SELLING_PRICE:   992500\",\"AREA_SQM: 119<br />SELLING_PRICE:   860000\",\"AREA_SQM: 119<br />SELLING_PRICE:   940000\",\"AREA_SQM: 134<br />SELLING_PRICE:   950000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1730000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1204000\",\"AREA_SQM: 146<br />SELLING_PRICE:  1363000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1150000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1355000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1197500\",\"AREA_SQM: 121<br />SELLING_PRICE:  1282500\",\"AREA_SQM: 143<br />SELLING_PRICE:  1525000\",\"AREA_SQM:  94<br />SELLING_PRICE:  1620000\",\"AREA_SQM: 172<br />SELLING_PRICE:  2662500\",\"AREA_SQM: 110<br />SELLING_PRICE:   795000\",\"AREA_SQM:  93<br />SELLING_PRICE:   768000\",\"AREA_SQM: 133<br />SELLING_PRICE:   910000\",\"AREA_SQM: 110<br />SELLING_PRICE:   888888\",\"AREA_SQM:  72<br />SELLING_PRICE:  1125000\",\"AREA_SQM: 300<br />SELLING_PRICE:  2100000\",\"AREA_SQM:  91<br />SELLING_PRICE:  1580000\",\"AREA_SQM: 138<br />SELLING_PRICE:  2430000\",\"AREA_SQM: 229<br />SELLING_PRICE:  3550000\",\"AREA_SQM: 138<br />SELLING_PRICE:  2300000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1398888\",\"AREA_SQM: 108<br />SELLING_PRICE:  1340000\",\"AREA_SQM:  81<br />SELLING_PRICE:  1329000\",\"AREA_SQM: 138<br />SELLING_PRICE:  1233800\",\"AREA_SQM: 202<br />SELLING_PRICE:  2930000\",\"AREA_SQM:  91<br />SELLING_PRICE:   880000\",\"AREA_SQM:  91<br />SELLING_PRICE:   884000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1100000\",\"AREA_SQM: 145<br />SELLING_PRICE:  2005000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1480000\",\"AREA_SQM: 145<br />SELLING_PRICE:  1920000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1730000\",\"AREA_SQM: 132<br />SELLING_PRICE:  1824000\",\"AREA_SQM: 151<br />SELLING_PRICE:  1950000\",\"AREA_SQM: 103<br />SELLING_PRICE:  1130000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1128000\",\"AREA_SQM: 143<br />SELLING_PRICE:  1340000\",\"AREA_SQM: 239<br />SELLING_PRICE:  3093000\",\"AREA_SQM:  77<br />SELLING_PRICE:  1238000\",\"AREA_SQM: 207<br />SELLING_PRICE:  2420000\",\"AREA_SQM: 345<br />SELLING_PRICE:  1650000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1720000\",\"AREA_SQM: 345<br />SELLING_PRICE:  2335000\",\"AREA_SQM:  85<br />SELLING_PRICE:  1125000\",\"AREA_SQM:  45<br />SELLING_PRICE:   734000\",\"AREA_SQM: 131<br />SELLING_PRICE:  2100000\",\"AREA_SQM: 137<br />SELLING_PRICE:  2060000\",\"AREA_SQM: 130<br />SELLING_PRICE:  2140000\",\"AREA_SQM: 131<br />SELLING_PRICE:  1879000\",\"AREA_SQM: 159<br />SELLING_PRICE:  2141115\",\"AREA_SQM: 142<br />SELLING_PRICE:  1339000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1231000\",\"AREA_SQM:  91<br />SELLING_PRICE:   955000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1270000\",\"AREA_SQM: 149<br />SELLING_PRICE:  1780000\",\"AREA_SQM:  88<br />SELLING_PRICE:  1038888\",\"AREA_SQM: 117<br />SELLING_PRICE:  1307500\",\"AREA_SQM:  83<br />SELLING_PRICE:  1378000\",\"AREA_SQM: 140<br />SELLING_PRICE:  2075000\",\"AREA_SQM:  55<br />SELLING_PRICE:  1311000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1480000\",\"AREA_SQM:  93<br />SELLING_PRICE:   910000\",\"AREA_SQM:  55<br />SELLING_PRICE:   594500\",\"AREA_SQM:  85<br />SELLING_PRICE:  1670000\",\"AREA_SQM: 196<br />SELLING_PRICE:  2021440\",\"AREA_SQM:  89<br />SELLING_PRICE:  1668000\",\"AREA_SQM:  54<br />SELLING_PRICE:  2440000\",\"AREA_SQM: 150<br />SELLING_PRICE:   940000\",\"AREA_SQM: 144<br />SELLING_PRICE:  1035000\",\"AREA_SQM: 140<br />SELLING_PRICE:   898400\",\"AREA_SQM: 140<br />SELLING_PRICE:   900000\",\"AREA_SQM: 140<br />SELLING_PRICE:   860000\",\"AREA_SQM: 128<br />SELLING_PRICE:  1150000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1125000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1360000\",\"AREA_SQM: 100<br />SELLING_PRICE:  1430000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1438000\",\"AREA_SQM: 134<br />SELLING_PRICE:  1700000\",\"AREA_SQM: 152<br />SELLING_PRICE:  3970000\",\"AREA_SQM: 179<br />SELLING_PRICE:  1305000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1255000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1160000\",\"AREA_SQM: 271<br />SELLING_PRICE:  1335000\",\"AREA_SQM: 215<br />SELLING_PRICE:  1267500\",\"AREA_SQM: 116<br />SELLING_PRICE:  1145000\",\"AREA_SQM: 188<br />SELLING_PRICE:  1540000\",\"AREA_SQM: 105<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 176<br />SELLING_PRICE:  1320000\",\"AREA_SQM: 176<br />SELLING_PRICE:  1330000\",\"AREA_SQM: 116<br />SELLING_PRICE:   970000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1020000\",\"AREA_SQM: 116<br />SELLING_PRICE:   982500\",\"AREA_SQM: 126<br />SELLING_PRICE:   968000\",\"AREA_SQM:  93<br />SELLING_PRICE:   760000\",\"AREA_SQM: 130<br />SELLING_PRICE:  1030000\",\"AREA_SQM: 113<br />SELLING_PRICE:   880000\",\"AREA_SQM: 112<br />SELLING_PRICE:   870000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1475000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1600000\",\"AREA_SQM:  90<br />SELLING_PRICE:  1355000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1225000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1530000\",\"AREA_SQM: 145<br />SELLING_PRICE:  1838888\",\"AREA_SQM: 114<br />SELLING_PRICE:  1570000\",\"AREA_SQM:  84<br />SELLING_PRICE:  1165000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1660000\",\"AREA_SQM:  95<br />SELLING_PRICE:   862500\",\"AREA_SQM: 110<br />SELLING_PRICE:   923000\",\"AREA_SQM: 110<br />SELLING_PRICE:   937500\",\"AREA_SQM: 132<br />SELLING_PRICE:  1277500\",\"AREA_SQM: 137<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 109<br />SELLING_PRICE:   900000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1930000\",\"AREA_SQM:  89<br />SELLING_PRICE:  2105000\",\"AREA_SQM: 127<br />SELLING_PRICE:  1790000\",\"AREA_SQM:  92<br />SELLING_PRICE:  1990000\",\"AREA_SQM: 149<br />SELLING_PRICE:  1850000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1200888\",\"AREA_SQM: 155<br />SELLING_PRICE:  1590000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1230000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1230000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1293000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1100000\",\"AREA_SQM:  92<br />SELLING_PRICE:   990000\",\"AREA_SQM:  81<br />SELLING_PRICE:   960000\",\"AREA_SQM:  66<br />SELLING_PRICE:  1150000\",\"AREA_SQM:  81<br />SELLING_PRICE:   940000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1105000\",\"AREA_SQM: 109<br />SELLING_PRICE:   985000\",\"AREA_SQM: 110<br />SELLING_PRICE:   985000\",\"AREA_SQM:  83<br />SELLING_PRICE:   900000\",\"AREA_SQM: 109<br />SELLING_PRICE:  1141344\",\"AREA_SQM: 109<br />SELLING_PRICE:  1085000\",\"AREA_SQM:  66<br />SELLING_PRICE:   750000\",\"AREA_SQM: 139<br />SELLING_PRICE:  1230000\",\"AREA_SQM: 172<br />SELLING_PRICE:  1608000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1180000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1300444\",\"AREA_SQM:  99<br />SELLING_PRICE:  1040000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1307500\",\"AREA_SQM: 127<br />SELLING_PRICE:  1225000\",\"AREA_SQM: 116<br />SELLING_PRICE:   995000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1265000\",\"AREA_SQM:  87<br />SELLING_PRICE:  1020000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1930000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1938000\",\"AREA_SQM: 181<br />SELLING_PRICE:  2850000\",\"AREA_SQM: 217<br />SELLING_PRICE:  3050000\",\"AREA_SQM: 216<br />SELLING_PRICE:  2938000\",\"AREA_SQM: 104<br />SELLING_PRICE:   950000\",\"AREA_SQM: 127<br />SELLING_PRICE:  1200000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1100000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1124000\",\"AREA_SQM: 104<br />SELLING_PRICE:   950000\",\"AREA_SQM: 184<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 149<br />SELLING_PRICE:  1650000\",\"AREA_SQM: 137<br />SELLING_PRICE:  1375000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1360000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1375000\",\"AREA_SQM:  98<br />SELLING_PRICE:  3268000\",\"AREA_SQM: 209<br />SELLING_PRICE:  2405000\",\"AREA_SQM: 162<br />SELLING_PRICE:  2150000\",\"AREA_SQM: 160<br />SELLING_PRICE:  2150000\",\"AREA_SQM: 162<br />SELLING_PRICE:  2120000\",\"AREA_SQM: 159<br />SELLING_PRICE:  1485000\",\"AREA_SQM:  95<br />SELLING_PRICE:   908000\",\"AREA_SQM: 111<br />SELLING_PRICE:  1085000\",\"AREA_SQM: 111<br />SELLING_PRICE:  1130000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1160000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1110000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1130000\",\"AREA_SQM: 128<br />SELLING_PRICE:  1189998\",\"AREA_SQM: 126<br />SELLING_PRICE:  1150000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1033000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1230000\",\"AREA_SQM: 174<br />SELLING_PRICE:  1505000\",\"AREA_SQM:  75<br />SELLING_PRICE:  1065000\",\"AREA_SQM:  75<br />SELLING_PRICE:   830000\",\"AREA_SQM:  82<br />SELLING_PRICE:   870000\",\"AREA_SQM:  54<br />SELLING_PRICE:   642888\",\"AREA_SQM: 103<br />SELLING_PRICE:  1230000\",\"AREA_SQM: 103<br />SELLING_PRICE:  1150000\",\"AREA_SQM:  55<br />SELLING_PRICE:   660000\",\"AREA_SQM:  75<br />SELLING_PRICE:   733888\",\"AREA_SQM:  95<br />SELLING_PRICE:  1132500\",\"AREA_SQM:  78<br />SELLING_PRICE:  1050000\",\"AREA_SQM:  75<br />SELLING_PRICE:  1000000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1220000\",\"AREA_SQM:  97<br />SELLING_PRICE:  1458500\",\"AREA_SQM:  80<br />SELLING_PRICE:  1060000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1179000\",\"AREA_SQM: 198<br />SELLING_PRICE:  2250000\",\"AREA_SQM: 141<br />SELLING_PRICE:  1430000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1456000\",\"AREA_SQM: 154<br />SELLING_PRICE:  1680000\",\"AREA_SQM: 199<br />SELLING_PRICE:  2200000\",\"AREA_SQM: 146<br />SELLING_PRICE:  1642000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1018500\",\"AREA_SQM:  87<br />SELLING_PRICE:   819000\",\"AREA_SQM: 103<br />SELLING_PRICE:   960000\",\"AREA_SQM: 141<br />SELLING_PRICE:  1718600\",\"AREA_SQM: 172<br />SELLING_PRICE:  1792500\",\"AREA_SQM:  59<br />SELLING_PRICE:  1300000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1219000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1188888\",\"AREA_SQM: 103<br />SELLING_PRICE:  1055000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1290000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1350000\",\"AREA_SQM:  92<br />SELLING_PRICE:  1257500\",\"AREA_SQM: 112<br />SELLING_PRICE:  1116000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1210000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1070000\",\"AREA_SQM: 134<br />SELLING_PRICE:  2380000\",\"AREA_SQM: 186<br />SELLING_PRICE:  3500000\",\"AREA_SQM: 105<br />SELLING_PRICE:  2630000\",\"AREA_SQM: 124<br />SELLING_PRICE:  2140000\",\"AREA_SQM: 221<br />SELLING_PRICE:  1965000\",\"AREA_SQM: 174<br />SELLING_PRICE:  1995000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1135000\",\"AREA_SQM:  73<br />SELLING_PRICE:  1052500\",\"AREA_SQM:  79<br />SELLING_PRICE:  1230000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1690000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1465000\",\"AREA_SQM: 147<br />SELLING_PRICE:  1750000\",\"AREA_SQM: 149<br />SELLING_PRICE:  1717100\",\"AREA_SQM: 250<br />SELLING_PRICE:  2350000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1929400\",\"AREA_SQM: 118<br />SELLING_PRICE:  1520000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1420000\",\"AREA_SQM: 152<br />SELLING_PRICE:  1530000\",\"AREA_SQM:  62<br />SELLING_PRICE:   730000\",\"AREA_SQM: 110<br />SELLING_PRICE:  1358888\",\"AREA_SQM: 110<br />SELLING_PRICE:  1320000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1445260\",\"AREA_SQM:  43<br />SELLING_PRICE:   635000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1115000\",\"AREA_SQM: 141<br />SELLING_PRICE:  1460000\",\"AREA_SQM:  85<br />SELLING_PRICE:  1270000\",\"AREA_SQM: 224<br />SELLING_PRICE:  3105000\",\"AREA_SQM: 199<br />SELLING_PRICE:  2855000\",\"AREA_SQM: 199<br />SELLING_PRICE:  3172500\",\"AREA_SQM:  86<br />SELLING_PRICE:  1688800\",\"AREA_SQM: 147<br />SELLING_PRICE:  2120000\",\"AREA_SQM: 153<br />SELLING_PRICE:  1950000\",\"AREA_SQM: 108<br />SELLING_PRICE:  2173480\",\"AREA_SQM: 163<br />SELLING_PRICE:  2672235\",\"AREA_SQM: 256<br />SELLING_PRICE:  2855000\",\"AREA_SQM: 244<br />SELLING_PRICE:  3720000\",\"AREA_SQM: 284<br />SELLING_PRICE:  4120000\",\"AREA_SQM: 206<br />SELLING_PRICE:  3675000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1080000\",\"AREA_SQM:  98<br />SELLING_PRICE:   875000\",\"AREA_SQM:  77<br />SELLING_PRICE:   800000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1048000\",\"AREA_SQM: 297<br />SELLING_PRICE:  1635000\",\"AREA_SQM:  95<br />SELLING_PRICE:   880000\",\"AREA_SQM: 297<br />SELLING_PRICE:  2000000\",\"AREA_SQM: 138<br />SELLING_PRICE:  1468000\",\"AREA_SQM: 249<br />SELLING_PRICE:  1940000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1315000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1390000\",\"AREA_SQM:  92<br />SELLING_PRICE:   962500\",\"AREA_SQM: 124<br />SELLING_PRICE:  1260000\",\"AREA_SQM: 164<br />SELLING_PRICE:  2075000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1724000\",\"AREA_SQM: 173<br />SELLING_PRICE:  1950000\",\"AREA_SQM: 167<br />SELLING_PRICE:  2062000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1420000\",\"AREA_SQM:  82<br />SELLING_PRICE:  1100000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1442500\",\"AREA_SQM:  83<br />SELLING_PRICE:  1120000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1288888\",\"AREA_SQM: 107<br />SELLING_PRICE:  1465000\",\"AREA_SQM:  77<br />SELLING_PRICE:  1057500\",\"AREA_SQM: 113<br />SELLING_PRICE:  1680000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1500000\",\"AREA_SQM: 142<br />SELLING_PRICE:  1490000\",\"AREA_SQM:  92<br />SELLING_PRICE:  1040000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1250000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1367500\",\"AREA_SQM:  92<br />SELLING_PRICE:  1252500\",\"AREA_SQM: 163<br />SELLING_PRICE:  1738444\",\"AREA_SQM:  91<br />SELLING_PRICE:   920000\",\"AREA_SQM: 142<br />SELLING_PRICE:  1400000\",\"AREA_SQM: 142<br />SELLING_PRICE:  1040000\",\"AREA_SQM:  91<br />SELLING_PRICE:   930000\",\"AREA_SQM:  90<br />SELLING_PRICE:   860000\",\"AREA_SQM:  99<br />SELLING_PRICE:  1255000\",\"AREA_SQM: 137<br />SELLING_PRICE:  1760000\",\"AREA_SQM: 135<br />SELLING_PRICE:  1680000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1745000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1840000\",\"AREA_SQM: 211<br />SELLING_PRICE:  1880000\",\"AREA_SQM: 169<br />SELLING_PRICE:  2170900\",\"AREA_SQM: 162<br />SELLING_PRICE:  1600000\",\"AREA_SQM: 178<br />SELLING_PRICE:  1850000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1430000\",\"AREA_SQM:  82<br />SELLING_PRICE:  1360000\",\"AREA_SQM: 162<br />SELLING_PRICE:  1600000\",\"AREA_SQM: 183<br />SELLING_PRICE:  1720000\",\"AREA_SQM:  54<br />SELLING_PRICE:  1045000\",\"AREA_SQM: 140<br />SELLING_PRICE:  1430000\",\"AREA_SQM: 156<br />SELLING_PRICE:  1710000\",\"AREA_SQM: 115<br />SELLING_PRICE:   970000\",\"AREA_SQM: 114<br />SELLING_PRICE:   988000\",\"AREA_SQM: 139<br />SELLING_PRICE:  1108000\",\"AREA_SQM:  92<br />SELLING_PRICE:   828000\",\"AREA_SQM:  92<br />SELLING_PRICE:   815000\",\"AREA_SQM: 114<br />SELLING_PRICE:   970000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1038000\",\"AREA_SQM: 153<br />SELLING_PRICE:  2620000\",\"AREA_SQM: 113<br />SELLING_PRICE:  2065000\",\"AREA_SQM: 153<br />SELLING_PRICE:  2610084\",\"AREA_SQM: 131<br />SELLING_PRICE:  2280000\",\"AREA_SQM:  52<br />SELLING_PRICE:  1679000\",\"AREA_SQM: 141<br />SELLING_PRICE:  2640000\",\"AREA_SQM: 108<br />SELLING_PRICE:   830000\",\"AREA_SQM: 108<br />SELLING_PRICE:   849000\",\"AREA_SQM: 117<br />SELLING_PRICE:   928000\",\"AREA_SQM: 158<br />SELLING_PRICE:   840000\",\"AREA_SQM: 158<br />SELLING_PRICE:   950000\",\"AREA_SQM: 156<br />SELLING_PRICE:   906500\",\"AREA_SQM: 154<br />SELLING_PRICE:   890000\",\"AREA_SQM: 155<br />SELLING_PRICE:   875000\",\"AREA_SQM: 157<br />SELLING_PRICE:   920500\",\"AREA_SQM: 160<br />SELLING_PRICE:   872500\",\"AREA_SQM: 135<br />SELLING_PRICE:  1900000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1797500\",\"AREA_SQM: 121<br />SELLING_PRICE:  2260000\",\"AREA_SQM: 123<br />SELLING_PRICE:  2130000\",\"AREA_SQM: 103<br />SELLING_PRICE:   955000\",\"AREA_SQM:  84<br />SELLING_PRICE:   920000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1207500\",\"AREA_SQM: 132<br />SELLING_PRICE:  1450000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1230000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1168000\",\"AREA_SQM: 132<br />SELLING_PRICE:  1405000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1225000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1212544\",\"AREA_SQM: 114<br />SELLING_PRICE:  1290000\",\"AREA_SQM: 105<br />SELLING_PRICE:  1388444\",\"AREA_SQM: 168<br />SELLING_PRICE:  1635000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1590000\",\"AREA_SQM: 154<br />SELLING_PRICE:  1380000\",\"AREA_SQM: 154<br />SELLING_PRICE:  1395000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1202500\",\"AREA_SQM: 154<br />SELLING_PRICE:  1400000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1300000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1219000\",\"AREA_SQM: 154<br />SELLING_PRICE:  1520000\",\"AREA_SQM: 154<br />SELLING_PRICE:  1408000\",\"AREA_SQM: 105<br />SELLING_PRICE:   890000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1065000\",\"AREA_SQM: 139<br />SELLING_PRICE:  1705000\",\"AREA_SQM: 117<br />SELLING_PRICE:   860000\",\"AREA_SQM: 119<br />SELLING_PRICE:   980000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1057500\",\"AREA_SQM: 117<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 137<br />SELLING_PRICE:  1100000\",\"AREA_SQM: 299<br />SELLING_PRICE:  3050000\",\"AREA_SQM:  86<br />SELLING_PRICE:  1395000\",\"AREA_SQM:  63<br />SELLING_PRICE:  1155000\",\"AREA_SQM:  63<br />SELLING_PRICE:  1125000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1900000\",\"AREA_SQM:  82<br />SELLING_PRICE:  2085444\",\"AREA_SQM: 123<br />SELLING_PRICE:  1952900\",\"AREA_SQM:  55<br />SELLING_PRICE:   700000\",\"AREA_SQM: 104<br />SELLING_PRICE:   965000\",\"AREA_SQM:  86<br />SELLING_PRICE:   908000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1119000\",\"AREA_SQM: 142<br />SELLING_PRICE:  1320000\",\"AREA_SQM:  93<br />SELLING_PRICE:   940000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1320000\",\"AREA_SQM: 161<br />SELLING_PRICE:  1019000\",\"AREA_SQM:  89<br />SELLING_PRICE:   840000\",\"AREA_SQM:  89<br />SELLING_PRICE:   767500\",\"AREA_SQM:  91<br />SELLING_PRICE:   807000\",\"AREA_SQM: 109<br />SELLING_PRICE:   787500\",\"AREA_SQM:  81<br />SELLING_PRICE:   775000\",\"AREA_SQM:  45<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 105<br />SELLING_PRICE:  1660000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1760000\",\"AREA_SQM: 146<br />SELLING_PRICE:  1955000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1940000\",\"AREA_SQM:  45<br />SELLING_PRICE:  1328000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1855000\",\"AREA_SQM: 147<br />SELLING_PRICE:  1694444\",\"AREA_SQM: 107<br />SELLING_PRICE:  1206000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1230000\",\"AREA_SQM: 108<br />SELLING_PRICE:  1260000\",\"AREA_SQM: 107<br />SELLING_PRICE:  1045000\",\"AREA_SQM:  86<br />SELLING_PRICE:  1015000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1382500\",\"AREA_SQM:  90<br />SELLING_PRICE:  1382000\",\"AREA_SQM:  90<br />SELLING_PRICE:  1370000\",\"AREA_SQM: 297<br />SELLING_PRICE:  2650000\",\"AREA_SQM: 167<br />SELLING_PRICE:  1655000\",\"AREA_SQM: 153<br />SELLING_PRICE:  1665000\",\"AREA_SQM: 194<br />SELLING_PRICE:  2100000\",\"AREA_SQM:  97<br />SELLING_PRICE:  1055000\",\"AREA_SQM:  99<br />SELLING_PRICE:  1010700\",\"AREA_SQM: 113<br />SELLING_PRICE:  1142500\",\"AREA_SQM: 127<br />SELLING_PRICE:  1063000\",\"AREA_SQM: 143<br />SELLING_PRICE:  1128000\",\"AREA_SQM:  98<br />SELLING_PRICE:   940000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1138000\",\"AREA_SQM: 100<br />SELLING_PRICE:  1145000\",\"AREA_SQM:  47<br />SELLING_PRICE:  1270000\",\"AREA_SQM: 225<br />SELLING_PRICE:  1892010\",\"AREA_SQM:  99<br />SELLING_PRICE:  1185000\",\"AREA_SQM: 100<br />SELLING_PRICE:   982888\",\"AREA_SQM: 141<br />SELLING_PRICE:  1095000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1027500\",\"AREA_SQM: 118<br />SELLING_PRICE:  1040500\",\"AREA_SQM: 116<br />SELLING_PRICE:  1030584\",\"AREA_SQM: 233<br />SELLING_PRICE:  2000000\",\"AREA_SQM: 110<br />SELLING_PRICE:  1365000\",\"AREA_SQM: 103<br />SELLING_PRICE:  1100000\",\"AREA_SQM:  69<br />SELLING_PRICE:   800000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1270000\",\"AREA_SQM:  74<br />SELLING_PRICE:   840000\",\"AREA_SQM: 108<br />SELLING_PRICE:   851500\",\"AREA_SQM:  95<br />SELLING_PRICE:   900000\",\"AREA_SQM:  95<br />SELLING_PRICE:   869444\",\"AREA_SQM:  87<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 127<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1380000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1320000\",\"AREA_SQM: 145<br />SELLING_PRICE:  1580000\",\"AREA_SQM: 170<br />SELLING_PRICE:  1560000\",\"AREA_SQM:  87<br />SELLING_PRICE:  1060000\",\"AREA_SQM:  93<br />SELLING_PRICE:  1072500\",\"AREA_SQM:  86<br />SELLING_PRICE:   834444\",\"AREA_SQM:  87<br />SELLING_PRICE:  1060000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1080000\",\"AREA_SQM:  92<br />SELLING_PRICE:  1067500\",\"AREA_SQM: 190<br />SELLING_PRICE:  1332500\",\"AREA_SQM: 135<br />SELLING_PRICE:  1190000\",\"AREA_SQM: 135<br />SELLING_PRICE:  1218000\",\"AREA_SQM: 135<br />SELLING_PRICE:  1260000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1095000\",\"AREA_SQM: 211<br />SELLING_PRICE:  1650000\",\"AREA_SQM: 135<br />SELLING_PRICE:  1235000\",\"AREA_SQM: 214<br />SELLING_PRICE:  1698000\",\"AREA_SQM: 114<br />SELLING_PRICE:   990000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1120000\",\"AREA_SQM: 190<br />SELLING_PRICE:  1400000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1108000\",\"AREA_SQM: 114<br />SELLING_PRICE:   980000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1007500\",\"AREA_SQM: 158<br />SELLING_PRICE:  1100000\",\"AREA_SQM: 181<br />SELLING_PRICE:  1260000\",\"AREA_SQM: 158<br />SELLING_PRICE:  1145000\",\"AREA_SQM: 155<br />SELLING_PRICE:  1150000\",\"AREA_SQM: 117<br />SELLING_PRICE:  1000000\",\"AREA_SQM:  80<br />SELLING_PRICE:  1015000\",\"AREA_SQM: 158<br />SELLING_PRICE:  1328000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1084000\",\"AREA_SQM:  70<br />SELLING_PRICE:   780000\",\"AREA_SQM:  89<br />SELLING_PRICE:   950000\",\"AREA_SQM:  80<br />SELLING_PRICE:   969444\",\"AREA_SQM:  80<br />SELLING_PRICE:   852000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1605400\",\"AREA_SQM: 121<br />SELLING_PRICE:  1739000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1481500\",\"AREA_SQM: 132<br />SELLING_PRICE:  1635000\",\"AREA_SQM: 120<br />SELLING_PRICE:  1612000\",\"AREA_SQM: 141<br />SELLING_PRICE:  2000000\",\"AREA_SQM: 141<br />SELLING_PRICE:  1935000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1220000\",\"AREA_SQM: 164<br />SELLING_PRICE:  1239800\",\"AREA_SQM: 163<br />SELLING_PRICE:  1501500\",\"AREA_SQM: 163<br />SELLING_PRICE:  1500000\",\"AREA_SQM: 163<br />SELLING_PRICE:  1300000\",\"AREA_SQM:  88<br />SELLING_PRICE:   918000\",\"AREA_SQM: 107<br />SELLING_PRICE:   970000\",\"AREA_SQM: 109<br />SELLING_PRICE:   915000\",\"AREA_SQM: 131<br />SELLING_PRICE:  1025000\",\"AREA_SQM:  89<br />SELLING_PRICE:   907500\",\"AREA_SQM: 109<br />SELLING_PRICE:   860000\",\"AREA_SQM: 109<br />SELLING_PRICE:   920000\",\"AREA_SQM:  90<br />SELLING_PRICE:   990000\",\"AREA_SQM: 120<br />SELLING_PRICE:   995000\",\"AREA_SQM:  90<br />SELLING_PRICE:  1080000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1350000\",\"AREA_SQM:  40<br />SELLING_PRICE:   545000\",\"AREA_SQM:  56<br />SELLING_PRICE:   628000\",\"AREA_SQM:  40<br />SELLING_PRICE:   600000\",\"AREA_SQM:  40<br />SELLING_PRICE:   547000\",\"AREA_SQM:  56<br />SELLING_PRICE:   720000\",\"AREA_SQM:  47<br />SELLING_PRICE:   599444\",\"AREA_SQM:  40<br />SELLING_PRICE:   540000\",\"AREA_SQM:  40<br />SELLING_PRICE:   615000\",\"AREA_SQM:  40<br />SELLING_PRICE:   555000\",\"AREA_SQM: 113<br />SELLING_PRICE:   920000\",\"AREA_SQM: 180<br />SELLING_PRICE:   888000\",\"AREA_SQM:  89<br />SELLING_PRICE:   780000\",\"AREA_SQM: 112<br />SELLING_PRICE:   860000\",\"AREA_SQM:  92<br />SELLING_PRICE:  1276238\",\"AREA_SQM: 409<br />SELLING_PRICE:  2550000\",\"AREA_SQM:  73<br />SELLING_PRICE:  1168000\",\"AREA_SQM: 333<br />SELLING_PRICE:   947500\",\"AREA_SQM:  86<br />SELLING_PRICE:   935000\",\"AREA_SQM: 351<br />SELLING_PRICE:  1328000\",\"AREA_SQM: 141<br />SELLING_PRICE:  1430000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1330000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1250000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1069000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1720000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1869000\",\"AREA_SQM: 251<br />SELLING_PRICE:  3690000\",\"AREA_SQM: 271<br />SELLING_PRICE:  1880000\",\"AREA_SQM:  95<br />SELLING_PRICE:  1268888\",\"AREA_SQM: 141<br />SELLING_PRICE:  1035000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 146<br />SELLING_PRICE:  1250000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1035000\",\"AREA_SQM: 137<br />SELLING_PRICE:  1270000\",\"AREA_SQM: 114<br />SELLING_PRICE:   950000\",\"AREA_SQM: 119<br />SELLING_PRICE:   935000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1035000\",\"AREA_SQM: 129<br />SELLING_PRICE:  1300000\",\"AREA_SQM:  81<br />SELLING_PRICE:   930000\",\"AREA_SQM: 130<br />SELLING_PRICE:  1357500\",\"AREA_SQM: 112<br />SELLING_PRICE:  1240000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1430000\",\"AREA_SQM: 116<br />SELLING_PRICE:   950000\",\"AREA_SQM: 167<br />SELLING_PRICE:  1239440\",\"AREA_SQM: 128<br />SELLING_PRICE:  1130000\",\"AREA_SQM: 115<br />SELLING_PRICE:   950000\",\"AREA_SQM: 116<br />SELLING_PRICE:  1100000\",\"AREA_SQM: 116<br />SELLING_PRICE:   918000\",\"AREA_SQM:  98<br />SELLING_PRICE:   857500\",\"AREA_SQM: 116<br />SELLING_PRICE:   960000\",\"AREA_SQM: 116<br />SELLING_PRICE:   950000\",\"AREA_SQM: 115<br />SELLING_PRICE:   965000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1030000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1030000\",\"AREA_SQM: 102<br />SELLING_PRICE:   838000\",\"AREA_SQM: 143<br />SELLING_PRICE:  1200000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1150000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1160000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1270000\",\"AREA_SQM: 111<br />SELLING_PRICE:  1515000\",\"AREA_SQM: 110<br />SELLING_PRICE:  1455000\",\"AREA_SQM: 110<br />SELLING_PRICE:  1450000\",\"AREA_SQM:  85<br />SELLING_PRICE:   905000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1220000\",\"AREA_SQM:  82<br />SELLING_PRICE:  1044000\",\"AREA_SQM: 143<br />SELLING_PRICE:  1360000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1245000\",\"AREA_SQM: 143<br />SELLING_PRICE:  1409000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1680000\",\"AREA_SQM: 158<br />SELLING_PRICE:  2552000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1630000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1305000\",\"AREA_SQM: 130<br />SELLING_PRICE:  1422500\",\"AREA_SQM: 183<br />SELLING_PRICE:  2200000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1719999\",\"AREA_SQM: 208<br />SELLING_PRICE:  2861667\",\"AREA_SQM: 114<br />SELLING_PRICE:  1215000\",\"AREA_SQM: 130<br />SELLING_PRICE:  1214000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1195000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1200000\",\"AREA_SQM: 187<br />SELLING_PRICE:  1380000\",\"AREA_SQM: 180<br />SELLING_PRICE:  1225000\",\"AREA_SQM: 180<br />SELLING_PRICE:  1320000\",\"AREA_SQM: 140<br />SELLING_PRICE:  1825000\",\"AREA_SQM: 164<br />SELLING_PRICE:  2105000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1413888\",\"AREA_SQM: 170<br />SELLING_PRICE:  2220000\",\"AREA_SQM: 193<br />SELLING_PRICE:  2450000\",\"AREA_SQM:  84<br />SELLING_PRICE:  1091500\",\"AREA_SQM: 132<br />SELLING_PRICE:  1421500\",\"AREA_SQM:  84<br />SELLING_PRICE:  1120000\",\"AREA_SQM:  84<br />SELLING_PRICE:  1120000\",\"AREA_SQM: 121<br />SELLING_PRICE:  1295000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1310000\",\"AREA_SQM: 157<br />SELLING_PRICE:  1400000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1358000\",\"AREA_SQM: 131<br />SELLING_PRICE:  1500000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1239000\",\"AREA_SQM: 104<br />SELLING_PRICE:  1112500\",\"AREA_SQM: 103<br />SELLING_PRICE:  1225000\",\"AREA_SQM:  86<br />SELLING_PRICE:  1010000\",\"AREA_SQM:  72<br />SELLING_PRICE:  1007500\",\"AREA_SQM:  97<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1120000\",\"AREA_SQM:  72<br />SELLING_PRICE:  1230000\",\"AREA_SQM:  97<br />SELLING_PRICE:  1180000\",\"AREA_SQM:  85<br />SELLING_PRICE:   860000\",\"AREA_SQM: 105<br />SELLING_PRICE:  1250000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1190000\",\"AREA_SQM:  85<br />SELLING_PRICE:   980000\",\"AREA_SQM:  97<br />SELLING_PRICE:  1180000\",\"AREA_SQM:  97<br />SELLING_PRICE:  1119000\",\"AREA_SQM: 122<br />SELLING_PRICE:  1600000\",\"AREA_SQM: 145<br />SELLING_PRICE:  2285000\",\"AREA_SQM: 125<br />SELLING_PRICE:  1570000\",\"AREA_SQM: 181<br />SELLING_PRICE:  1690000\",\"AREA_SQM: 145<br />SELLING_PRICE:  2000000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1650000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1519952\",\"AREA_SQM:  53<br />SELLING_PRICE:  1300000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1292500\",\"AREA_SQM:  80<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 115<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 112<br />SELLING_PRICE:  1660000\",\"AREA_SQM:  96<br />SELLING_PRICE:  1115000\",\"AREA_SQM: 127<br />SELLING_PRICE:  1255000\",\"AREA_SQM: 126<br />SELLING_PRICE:  1330000\",\"AREA_SQM: 130<br />SELLING_PRICE:  1365000\",\"AREA_SQM:  96<br />SELLING_PRICE:  1820000\",\"AREA_SQM: 132<br />SELLING_PRICE:  1396500\",\"AREA_SQM: 131<br />SELLING_PRICE:  1350000\",\"AREA_SQM: 130<br />SELLING_PRICE:  1362500\",\"AREA_SQM: 132<br />SELLING_PRICE:  1365000\",\"AREA_SQM: 100<br />SELLING_PRICE:  1009750\",\"AREA_SQM: 129<br />SELLING_PRICE:  1260000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1070700\",\"AREA_SQM: 114<br />SELLING_PRICE:  1090000\",\"AREA_SQM: 114<br />SELLING_PRICE:   995000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1050000\",\"AREA_SQM: 114<br />SELLING_PRICE:   975000\",\"AREA_SQM: 126<br />SELLING_PRICE:  2060000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1890000\",\"AREA_SQM: 118<br />SELLING_PRICE:  1825000\",\"AREA_SQM: 432<br />SELLING_PRICE:  3095590\",\"AREA_SQM: 119<br />SELLING_PRICE:  1870000\",\"AREA_SQM: 119<br />SELLING_PRICE:  1900000\",\"AREA_SQM:  83<br />SELLING_PRICE:  1380000\",\"AREA_SQM: 123<br />SELLING_PRICE:  1970000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1950000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1940000\",\"AREA_SQM: 112<br />SELLING_PRICE:  2065000\",\"AREA_SQM: 114<br />SELLING_PRICE:  1845000\",\"AREA_SQM: 193<br />SELLING_PRICE:  3759000\",\"AREA_SQM: 152<br />SELLING_PRICE:  2565000\",\"AREA_SQM: 124<br />SELLING_PRICE:  1870000\",\"AREA_SQM: 110<br />SELLING_PRICE:  1030000\",\"AREA_SQM:  90<br />SELLING_PRICE:   832500\",\"AREA_SQM:  86<br />SELLING_PRICE:  1012000\",\"AREA_SQM: 133<br />SELLING_PRICE:   958000\",\"AREA_SQM:  89<br />SELLING_PRICE:   885000\",\"AREA_SQM: 110<br />SELLING_PRICE:   940000\",\"AREA_SQM:  91<br />SELLING_PRICE:   905000\",\"AREA_SQM: 350<br />SELLING_PRICE:  3392440\",\"AREA_SQM: 211<br />SELLING_PRICE:  2743530\",\"AREA_SQM:  99<br />SELLING_PRICE:  2700000\",\"AREA_SQM: 174<br />SELLING_PRICE:  2362400\",\"AREA_SQM: 184<br />SELLING_PRICE:  2382100\",\"AREA_SQM: 191<br />SELLING_PRICE:  2629000\",\"AREA_SQM:  95<br />SELLING_PRICE:  1830000\",\"AREA_SQM:  93<br />SELLING_PRICE:  1380000\",\"AREA_SQM: 191<br />SELLING_PRICE:  1668000\",\"AREA_SQM: 191<br />SELLING_PRICE:  2228550\",\"AREA_SQM: 100<br />SELLING_PRICE:  1300000\",\"AREA_SQM: 191<br />SELLING_PRICE:  2124700\",\"AREA_SQM: 191<br />SELLING_PRICE:  1853000\",\"AREA_SQM: 191<br />SELLING_PRICE:  2571350\",\"AREA_SQM:  93<br />SELLING_PRICE:  1280000\",\"AREA_SQM: 355<br />SELLING_PRICE:  3123900\",\"AREA_SQM: 174<br />SELLING_PRICE:  2290890\",\"AREA_SQM: 174<br />SELLING_PRICE:  2359200\",\"AREA_SQM: 174<br />SELLING_PRICE:  2427336\",\"AREA_SQM: 174<br />SELLING_PRICE:  2444000\",\"AREA_SQM:  97<br />SELLING_PRICE:  1365000\",\"AREA_SQM: 204<br />SELLING_PRICE:  1132500\",\"AREA_SQM:  87<br />SELLING_PRICE:  1080000\",\"AREA_SQM:  87<br />SELLING_PRICE:   825000\",\"AREA_SQM:  87<br />SELLING_PRICE:   968000\",\"AREA_SQM:  87<br />SELLING_PRICE:  1095000\",\"AREA_SQM:  87<br />SELLING_PRICE:   990000\",\"AREA_SQM:  87<br />SELLING_PRICE:   870000\",\"AREA_SQM: 371<br />SELLING_PRICE:  9600000\",\"AREA_SQM: 243<br />SELLING_PRICE:  4500000\",\"AREA_SQM: 120<br />SELLING_PRICE:  2900000\",\"AREA_SQM:  76<br />SELLING_PRICE:  1500000\",\"AREA_SQM: 193<br />SELLING_PRICE:  4680000\",\"AREA_SQM: 106<br />SELLING_PRICE:  1919000\",\"AREA_SQM:  91<br />SELLING_PRICE:  2550000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1445000\",\"AREA_SQM: 259<br />SELLING_PRICE:  2750000\",\"AREA_SQM: 103<br />SELLING_PRICE:  1185000\",\"AREA_SQM:  74<br />SELLING_PRICE:   780000\",\"AREA_SQM:  51<br />SELLING_PRICE:   758000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1420000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1340000\",\"AREA_SQM:  92<br />SELLING_PRICE:  1120000\",\"AREA_SQM: 113<br />SELLING_PRICE:  1400000\",\"AREA_SQM:  97<br />SELLING_PRICE:   835000\",\"AREA_SQM:  97<br />SELLING_PRICE:   820000\",\"AREA_SQM:  87<br />SELLING_PRICE:   750000\",\"AREA_SQM: 128<br />SELLING_PRICE:   975000\",\"AREA_SQM:  92<br />SELLING_PRICE:   780000\",\"AREA_SQM:  89<br />SELLING_PRICE:   750250\",\"AREA_SQM:  92<br />SELLING_PRICE:   765000\",\"AREA_SQM: 196<br />SELLING_PRICE:  3282200\",\"AREA_SQM: 140<br />SELLING_PRICE:  2595900\",\"AREA_SQM:  73<br />SELLING_PRICE:  1466100\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,0,0,1)\",\"opacity\":1,\"size\":5.6692913385826778,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"}},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[34,41.405063291139243,48.810126582278485,56.215189873417721,63.620253164556964,71.025316455696213,78.430379746835442,85.835443037974684,93.240506329113927,100.64556962025317,108.05063291139241,115.45569620253166,122.86075949367088,130.26582278481013,137.67088607594937,145.07594936708861,152.48101265822785,159.8860759493671,167.29113924050634,174.69620253164558,182.10126582278482,189.50632911392407,196.91139240506331,204.31645569620255,211.72151898734177,219.12658227848101,226.53164556962025,233.9367088607595,241.34177215189874,248.74683544303798,256.15189873417722,263.55696202531647,270.96202531645571,278.36708860759495,285.77215189873419,293.17721518987344,300.58227848101268,307.98734177215192,315.39240506329116,322.79746835443041,330.20253164556965,337.60759493670889,345.01265822784814,352.41772151898738,359.82278481012662,367.22784810126586,374.63291139240511,382.03797468354435,389.44303797468353,396.84810126582278,404.25316455696202,411.65822784810126,419.0632911392405,426.46835443037975,433.87341772151899,441.27848101265823,448.68354430379748,456.08860759493672,463.49367088607596,470.8987341772152,478.30379746835445,485.70886075949369,493.11392405063293,500.51898734177217,507.92405063291142,515.32911392405072,522.7341772151899,530.13924050632909,537.54430379746839,544.94936708860769,552.35443037974687,559.75949367088606,567.16455696202536,574.56962025316454,581.97468354430384,589.37974683544303,596.78481012658233,604.18987341772151,611.59493670886081,619],\"y\":[242325.90312630998,351321.23988176859,460316.5766372272,569311.9133926857,678307.25014814432,787302.58690360305,896297.92365906155,1005293.26041452,1114288.5971699788,1223283.9339254375,1332279.270680896,1441274.6074363547,1550269.944191813,1659265.2809472717,1768260.6177027302,1877255.954458189,1986251.2912136477,2095246.6279691064,2204241.9647245649,2313237.3014800232,2422232.6382354824,2531227.9749909407,2640223.3117463989,2749218.6485018581,2858213.9852573164,2967209.3220127746,3076204.6587682338,3185199.9955236921,3294195.3322791504,3403190.6690346096,3512186.0057900678,3621181.342545527,3730176.6793009853,3839172.0160564436,3948167.3528119018,4057162.689567361,4166158.0263228193,4275153.3630782785,4384148.6998337368,4493144.036589195,4602139.3733446542,4711134.7101001125,4820130.0468555717,4929125.3836110299,5038120.7203664882,5147116.0571219474,5256111.3938774057,5365106.7306328639,5474102.0673883222,5583097.4041437805,5692092.7408992397,5801088.0776546979,5910083.4144101571,6019078.7511656154,6128074.0879210737,6237069.4246765329,6346064.7614319911,6455060.0981874494,6564055.4349429086,6673050.7716983669,6782046.108453826,6891041.4452092843,7000036.7819647426,7109032.1187202018,7218027.45547566,7327022.7922311192,7436018.1289865775,7545013.4657420348,7654008.802497495,7763004.1392529542,7871999.4760084115,7980994.8127638698,8089990.149519329,8198985.4862747863,8307980.8230302464,8416976.1597857047,8525971.496541163,8634966.8332966212,8743962.1700520813,8852957.5068075396],\"text\":[\"AREA_SQM:  34.00000<br />SELLING_PRICE:  242325.9\",\"AREA_SQM:  41.40506<br />SELLING_PRICE:  351321.2\",\"AREA_SQM:  48.81013<br />SELLING_PRICE:  460316.6\",\"AREA_SQM:  56.21519<br />SELLING_PRICE:  569311.9\",\"AREA_SQM:  63.62025<br />SELLING_PRICE:  678307.3\",\"AREA_SQM:  71.02532<br />SELLING_PRICE:  787302.6\",\"AREA_SQM:  78.43038<br />SELLING_PRICE:  896297.9\",\"AREA_SQM:  85.83544<br />SELLING_PRICE: 1005293.3\",\"AREA_SQM:  93.24051<br />SELLING_PRICE: 1114288.6\",\"AREA_SQM: 100.64557<br />SELLING_PRICE: 1223283.9\",\"AREA_SQM: 108.05063<br />SELLING_PRICE: 1332279.3\",\"AREA_SQM: 115.45570<br />SELLING_PRICE: 1441274.6\",\"AREA_SQM: 122.86076<br />SELLING_PRICE: 1550269.9\",\"AREA_SQM: 130.26582<br />SELLING_PRICE: 1659265.3\",\"AREA_SQM: 137.67089<br />SELLING_PRICE: 1768260.6\",\"AREA_SQM: 145.07595<br />SELLING_PRICE: 1877256.0\",\"AREA_SQM: 152.48101<br />SELLING_PRICE: 1986251.3\",\"AREA_SQM: 159.88608<br />SELLING_PRICE: 2095246.6\",\"AREA_SQM: 167.29114<br />SELLING_PRICE: 2204242.0\",\"AREA_SQM: 174.69620<br />SELLING_PRICE: 2313237.3\",\"AREA_SQM: 182.10127<br />SELLING_PRICE: 2422232.6\",\"AREA_SQM: 189.50633<br />SELLING_PRICE: 2531228.0\",\"AREA_SQM: 196.91139<br />SELLING_PRICE: 2640223.3\",\"AREA_SQM: 204.31646<br />SELLING_PRICE: 2749218.6\",\"AREA_SQM: 211.72152<br />SELLING_PRICE: 2858214.0\",\"AREA_SQM: 219.12658<br />SELLING_PRICE: 2967209.3\",\"AREA_SQM: 226.53165<br />SELLING_PRICE: 3076204.7\",\"AREA_SQM: 233.93671<br />SELLING_PRICE: 3185200.0\",\"AREA_SQM: 241.34177<br />SELLING_PRICE: 3294195.3\",\"AREA_SQM: 248.74684<br />SELLING_PRICE: 3403190.7\",\"AREA_SQM: 256.15190<br />SELLING_PRICE: 3512186.0\",\"AREA_SQM: 263.55696<br />SELLING_PRICE: 3621181.3\",\"AREA_SQM: 270.96203<br />SELLING_PRICE: 3730176.7\",\"AREA_SQM: 278.36709<br />SELLING_PRICE: 3839172.0\",\"AREA_SQM: 285.77215<br />SELLING_PRICE: 3948167.4\",\"AREA_SQM: 293.17722<br />SELLING_PRICE: 4057162.7\",\"AREA_SQM: 300.58228<br />SELLING_PRICE: 4166158.0\",\"AREA_SQM: 307.98734<br />SELLING_PRICE: 4275153.4\",\"AREA_SQM: 315.39241<br />SELLING_PRICE: 4384148.7\",\"AREA_SQM: 322.79747<br />SELLING_PRICE: 4493144.0\",\"AREA_SQM: 330.20253<br />SELLING_PRICE: 4602139.4\",\"AREA_SQM: 337.60759<br />SELLING_PRICE: 4711134.7\",\"AREA_SQM: 345.01266<br />SELLING_PRICE: 4820130.0\",\"AREA_SQM: 352.41772<br />SELLING_PRICE: 4929125.4\",\"AREA_SQM: 359.82278<br />SELLING_PRICE: 5038120.7\",\"AREA_SQM: 367.22785<br />SELLING_PRICE: 5147116.1\",\"AREA_SQM: 374.63291<br />SELLING_PRICE: 5256111.4\",\"AREA_SQM: 382.03797<br />SELLING_PRICE: 5365106.7\",\"AREA_SQM: 389.44304<br />SELLING_PRICE: 5474102.1\",\"AREA_SQM: 396.84810<br />SELLING_PRICE: 5583097.4\",\"AREA_SQM: 404.25316<br />SELLING_PRICE: 5692092.7\",\"AREA_SQM: 411.65823<br />SELLING_PRICE: 5801088.1\",\"AREA_SQM: 419.06329<br />SELLING_PRICE: 5910083.4\",\"AREA_SQM: 426.46835<br />SELLING_PRICE: 6019078.8\",\"AREA_SQM: 433.87342<br />SELLING_PRICE: 6128074.1\",\"AREA_SQM: 441.27848<br />SELLING_PRICE: 6237069.4\",\"AREA_SQM: 448.68354<br />SELLING_PRICE: 6346064.8\",\"AREA_SQM: 456.08861<br />SELLING_PRICE: 6455060.1\",\"AREA_SQM: 463.49367<br />SELLING_PRICE: 6564055.4\",\"AREA_SQM: 470.89873<br />SELLING_PRICE: 6673050.8\",\"AREA_SQM: 478.30380<br />SELLING_PRICE: 6782046.1\",\"AREA_SQM: 485.70886<br />SELLING_PRICE: 6891041.4\",\"AREA_SQM: 493.11392<br />SELLING_PRICE: 7000036.8\",\"AREA_SQM: 500.51899<br />SELLING_PRICE: 7109032.1\",\"AREA_SQM: 507.92405<br />SELLING_PRICE: 7218027.5\",\"AREA_SQM: 515.32911<br />SELLING_PRICE: 7327022.8\",\"AREA_SQM: 522.73418<br />SELLING_PRICE: 7436018.1\",\"AREA_SQM: 530.13924<br />SELLING_PRICE: 7545013.5\",\"AREA_SQM: 537.54430<br />SELLING_PRICE: 7654008.8\",\"AREA_SQM: 544.94937<br />SELLING_PRICE: 7763004.1\",\"AREA_SQM: 552.35443<br />SELLING_PRICE: 7871999.5\",\"AREA_SQM: 559.75949<br />SELLING_PRICE: 7980994.8\",\"AREA_SQM: 567.16456<br />SELLING_PRICE: 8089990.1\",\"AREA_SQM: 574.56962<br />SELLING_PRICE: 8198985.5\",\"AREA_SQM: 581.97468<br />SELLING_PRICE: 8307980.8\",\"AREA_SQM: 589.37975<br />SELLING_PRICE: 8416976.2\",\"AREA_SQM: 596.78481<br />SELLING_PRICE: 8525971.5\",\"AREA_SQM: 604.18987<br />SELLING_PRICE: 8634966.8\",\"AREA_SQM: 611.59494<br />SELLING_PRICE: 8743962.2\",\"AREA_SQM: 619.00000<br />SELLING_PRICE: 8852957.5\"],\"type\":\"scatter\",\"mode\":\"lines\",\"name\":\"fitted values\",\"line\":{\"width\":3.7795275590551185,\"color\":\"rgba(51,102,255,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[34,41.405063291139243,48.810126582278485,56.215189873417721,63.620253164556964,71.025316455696213,78.430379746835442,85.835443037974684,93.240506329113927,100.64556962025317,108.05063291139241,115.45569620253166,122.86075949367088,130.26582278481013,137.67088607594937,145.07594936708861,152.48101265822785,159.8860759493671,167.29113924050634,174.69620253164558,182.10126582278482,189.50632911392407,196.91139240506331,204.31645569620255,211.72151898734177,219.12658227848101,226.53164556962025,233.9367088607595,241.34177215189874,248.74683544303798,256.15189873417722,263.55696202531647,270.96202531645571,278.36708860759495,285.77215189873419,293.17721518987344,300.58227848101268,307.98734177215192,315.39240506329116,322.79746835443041,330.20253164556965,337.60759493670889,345.01265822784814,352.41772151898738,359.82278481012662,367.22784810126586,374.63291139240511,382.03797468354435,389.44303797468353,396.84810126582278,404.25316455696202,411.65822784810126,419.0632911392405,426.46835443037975,433.87341772151899,441.27848101265823,448.68354430379748,456.08860759493672,463.49367088607596,470.8987341772152,478.30379746835445,485.70886075949369,493.11392405063293,500.51898734177217,507.92405063291142,515.32911392405072,522.7341772151899,530.13924050632909,537.54430379746839,544.94936708860769,552.35443037974687,559.75949367088606,567.16455696202536,574.56962025316454,581.97468354430384,589.37974683544303,596.78481012658233,604.18987341772151,611.59493670886081,619,619,619,611.59493670886081,604.18987341772151,596.78481012658233,589.37974683544303,581.97468354430384,574.56962025316454,567.16455696202536,559.75949367088606,552.35443037974687,544.94936708860769,537.54430379746839,530.13924050632909,522.7341772151899,515.32911392405072,507.92405063291142,500.51898734177217,493.11392405063293,485.70886075949369,478.30379746835445,470.8987341772152,463.49367088607596,456.08860759493672,448.68354430379748,441.27848101265823,433.87341772151899,426.46835443037975,419.0632911392405,411.65822784810126,404.25316455696202,396.84810126582278,389.44303797468353,382.03797468354435,374.63291139240511,367.22784810126586,359.82278481012662,352.41772151898738,345.01265822784814,337.60759493670889,330.20253164556965,322.79746835443041,315.39240506329116,307.98734177215192,300.58227848101268,293.17721518987344,285.77215189873419,278.36708860759495,270.96202531645571,263.55696202531647,256.15189873417722,248.74683544303798,241.34177215189874,233.9367088607595,226.53164556962025,219.12658227848101,211.72151898734177,204.31645569620255,196.91139240506331,189.50632911392407,182.10126582278482,174.69620253164558,167.29113924050634,159.8860759493671,152.48101265822785,145.07594936708861,137.67088607594937,130.26582278481013,122.86075949367088,115.45569620253166,108.05063291139241,100.64556962025317,93.240506329113927,85.835443037974684,78.430379746835442,71.025316455696213,63.620253164556964,56.215189873417721,48.810126582278485,41.405063291139243,34,34],\"y\":[143367.82117230387,257723.06229838758,371965.6709019852,486074.3432939722,600022.82997380814,713778.74966343353,827302.23047898698,940544.48786497908,1053446.6030348542,1165939.0144608673,1277942.5596942098,1389372.1665718206,1500144.1483484015,1610187.034395796,1719453.85593151,1827931.7966953747,1935645.047351625,2042649.497524308,2149021.7584715551,2254846.9678569324,2360208.951010359,2465184.1158685577,2569838.7131970893,2674228.389584376,2778398.9930160861,2882387.8985702419,2986225.430067603,3089936.1715678144,3193540.0912520401,3297053.4664515941,3400489.627905807,3503859.5511887111,3607172.3238647892,3710435.5137745775,3813655.4595917966,3916837.5006313105,4019986.1592737436,4123105.2864127704,4226198.1779823015,4329267.6687901905,4432316.2084723627,4535345.9232965121,4638358.6667130562,4741356.0609133607,4844339.5311654704,4947310.3343200879,5050269.5825878158,5153218.2634620946,5256157.2564857211,5359087.3474205267,5462009.2402710244,5564923.5675268946,5667830.8989209058,5770731.7489444735,5873626.5833194777,5976515.8245898653,6079399.8569682427,6182279.0305496994,6285153.6649863264,6388024.0527006015,6490890.4617032595,6593753.1380708367,6696612.3081295891,6799468.1803852767,6902320.9472324634,7005170.7864719704,7108017.862660991,7210862.3283168906,7313704.3249927573,7416543.984240259,7519381.4284733171,7622216.7717442214,7725050.1204423262,7827881.5739241559,7930711.2250826266,8033539.1608620677,8136365.4627249939,8239190.2070757709,8342013.4656457286,8444835.3058437537,8444835.3058437537,9261079.7077713255,9145910.8744584341,9030743.4595174715,8915577.530357331,8800413.1587093417,8685250.4209778663,8570089.3986254167,8454930.1785963327,8339772.8537835181,8224617.5235435059,8109464.2942656493,7994313.2800022326,7879164.603167179,7764018.395312164,7648874.7979902681,7533733.9637188567,7418596.0570551269,7303461.2557998961,7188329.752347732,7073201.7552043926,6958077.4906961322,6842957.2048994908,6727841.1658251993,6612729.6658957396,6497623.0247632004,6382521.5925226696,6267425.7533867573,6152335.9298994085,6037252.5877825012,5922176.2415274549,5807107.4608670343,5692046.8782909233,5576995.1978036333,5461953.2051669955,5346921.7799238069,5231901.9095675061,5116894.7063086992,5001901.4269980872,4886923.4969037129,4771962.5382169457,4657020.4043881996,4542099.2216851721,4427201.4397437861,4312329.893371895,4197487.878503412,4082679.246032007,3967908.5183383096,3853181.0347371814,3738503.133902343,3623882.3836743287,3509327.871617625,3394850.5733062606,3280463.8194795698,3166183.8874688647,3052030.7454553074,2938028.9774985467,2824208.9074193402,2710607.9102957086,2597271.8341133236,2484256.3254606058,2371627.6351031139,2259462.1709775748,2147843.7584139048,2036857.5350756703,1926580.1122210033,1817067.3794739505,1708343.5274987475,1600395.7400352245,1493177.0483008889,1386615.9816675822,1280628.8533900077,1175130.5913051034,1070042.032964061,965293.61683913611,860826.42414377257,756591.6703224805,652549.48349139921,548667.48237246915,444919.4174651496,341283.98508031608,143367.82117230387],\"text\":[\"AREA_SQM:  34.00000<br />SELLING_PRICE:  242325.9\",\"AREA_SQM:  41.40506<br />SELLING_PRICE:  351321.2\",\"AREA_SQM:  48.81013<br />SELLING_PRICE:  460316.6\",\"AREA_SQM:  56.21519<br />SELLING_PRICE:  569311.9\",\"AREA_SQM:  63.62025<br />SELLING_PRICE:  678307.3\",\"AREA_SQM:  71.02532<br />SELLING_PRICE:  787302.6\",\"AREA_SQM:  78.43038<br />SELLING_PRICE:  896297.9\",\"AREA_SQM:  85.83544<br />SELLING_PRICE: 1005293.3\",\"AREA_SQM:  93.24051<br />SELLING_PRICE: 1114288.6\",\"AREA_SQM: 100.64557<br />SELLING_PRICE: 1223283.9\",\"AREA_SQM: 108.05063<br />SELLING_PRICE: 1332279.3\",\"AREA_SQM: 115.45570<br />SELLING_PRICE: 1441274.6\",\"AREA_SQM: 122.86076<br />SELLING_PRICE: 1550269.9\",\"AREA_SQM: 130.26582<br />SELLING_PRICE: 1659265.3\",\"AREA_SQM: 137.67089<br />SELLING_PRICE: 1768260.6\",\"AREA_SQM: 145.07595<br />SELLING_PRICE: 1877256.0\",\"AREA_SQM: 152.48101<br />SELLING_PRICE: 1986251.3\",\"AREA_SQM: 159.88608<br />SELLING_PRICE: 2095246.6\",\"AREA_SQM: 167.29114<br />SELLING_PRICE: 2204242.0\",\"AREA_SQM: 174.69620<br />SELLING_PRICE: 2313237.3\",\"AREA_SQM: 182.10127<br />SELLING_PRICE: 2422232.6\",\"AREA_SQM: 189.50633<br />SELLING_PRICE: 2531228.0\",\"AREA_SQM: 196.91139<br />SELLING_PRICE: 2640223.3\",\"AREA_SQM: 204.31646<br />SELLING_PRICE: 2749218.6\",\"AREA_SQM: 211.72152<br />SELLING_PRICE: 2858214.0\",\"AREA_SQM: 219.12658<br />SELLING_PRICE: 2967209.3\",\"AREA_SQM: 226.53165<br />SELLING_PRICE: 3076204.7\",\"AREA_SQM: 233.93671<br />SELLING_PRICE: 3185200.0\",\"AREA_SQM: 241.34177<br />SELLING_PRICE: 3294195.3\",\"AREA_SQM: 248.74684<br />SELLING_PRICE: 3403190.7\",\"AREA_SQM: 256.15190<br />SELLING_PRICE: 3512186.0\",\"AREA_SQM: 263.55696<br />SELLING_PRICE: 3621181.3\",\"AREA_SQM: 270.96203<br />SELLING_PRICE: 3730176.7\",\"AREA_SQM: 278.36709<br />SELLING_PRICE: 3839172.0\",\"AREA_SQM: 285.77215<br />SELLING_PRICE: 3948167.4\",\"AREA_SQM: 293.17722<br />SELLING_PRICE: 4057162.7\",\"AREA_SQM: 300.58228<br />SELLING_PRICE: 4166158.0\",\"AREA_SQM: 307.98734<br />SELLING_PRICE: 4275153.4\",\"AREA_SQM: 315.39241<br />SELLING_PRICE: 4384148.7\",\"AREA_SQM: 322.79747<br />SELLING_PRICE: 4493144.0\",\"AREA_SQM: 330.20253<br />SELLING_PRICE: 4602139.4\",\"AREA_SQM: 337.60759<br />SELLING_PRICE: 4711134.7\",\"AREA_SQM: 345.01266<br />SELLING_PRICE: 4820130.0\",\"AREA_SQM: 352.41772<br />SELLING_PRICE: 4929125.4\",\"AREA_SQM: 359.82278<br />SELLING_PRICE: 5038120.7\",\"AREA_SQM: 367.22785<br />SELLING_PRICE: 5147116.1\",\"AREA_SQM: 374.63291<br />SELLING_PRICE: 5256111.4\",\"AREA_SQM: 382.03797<br />SELLING_PRICE: 5365106.7\",\"AREA_SQM: 389.44304<br />SELLING_PRICE: 5474102.1\",\"AREA_SQM: 396.84810<br />SELLING_PRICE: 5583097.4\",\"AREA_SQM: 404.25316<br />SELLING_PRICE: 5692092.7\",\"AREA_SQM: 411.65823<br />SELLING_PRICE: 5801088.1\",\"AREA_SQM: 419.06329<br />SELLING_PRICE: 5910083.4\",\"AREA_SQM: 426.46835<br />SELLING_PRICE: 6019078.8\",\"AREA_SQM: 433.87342<br />SELLING_PRICE: 6128074.1\",\"AREA_SQM: 441.27848<br />SELLING_PRICE: 6237069.4\",\"AREA_SQM: 448.68354<br />SELLING_PRICE: 6346064.8\",\"AREA_SQM: 456.08861<br />SELLING_PRICE: 6455060.1\",\"AREA_SQM: 463.49367<br />SELLING_PRICE: 6564055.4\",\"AREA_SQM: 470.89873<br />SELLING_PRICE: 6673050.8\",\"AREA_SQM: 478.30380<br />SELLING_PRICE: 6782046.1\",\"AREA_SQM: 485.70886<br />SELLING_PRICE: 6891041.4\",\"AREA_SQM: 493.11392<br />SELLING_PRICE: 7000036.8\",\"AREA_SQM: 500.51899<br />SELLING_PRICE: 7109032.1\",\"AREA_SQM: 507.92405<br />SELLING_PRICE: 7218027.5\",\"AREA_SQM: 515.32911<br />SELLING_PRICE: 7327022.8\",\"AREA_SQM: 522.73418<br />SELLING_PRICE: 7436018.1\",\"AREA_SQM: 530.13924<br />SELLING_PRICE: 7545013.5\",\"AREA_SQM: 537.54430<br />SELLING_PRICE: 7654008.8\",\"AREA_SQM: 544.94937<br />SELLING_PRICE: 7763004.1\",\"AREA_SQM: 552.35443<br />SELLING_PRICE: 7871999.5\",\"AREA_SQM: 559.75949<br />SELLING_PRICE: 7980994.8\",\"AREA_SQM: 567.16456<br />SELLING_PRICE: 8089990.1\",\"AREA_SQM: 574.56962<br />SELLING_PRICE: 8198985.5\",\"AREA_SQM: 581.97468<br />SELLING_PRICE: 8307980.8\",\"AREA_SQM: 589.37975<br />SELLING_PRICE: 8416976.2\",\"AREA_SQM: 596.78481<br />SELLING_PRICE: 8525971.5\",\"AREA_SQM: 604.18987<br />SELLING_PRICE: 8634966.8\",\"AREA_SQM: 611.59494<br />SELLING_PRICE: 8743962.2\",\"AREA_SQM: 619.00000<br />SELLING_PRICE: 8852957.5\",\"AREA_SQM: 619.00000<br />SELLING_PRICE: 8852957.5\",\"AREA_SQM: 619.00000<br />SELLING_PRICE: 8852957.5\",\"AREA_SQM: 611.59494<br />SELLING_PRICE: 8743962.2\",\"AREA_SQM: 604.18987<br />SELLING_PRICE: 8634966.8\",\"AREA_SQM: 596.78481<br />SELLING_PRICE: 8525971.5\",\"AREA_SQM: 589.37975<br />SELLING_PRICE: 8416976.2\",\"AREA_SQM: 581.97468<br />SELLING_PRICE: 8307980.8\",\"AREA_SQM: 574.56962<br />SELLING_PRICE: 8198985.5\",\"AREA_SQM: 567.16456<br />SELLING_PRICE: 8089990.1\",\"AREA_SQM: 559.75949<br />SELLING_PRICE: 7980994.8\",\"AREA_SQM: 552.35443<br />SELLING_PRICE: 7871999.5\",\"AREA_SQM: 544.94937<br />SELLING_PRICE: 7763004.1\",\"AREA_SQM: 537.54430<br />SELLING_PRICE: 7654008.8\",\"AREA_SQM: 530.13924<br />SELLING_PRICE: 7545013.5\",\"AREA_SQM: 522.73418<br />SELLING_PRICE: 7436018.1\",\"AREA_SQM: 515.32911<br />SELLING_PRICE: 7327022.8\",\"AREA_SQM: 507.92405<br />SELLING_PRICE: 7218027.5\",\"AREA_SQM: 500.51899<br />SELLING_PRICE: 7109032.1\",\"AREA_SQM: 493.11392<br />SELLING_PRICE: 7000036.8\",\"AREA_SQM: 485.70886<br />SELLING_PRICE: 6891041.4\",\"AREA_SQM: 478.30380<br />SELLING_PRICE: 6782046.1\",\"AREA_SQM: 470.89873<br />SELLING_PRICE: 6673050.8\",\"AREA_SQM: 463.49367<br />SELLING_PRICE: 6564055.4\",\"AREA_SQM: 456.08861<br />SELLING_PRICE: 6455060.1\",\"AREA_SQM: 448.68354<br />SELLING_PRICE: 6346064.8\",\"AREA_SQM: 441.27848<br />SELLING_PRICE: 6237069.4\",\"AREA_SQM: 433.87342<br />SELLING_PRICE: 6128074.1\",\"AREA_SQM: 426.46835<br />SELLING_PRICE: 6019078.8\",\"AREA_SQM: 419.06329<br />SELLING_PRICE: 5910083.4\",\"AREA_SQM: 411.65823<br />SELLING_PRICE: 5801088.1\",\"AREA_SQM: 404.25316<br />SELLING_PRICE: 5692092.7\",\"AREA_SQM: 396.84810<br />SELLING_PRICE: 5583097.4\",\"AREA_SQM: 389.44304<br />SELLING_PRICE: 5474102.1\",\"AREA_SQM: 382.03797<br />SELLING_PRICE: 5365106.7\",\"AREA_SQM: 374.63291<br />SELLING_PRICE: 5256111.4\",\"AREA_SQM: 367.22785<br />SELLING_PRICE: 5147116.1\",\"AREA_SQM: 359.82278<br />SELLING_PRICE: 5038120.7\",\"AREA_SQM: 352.41772<br />SELLING_PRICE: 4929125.4\",\"AREA_SQM: 345.01266<br />SELLING_PRICE: 4820130.0\",\"AREA_SQM: 337.60759<br />SELLING_PRICE: 4711134.7\",\"AREA_SQM: 330.20253<br />SELLING_PRICE: 4602139.4\",\"AREA_SQM: 322.79747<br />SELLING_PRICE: 4493144.0\",\"AREA_SQM: 315.39241<br />SELLING_PRICE: 4384148.7\",\"AREA_SQM: 307.98734<br />SELLING_PRICE: 4275153.4\",\"AREA_SQM: 300.58228<br />SELLING_PRICE: 4166158.0\",\"AREA_SQM: 293.17722<br />SELLING_PRICE: 4057162.7\",\"AREA_SQM: 285.77215<br />SELLING_PRICE: 3948167.4\",\"AREA_SQM: 278.36709<br />SELLING_PRICE: 3839172.0\",\"AREA_SQM: 270.96203<br />SELLING_PRICE: 3730176.7\",\"AREA_SQM: 263.55696<br />SELLING_PRICE: 3621181.3\",\"AREA_SQM: 256.15190<br />SELLING_PRICE: 3512186.0\",\"AREA_SQM: 248.74684<br />SELLING_PRICE: 3403190.7\",\"AREA_SQM: 241.34177<br />SELLING_PRICE: 3294195.3\",\"AREA_SQM: 233.93671<br />SELLING_PRICE: 3185200.0\",\"AREA_SQM: 226.53165<br />SELLING_PRICE: 3076204.7\",\"AREA_SQM: 219.12658<br />SELLING_PRICE: 2967209.3\",\"AREA_SQM: 211.72152<br />SELLING_PRICE: 2858214.0\",\"AREA_SQM: 204.31646<br />SELLING_PRICE: 2749218.6\",\"AREA_SQM: 196.91139<br />SELLING_PRICE: 2640223.3\",\"AREA_SQM: 189.50633<br />SELLING_PRICE: 2531228.0\",\"AREA_SQM: 182.10127<br />SELLING_PRICE: 2422232.6\",\"AREA_SQM: 174.69620<br />SELLING_PRICE: 2313237.3\",\"AREA_SQM: 167.29114<br />SELLING_PRICE: 2204242.0\",\"AREA_SQM: 159.88608<br />SELLING_PRICE: 2095246.6\",\"AREA_SQM: 152.48101<br />SELLING_PRICE: 1986251.3\",\"AREA_SQM: 145.07595<br />SELLING_PRICE: 1877256.0\",\"AREA_SQM: 137.67089<br />SELLING_PRICE: 1768260.6\",\"AREA_SQM: 130.26582<br />SELLING_PRICE: 1659265.3\",\"AREA_SQM: 122.86076<br />SELLING_PRICE: 1550269.9\",\"AREA_SQM: 115.45570<br />SELLING_PRICE: 1441274.6\",\"AREA_SQM: 108.05063<br />SELLING_PRICE: 1332279.3\",\"AREA_SQM: 100.64557<br />SELLING_PRICE: 1223283.9\",\"AREA_SQM:  93.24051<br />SELLING_PRICE: 1114288.6\",\"AREA_SQM:  85.83544<br />SELLING_PRICE: 1005293.3\",\"AREA_SQM:  78.43038<br />SELLING_PRICE:  896297.9\",\"AREA_SQM:  71.02532<br />SELLING_PRICE:  787302.6\",\"AREA_SQM:  63.62025<br />SELLING_PRICE:  678307.3\",\"AREA_SQM:  56.21519<br />SELLING_PRICE:  569311.9\",\"AREA_SQM:  48.81013<br />SELLING_PRICE:  460316.6\",\"AREA_SQM:  41.40506<br />SELLING_PRICE:  351321.2\",\"AREA_SQM:  34.00000<br />SELLING_PRICE:  242325.9\",\"AREA_SQM:  34.00000<br />SELLING_PRICE:  242325.9\"],\"type\":\"scatter\",\"mode\":\"lines\",\"line\":{\"width\":3.7795275590551185,\"color\":\"transparent\",\"dash\":\"solid\"},\"fill\":\"toself\",\"fillcolor\":\"rgba(153,153,153,0.4)\",\"hoveron\":\"points\",\"hoverinfo\":\"x+y\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":26.74896341783446,\"r\":7.3059360730593621,\"b\":40.70330131737785,\"l\":66.484018264840202},\"plot_bgcolor\":\"rgba(235,235,235,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[4.75,648.25],\"tickmode\":\"array\",\"ticktext\":[\"200\",\"400\",\"600\"],\"tickvals\":[199.99999999999997,400,600],\"categoryorder\":\"array\",\"categoryarray\":[\"200\",\"400\",\"600\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.689497716894984},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"AREA_SQM\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-749463.78776908095,18892831.608941384],\"tickmode\":\"array\",\"ticktext\":[\"0.0e+00\",\"5.0e+06\",\"1.0e+07\",\"1.5e+07\"],\"tickvals\":[0,5000000,10000000,14999999.999999998],\"categoryorder\":\"array\",\"categoryarray\":[\"0.0e+00\",\"5.0e+06\",\"1.0e+07\",\"1.5e+07\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(51,51,51,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.66417600664176002,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(255,255,255,1)\",\"gridwidth\":0.66417600664176002,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"SELLING_PRICE\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275593,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.689497716894984}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"94f03a991279\":{\"x\":{},\"y\":{},\"type\":\"scatter\"},\"94f0e637f00\":{\"x\":{},\"y\":{}}},\"cur_data\":\"94f03a991279\",\"visdat\":{\"94f03a991279\":[\"function (y) \",\"x\"],\"94f0e637f00\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n:::\n:::\n\n\nFigure above reveals that there are a **few statistical outliers** with relatively high selling prices.\n\n### **13.8.2 Multiple Linear Regression Method**\n\n#### 13.8.2.1 Visualising the relationships of the independent variables\n\nBefore building a multiple regression model, it is important to ensure that the indepdent variables used are **not** highly correlated to each other. If these highly correlated independent variables are used in building a regression model by mistake, the quality of the model will be compromised. This phenomenon is known as **multicollinearity** in statistics.\n\n**Correlation matrix** is commonly used to visualise the relationships between the independent variables. Beside the `pairs()` of R, there are many packages support the display of a correlation matrix. We will be using the [**corrplot**](https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html) package.\n\nThe code chunk below is used to plot a scatterplot matrix of the relationship between the independent variables in *condo_resale* data.frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(condo_resale)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"LATITUDE\"             \"LONGITUDE\"            \"POSTCODE\"            \n [4] \"SELLING_PRICE\"        \"AREA_SQM\"             \"AGE\"                 \n [7] \"PROX_CBD\"             \"PROX_CHILDCARE\"       \"PROX_ELDERLYCARE\"    \n[10] \"PROX_URA_GROWTH_AREA\" \"PROX_HAWKER_MARKET\"   \"PROX_KINDERGARTEN\"   \n[13] \"PROX_MRT\"             \"PROX_PARK\"            \"PROX_PRIMARY_SCH\"    \n[16] \"PROX_TOP_PRIMARY_SCH\" \"PROX_SHOPPING_MALL\"   \"PROX_SUPERMARKET\"    \n[19] \"PROX_BUS_STOP\"        \"NO_Of_UNITS\"          \"FAMILY_FRIENDLY\"     \n[22] \"FREEHOLD\"             \"LEASEHOLD_99YR\"      \n```\n:::\n:::\n\n\n`cor(condo_resale[,5:23])` gives a matrix array of the correlation values between each pair of variables.\n\n\n::: {.cell fig.asp='0.68'}\n\n```{.r .cell-code}\ncorrplot(cor(condo_resale[,5:23]),\n         diag= FALSE,\n         order= 'AOE',\n         tl.pos= 'td',\n         tl.cex = 0.8, # increase or decrease the size of variable names\n         method = 'number',\n         type = 'upper')\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex4_1_files/figure-html/unnamed-chunk-26-1.png){width=1344}\n:::\n:::\n\n\nMatrix reorder is very important for mining the hiden structure and patter in the matrix. There are four methods in corrplot (parameter order), named \"AOE\", \"FPC\", \"hclust\", \"alphabet\". In the code chunk above, AOE order is used. It orders the variables by using the *angular order of the eigenvectors* method suggested by [Michael Friendly](https://www.datavis.ca/papers/corrgram.pdf).\n\n**`tl.pos`:** This parameter specifies the position of the variable names (text labels) around the correlation plot. It can take one of the following values:\n\n-   **`\"n\"`**: Names are displayed on the top of the plot.\n\n-   **`\"ne\"`**: Names are displayed on the top-right corner of the plot.\n\n-   **`\"e\"`**: Names are displayed on the right side of the plot.\n\n-   **`\"se\"`**: Names are displayed on the bottom-right corner of the plot.\n\n-   **`\"s\"`**: Names are displayed at the bottom of the plot.\n\n-   **`\"sw\"`**: Names are displayed on the bottom-left corner of the plot.\n\n-   **`\"w\"`**: Names are displayed on the left side of the plot.\n\n-   **`\"nw\"`**: Names are displayed on the top-left corner of the plot.\n\n-   **`\"td\"`**: Names are displayed outside of the plot.\n\nFrom the scatterplot matrix, it is clear that ***Freehold*** is highly correlated to ***LEASE_99YEAR***. In view of this, it is wiser to only include either one of them in the subsequent model building. As a result, ***LEASE_99YEAR*** is **excluded** in the subsequent model building.\n\n### **13.8.3 Building a hedonic pricing model using multiple linear regression method**\n\nPreviously, we have use `lm(formula=SELLING_PRICE ~ AREA_SQM, data = condo_resale.sf)` to fit only one independent variable.\n\nThe code chunk below using `lm()` to **calibrate** the *multiple* linear regression model, ***LEASE_99YEAR*** has been excluded.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.mlr18 <- lm(formula = log(SELLING_PRICE) ~ AREA_SQM + AGE    + \n                  PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +\n                  PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET + PROX_KINDERGARTEN + \n                  PROX_MRT  + PROX_PARK + PROX_PRIMARY_SCH + \n                  PROX_TOP_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_SUPERMARKET + \n                  PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, \n                data=condo_resale.sf)\nsummary(condo.mlr18)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(SELLING_PRICE) ~ AREA_SQM + AGE + PROX_CBD + \n    PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + \n    PROX_HAWKER_MARKET + PROX_KINDERGARTEN + PROX_MRT + PROX_PARK + \n    PROX_PRIMARY_SCH + PROX_TOP_PRIMARY_SCH + PROX_SHOPPING_MALL + \n    PROX_SUPERMARKET + PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + \n    FREEHOLD, data = condo_resale.sf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.34122 -0.12109 -0.00683  0.12583  1.08031 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           1.394e+01  3.534e-02 394.500  < 2e-16 ***\nAREA_SQM              4.773e-03  1.075e-04  44.381  < 2e-16 ***\nAGE                  -6.369e-03  8.040e-04  -7.922 4.70e-15 ***\nPROX_CBD             -4.756e-02  1.970e-03 -24.147  < 2e-16 ***\nPROX_CHILDCARE       -5.186e-02  3.185e-02  -1.628 0.103741    \nPROX_ELDERLYCARE      5.142e-02  1.225e-02   4.196 2.88e-05 ***\nPROX_URA_GROWTH_AREA  1.252e-02  3.644e-03   3.437 0.000605 ***\nPROX_HAWKER_MARKET    3.185e-03  8.526e-03   0.374 0.708810    \nPROX_KINDERGARTEN     7.409e-02  2.406e-02   3.080 0.002109 ** \nPROX_MRT             -9.881e-02  1.686e-02  -5.860 5.75e-09 ***\nPROX_PARK             8.325e-02  1.937e-02   4.299 1.83e-05 ***\nPROX_PRIMARY_SCH     -6.250e-03  1.898e-02  -0.329 0.742039    \nPROX_TOP_PRIMARY_SCH  3.960e-03  5.939e-03   0.667 0.505044    \nPROX_SHOPPING_MALL   -3.471e-02  1.247e-02  -2.785 0.005428 ** \nPROX_SUPERMARKET     -3.436e-02  2.243e-02  -1.532 0.125738    \nPROX_BUS_STOP         2.483e-01  4.026e-02   6.169 8.97e-10 ***\nNO_Of_UNITS          -4.744e-06  2.591e-05  -0.183 0.854738    \nFAMILY_FRIENDLY      -8.581e-05  1.368e-02  -0.006 0.994997    \nFREEHOLD              1.531e-01  1.432e-02  10.686  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2199 on 1417 degrees of freedom\nMultiple R-squared:  0.7904,\tAdjusted R-squared:  0.7878 \nF-statistic: 296.9 on 18 and 1417 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\nThe 4 non-significant variables are 'PROX_HAWKER_MARKET', 'PROX_KINDERGARTEN', 'PROX_TOP_PRIMARY_SCH' and 'PROX_SUPERMARKET'.\n\n### **13.8.4 Preparing Publication Quality Table: olsrr method**\n\nWith reference to the report above, it is clear that not all the independent variables are statistically significant. We will revised the model by removing those **4** variables above which are not statistically significant.\n\nNow, we are ready to calibrate the revised model by using the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncondo.mlr14 <- lm(formula = SELLING_PRICE ~ AREA_SQM + AGE + \n                   PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +\n                   PROX_URA_GROWTH_AREA + PROX_MRT  + PROX_PARK + \n                   PROX_PRIMARY_SCH + PROX_SHOPPING_MALL    + PROX_BUS_STOP + \n                   NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD,\n                 data=condo_resale.sf)\n\nols_regress(condo.mlr14)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                             Model Summary                               \n------------------------------------------------------------------------\nR                       0.807       RMSE                     755957.289 \nR-Squared               0.651       Coef. Var                    43.168 \nAdj. R-Squared          0.647       MSE                571471422208.591 \nPred R-Squared          0.638       MAE                      414819.628 \n------------------------------------------------------------------------\n RMSE: Root Mean Square Error \n MSE: Mean Square Error \n MAE: Mean Absolute Error \n\n                                     ANOVA                                       \n--------------------------------------------------------------------------------\n                    Sum of                                                      \n                   Squares          DF         Mean Square       F         Sig. \n--------------------------------------------------------------------------------\nRegression    1.512586e+15          14        1.080418e+14    189.059    0.0000 \nResidual      8.120609e+14        1421    571471422208.591                      \nTotal         2.324647e+15        1435                                          \n--------------------------------------------------------------------------------\n\n                                               Parameter Estimates                                                \n-----------------------------------------------------------------------------------------------------------------\n               model           Beta    Std. Error    Std. Beta       t        Sig           lower          upper \n-----------------------------------------------------------------------------------------------------------------\n         (Intercept)     527633.222    108183.223                   4.877    0.000     315417.244     739849.200 \n            AREA_SQM      12777.523       367.479        0.584     34.771    0.000      12056.663      13498.382 \n                 AGE     -24687.739      2754.845       -0.167     -8.962    0.000     -30091.739     -19283.740 \n            PROX_CBD     -77131.323      5763.125       -0.263    -13.384    0.000     -88436.469     -65826.176 \n      PROX_CHILDCARE    -318472.751    107959.512       -0.084     -2.950    0.003    -530249.889    -106695.613 \n    PROX_ELDERLYCARE     185575.623     39901.864        0.090      4.651    0.000     107302.737     263848.510 \nPROX_URA_GROWTH_AREA      39163.254     11754.829        0.060      3.332    0.001      16104.571      62221.936 \n            PROX_MRT    -294745.107     56916.367       -0.112     -5.179    0.000    -406394.234    -183095.980 \n           PROX_PARK     570504.807     65507.029        0.150      8.709    0.000     442003.938     699005.677 \n    PROX_PRIMARY_SCH     159856.136     60234.599        0.062      2.654    0.008      41697.849     278014.424 \n  PROX_SHOPPING_MALL    -220947.251     36561.832       -0.115     -6.043    0.000    -292668.213    -149226.288 \n       PROX_BUS_STOP     682482.221    134513.243        0.134      5.074    0.000     418616.359     946348.082 \n         NO_Of_UNITS       -245.480        87.947       -0.053     -2.791    0.005       -418.000        -72.961 \n     FAMILY_FRIENDLY     146307.576     46893.021        0.057      3.120    0.002      54320.593     238294.560 \n            FREEHOLD     350599.812     48506.485        0.136      7.228    0.000     255447.802     445751.821 \n-----------------------------------------------------------------------------------------------------------------\n```\n:::\n:::\n\n\n**Confidence** **Interval Interpretation:** The entire confidence interval for age predictor is \\[-30091.739, -19283.740\\]. It means that out of 100 trials, 95/100 times the true coefficient for AGE lies within this range.\n\n**Other tools in the olsrr package**\n\n-   comprehensive regression output\n\n-   residual diagnostics\n\n-   measures of influence\n\n-   heteroskedasticity tests\n\n-   collinearity diagnostics\n\n-   model fit assessment\n\n-   variable contribution assessment\n\n-   variable selection procedures\n\n::: panel-tabset\n## Variable selection methods\n\n1.Best subset Regression\n\nSelect the subset of predictors that do the best at meeting some well-defined objective criterion, such as having the largest R2 value or the smallest MSE, Mallow\\'s Cp or AIC. [Plot](https://olsrr.rsquaredacademy.com/articles/variable_selection) is available.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_step_best_subset(condo.mlr18)\n```\n:::\n\n\n2.Stepwise Forward Regression\n\nBuild regression model from a set of candidate predictor variables by entering predictors based on p values, in a stepwise manner until there is no variable left to enter any more. The model should include all the candidate predictor variables. If details is set to `TRUE`, each step is displayed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_step_forward_p(condo.mlr18)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n                                   Selection Summary                                     \n----------------------------------------------------------------------------------------\n        Variable                              Adj.                                          \nStep          Entered           R-Square    R-Square      C(p)          AIC        RMSE     \n----------------------------------------------------------------------------------------\n   1    AREA_SQM                  0.5006      0.5002    1945.0981     959.7305    0.3375    \n   2    PROX_CBD                  0.7404      0.7400     325.3876      22.1168    0.2434    \n   3    FREEHOLD                  0.7554      0.7548     226.1985     -61.1430    0.2364    \n   4    AGE                       0.7682      0.7676     141.1208    -136.7970    0.2302    \n   5    PROX_ELDERLYCARE          0.7731      0.7723     110.0861    -165.3912    0.2278    \n   6    PROX_MRT                  0.7763      0.7754      90.4947    -183.7457    0.2263    \n   7    PROX_BUS_STOP             0.7824      0.7814      51.0450    -221.6484    0.2232    \n   8    PROX_PARK                 0.7846      0.7834      38.2767    -234.1377    0.2222    \n   9    PROX_SHOPPING_MALL        0.7864      0.7851      28.1903    -244.1056    0.2213    \n  10    PROX_URA_GROWTH_AREA      0.7880      0.7866      19.2242    -253.0511    0.2206    \n  11    PROX_KINDERGARTEN         0.7893      0.7877      12.5514    -259.7671    0.2200    \n  12    PROX_SUPERMARKET          0.7898      0.7881      11.1775    -261.1721    0.2198    \n  13    PROX_CHILDCARE            0.7903      0.7884      10.1287    -262.2561    0.2196    \n----------------------------------------------------------------------------------------\n```\n:::\n:::\n\n\n## Residual Diagnostics\n\n1.Residual QQ plot: Detects violation of standard regression assumptions.\n\nAssumptions:\n\n-   The error has a normal distribution (normality assumption).\n\n-   The errors have mean zero.\n\n-   The errors have same but unknown variance (homoscedasticity assumption).\n\n-   The error are independent of each other (independent errors assumption).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_plot_resid_qq(condo.mlr14)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex4_1_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n2.Residual Normality test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_test_normality(condo.mlr14)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n-----------------------------------------------\n       Test             Statistic       pvalue  \n-----------------------------------------------\nShapiro-Wilk              0.6856         0.0000 \nKolmogorov-Smirnov        0.1366         0.0000 \nCramer-von Mises         121.0768        0.0000 \nAnderson-Darling         67.9551         0.0000 \n-----------------------------------------------\n```\n:::\n:::\n\n\nThe summary table above reveals that the p-values of the four tests are way smaller than the alpha value of 0.05. Hence we will reject the null hypothesis and infer that there is statistical evidence that the residual are **not** normally distributed.\n\n3.Residual vs Fitted Values Plot\n\nIt is a scatter plot of residuals on the y axis and fitted values on the x axis to detect non-linearity, unequal error variances, and outliers.\n\nCharacteristics of a well behaved residual vs fitted plot:\n\n-   The residuals spread randomly around the 0 line indicating that the relationship is linear.\n\n-   The residuals form an approximate horizontal band around the 0 line indicating homogeneity of error variance.\n\n-   No one residual is visibly away from the random pattern of the residuals indicating that there are no outliers\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_plot_resid_fit(condo.mlr14)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex4_1_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nThe spread of residual is wider for higher fitted values .\n\n4.Residual Histogram\n\nHistogram of residuals for detecting violation of normality assumption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_plot_resid_hist(condo.mlr14)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex4_1_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nThe residual appears to resemble a normal distribution, but chart 2 above shows that the residuals are **not** normal distributed.\n\n[Link](https://olsrr.rsquaredacademy.com/articles/residual_diagnostics)\n\n## Heteroskedasticity\n\nF Test for heteroskedasticity under the assumption that the errors are independent and identically distributed (i.i.d.). We can perform the test using the fitted values of the model, the predictors in the model and a subset of the independent variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_test_f(condo.mlr14)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n F Test for Heteroskedasticity\n -----------------------------\n Ho: Variance is homogenous\n Ha: Variance is not homogenous\n\n Variables: fitted values of SELLING_PRICE \n\n        Test Summary         \n ----------------------------\n Num DF     =    1 \n Den DF     =    1434 \n F          =    138.994 \n Prob > F   =    1.096016e-30 \n```\n:::\n:::\n\n\n## Collinearity Diagnostics\n\n1.Check for signs of multicollinearity\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_vif_tol(condo.mlr14)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              Variables Tolerance      VIF\n1              AREA_SQM 0.8728554 1.145665\n2                   AGE 0.7071275 1.414172\n3              PROX_CBD 0.6356147 1.573280\n4        PROX_CHILDCARE 0.3066019 3.261559\n5      PROX_ELDERLYCARE 0.6598479 1.515501\n6  PROX_URA_GROWTH_AREA 0.7510311 1.331503\n7              PROX_MRT 0.5236090 1.909822\n8             PROX_PARK 0.8279261 1.207837\n9      PROX_PRIMARY_SCH 0.4524628 2.210126\n10   PROX_SHOPPING_MALL 0.6738795 1.483945\n11        PROX_BUS_STOP 0.3514118 2.845664\n12          NO_Of_UNITS 0.6901036 1.449058\n13      FAMILY_FRIENDLY 0.7244157 1.380423\n14             FREEHOLD 0.6931163 1.442759\n```\n:::\n:::\n\n\nSince the VIF of the independent variables are less than 10. We can safely conclude that there are no sign of multicollinearity among the independent variables.\n\n2.Observed vs Predicted plot\n\nPlot of observed vs fitted values to assess the fit of the model. Ideally, all points should be close to a regressed diagonal line. Draw such a diagonal line within your graph and check out where the points lie. If your model had a high R Square, all the points would be close to this diagonal line. The lower the R Square, the weaker the Goodness of fit of your model, the more foggy or dispersed your points are from this diagonal line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nols_plot_obs_fit(condo.mlr14)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex4_1_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\n[Link](https://olsrr.rsquaredacademy.com/articles/regression_diagnostics)\n:::\n\n### **13.8.5 Preparing Publication Quality Table: gtsummary method**\n\nThe [**gtsummary**](https://www.danieldsjoberg.com/gtsummary/) package provides an elegant and flexible way to create publication-ready summary tables in R.\n\nIn the code chunk below, [`tbl_regression()`](https://www.danieldsjoberg.com/gtsummary/reference/tbl_regression.html) is used to create a well formatted regression report.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(condo.mlr14, intercept = TRUE)\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"zhiskpfcah\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#zhiskpfcah table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#zhiskpfcah thead, #zhiskpfcah tbody, #zhiskpfcah tfoot, #zhiskpfcah tr, #zhiskpfcah td, #zhiskpfcah th {\n  border-style: none;\n}\n\n#zhiskpfcah p {\n  margin: 0;\n  padding: 0;\n}\n\n#zhiskpfcah .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#zhiskpfcah .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#zhiskpfcah .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#zhiskpfcah .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#zhiskpfcah .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#zhiskpfcah .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#zhiskpfcah .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#zhiskpfcah .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#zhiskpfcah .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#zhiskpfcah .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#zhiskpfcah .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#zhiskpfcah .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#zhiskpfcah .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#zhiskpfcah .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#zhiskpfcah .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zhiskpfcah .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#zhiskpfcah .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#zhiskpfcah .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#zhiskpfcah .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zhiskpfcah .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#zhiskpfcah .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zhiskpfcah .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#zhiskpfcah .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zhiskpfcah .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#zhiskpfcah .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#zhiskpfcah .gt_left {\n  text-align: left;\n}\n\n#zhiskpfcah .gt_center {\n  text-align: center;\n}\n\n#zhiskpfcah .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#zhiskpfcah .gt_font_normal {\n  font-weight: normal;\n}\n\n#zhiskpfcah .gt_font_bold {\n  font-weight: bold;\n}\n\n#zhiskpfcah .gt_font_italic {\n  font-style: italic;\n}\n\n#zhiskpfcah .gt_super {\n  font-size: 65%;\n}\n\n#zhiskpfcah .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#zhiskpfcah .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#zhiskpfcah .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#zhiskpfcah .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#zhiskpfcah .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#zhiskpfcah .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#zhiskpfcah .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt;\"><strong>Beta</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">527,633</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">315,417, 739,849</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AREA_SQM</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">12,778</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">12,057, 13,498</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AGE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-24,688</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-30,092, -19,284</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CBD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-77,131</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-88,436, -65,826</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CHILDCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-318,473</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-530,250, -106,696</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.003</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_ELDERLYCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">185,576</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">107,303, 263,849</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_URA_GROWTH_AREA</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">39,163</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">16,105, 62,222</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_MRT</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-294,745</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-406,394, -183,096</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PARK</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">570,505</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">442,004, 699,006</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PRIMARY_SCH</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">159,856</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">41,698, 278,014</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.008</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_SHOPPING_MALL</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-220,947</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-292,668, -149,226</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_BUS_STOP</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">682,482</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">418,616, 946,348</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">NO_Of_UNITS</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-245</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-418, -73</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.005</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">FAMILY_FRIENDLY</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">146,308</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">54,321, 238,295</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.002</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">FREEHOLD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">350,600</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">255,448, 445,752</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\nWith gtsummary package, model statistics can be included in the report by either appending them to the report table by using [`add_glance_table()`](https://www.danieldsjoberg.com/gtsummary/reference/add_glance.html) or adding as a table source note by using [`add_glance_source_note()`](https://www.danieldsjoberg.com/gtsummary/reference/add_glance.html) as shown in the code chunk below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntbl_regression(condo.mlr14, \n               intercept = TRUE) %>% \n  add_glance_source_note(\n    label = list(sigma ~ \"\\U03C3\"),\n    include = c(r.squared, adj.r.squared, \n                AIC, statistic,\n                p.value, sigma))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ghjcwhvtxh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ghjcwhvtxh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ghjcwhvtxh thead, #ghjcwhvtxh tbody, #ghjcwhvtxh tfoot, #ghjcwhvtxh tr, #ghjcwhvtxh td, #ghjcwhvtxh th {\n  border-style: none;\n}\n\n#ghjcwhvtxh p {\n  margin: 0;\n  padding: 0;\n}\n\n#ghjcwhvtxh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ghjcwhvtxh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ghjcwhvtxh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ghjcwhvtxh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ghjcwhvtxh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ghjcwhvtxh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ghjcwhvtxh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ghjcwhvtxh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ghjcwhvtxh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ghjcwhvtxh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ghjcwhvtxh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ghjcwhvtxh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ghjcwhvtxh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ghjcwhvtxh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ghjcwhvtxh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ghjcwhvtxh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ghjcwhvtxh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ghjcwhvtxh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ghjcwhvtxh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ghjcwhvtxh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ghjcwhvtxh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ghjcwhvtxh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ghjcwhvtxh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ghjcwhvtxh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ghjcwhvtxh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ghjcwhvtxh .gt_left {\n  text-align: left;\n}\n\n#ghjcwhvtxh .gt_center {\n  text-align: center;\n}\n\n#ghjcwhvtxh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ghjcwhvtxh .gt_font_normal {\n  font-weight: normal;\n}\n\n#ghjcwhvtxh .gt_font_bold {\n  font-weight: bold;\n}\n\n#ghjcwhvtxh .gt_font_italic {\n  font-style: italic;\n}\n\n#ghjcwhvtxh .gt_super {\n  font-size: 65%;\n}\n\n#ghjcwhvtxh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ghjcwhvtxh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ghjcwhvtxh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ghjcwhvtxh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ghjcwhvtxh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ghjcwhvtxh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ghjcwhvtxh .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Beta&lt;/strong&gt;\"><strong>Beta</strong></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;95% CI&lt;/strong&gt;&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>95% CI</strong><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;p-value&lt;/strong&gt;\"><strong>p-value</strong></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">527,633</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">315,417, 739,849</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AREA_SQM</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">12,778</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">12,057, 13,498</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">AGE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-24,688</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-30,092, -19,284</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CBD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-77,131</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-88,436, -65,826</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_CHILDCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-318,473</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-530,250, -106,696</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.003</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_ELDERLYCARE</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">185,576</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">107,303, 263,849</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_URA_GROWTH_AREA</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">39,163</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">16,105, 62,222</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_MRT</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-294,745</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-406,394, -183,096</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PARK</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">570,505</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">442,004, 699,006</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_PRIMARY_SCH</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">159,856</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">41,698, 278,014</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.008</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_SHOPPING_MALL</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-220,947</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-292,668, -149,226</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">PROX_BUS_STOP</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">682,482</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">418,616, 946,348</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">NO_Of_UNITS</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">-245</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">-418, -73</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.005</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">FAMILY_FRIENDLY</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">146,308</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">54,321, 238,295</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\">0.002</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">FREEHOLD</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">350,600</td>\n<td headers=\"ci\" class=\"gt_row gt_center\">255,448, 445,752</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"4\">R² = 0.651; Adjusted R² = 0.647; AIC = 42,967; Statistic = 189; p-value = &lt;0.001; σ = 755,957</td>\n    </tr>\n  </tfoot>\n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"4\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> CI = Confidence Interval</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n#### 13.8.5.4 Testing for Spatial Autocorrelation\n\nThe hedonic model we try to build are using geographically referenced attributes, hence it is also important for us to visual the residual of the hedonic pricing model.\n\nIn order to perform spatial autocorrelation test, we need to convert *condo_resale.sf* from sf data frame into a **SpatialPointsDataFrame**.\n\nFirst, we will export the residual of the hedonic pricing model and save it as a data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#| eval: false\n#| echo: false\n#| fig-width: 14\n#| fig-asp: 0.68\n#| code-fold: True\n```\n:::\n\n\n## Summaries\n",
    "supporting": [
      "Hands-on_Ex4_1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/htmlwidgets-1.6.2/htmlwidgets.js\"></script>\r\n<script src=\"../site_libs/plotly-binding-4.10.3/plotly.js\"></script>\r\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\r\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\r\n<link href=\"../site_libs/crosstalk-1.2.0/css/crosstalk.min.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/crosstalk-1.2.0/js/crosstalk.min.js\"></script>\r\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\r\n<script src=\"../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}